### ISSUE TITLE
Time Stamp Command

### ISSUE THREAD

**Issue by joelcorporan** [the-tcpdump-group/libpcap#1007]
How I use the tstamp for the network adapter. This is what I'm typing,

sudo tcpdump -j pcap_list_tstamp_types(pcap_tstamp_adapter() dst port 57441 -tttt -s 65535 -w

but doesn't not work. What I need to do?

**Comment by guyharris** [comment]
> Hi, I have a similar issue. My tcpdump -J gives me only host option. But my NIC supports hardware timestamping.

Please file this in the libpcap issue list as a separate issue, as it might be due to a different problem.
