### ISSUE TITLE
Packets received by filter but not the applicaiotn callback function after calling pcap_breakloop

### ISSUE THREAD

**Issue by HvR-PA** [the-tcpdump-group/libpcap#1011]
This is for an application that uses pcap_loop() to capture undetermined number of packets continuously and process packet info in the callback fucntion until a termination signal is received and pcap_breakloop() is used to stop capture.

Found with testing that after the termination signal a number of packets would have been received by the filter that have not been passed back to the application via callback. This seems to occurs because either not enough packets have not been received or the set timeout have not expired to trigger the callback.

Is there a way to properly handle this situation to retrieve the packets or trigger callback when stopping the pcap loop?

**Comment by infrastation** [comment]
Better late than never. Please see the recently updated **[pcap_breakloop](https://www.tcpdump.org/manpages/pcap_breakloop.3pcap.html)**(3PCAP) man page and confirm whether the described behaviour matches what you observed. If it does not, please see `CONTRIBUTING.md` and provide detailed information about the problem as described there.

**Comment by infrastation** [comment]
Closing due to lack of a detailed description.
