### ISSUE TITLE
Libpcap, compiled on Windows for Windows, doesn't support live packet capture

### ISSUE THREAD

**Issue by clementsbr** [the-tcpdump-group/libpcap#1016]
Successfully compiled both libpcap and tcpdump for Win_x86, however when run I receive an error "live packet capture not supported on this system". Has anyone successfully compiled this tcpdump for packet capture on Windows, box has npcap installed.

**Comment by clementsbr** [comment]
Thank you for the reply, and forgive the likely question I haven't touch C in years. I downloaded the Npcap SDK and extracted it, pointed PACKET_INCLUDE_DIR and PACKET_LIBRARY to the Include and Lib folders, compiled and it built the DLL, recompiled tcpdump, pointing PCAP_INCLUDE_DIR to the npcap and PCAP_LIBRARY to the newly compiled lib. I now get a Entry Point Not Found "PacketGetMonitorMode" could not be located. Thanks again for the help!

**Comment by guyharris** [comment]
`PacketGetMonitorMode()` was added to Npcap in 2016, so either you have a *really* old version of Npcap installed or something else unusual is happening.

In Win_x86, does the "x86" mean that this is 32-bit x86, as opposed to 64-bit x86 (x86-64/x64)?

**Comment by clementsbr** [comment]
I downloaded the SDK Zip file version 1.07 from nmap.org, further to be clear I am not "installing" the SDK but pointing the libpcap at the .lib and .h files. 

Currently I am trying to get it to compile for x86 not _x86-64 to ensure I am compiling all the different pieces properly.

**Comment by guyharris** [comment]
> I am not "installing" the SDK but pointing the libpcap at the .lib and .h files.

You have to unzip the SDK to have .lib and .h files at which to point CMake; that's what "installing" means in that case.

Do you have any version of WinPcap installed?  What version of Npcap do you have installed?

**Comment by infrastation** [comment]
Closing due to the lack of feedback.

**Comment by MathiasDeWeerdt** [comment]
Could this be reopened? I am having the same problem.

**Comment by infrastation** [comment]
Reopening. Please provide detailed diagnostics and the steps to reproduce the problem, as discussed earlier.

**Comment by MathiasDeWeerdt** [comment]
Windows 11 22H2 fully updated
Install libtins using vcpkg latest versions available. 
Installed npcap driver. Version 1.75

![image](https://github.com/the-tcpdump-group/libpcap/assets/7256303/2cb51f5e-e416-4f0f-9fd4-ebf007ebc219)

**Comment by guyharris** [comment]
> If you need more information please ask.

In what directory did you install the WinPcap or Npcap SDK, and what was the `-DPacket_ROOT=` argument you passed to CMake?

**Comment by MathiasDeWeerdt** [comment]
> > If you need more information please ask.
> 
> In what directory did you install the WinPcap or Npcap SDK, and what was the `-DPacket_ROOT=` argument you passed to CMake?

I have it installed in "C:\npcap-sdk" but not referenced anywhere since I didnt find any documentation with libtins or with libpcap for vcpkg. So I assume it handeld it for me. 

Since everything compiles perfectly fine.

**Comment by guyharris** [comment]
> I have it installed in "C:\npcap-sdk" but not referenced anywhere since I didnt find any documentation with libtins or with libpcap for vcpkg.

If you downloaded the libpcap source, or checked it out from Git, in order to build it, you should look in that source for the documentation.

The documentation for building libpcap on various platforms is in the "doc" directory, in files named either "README.{platform}" or "README.{platform}.md" (either unformatted text or Markdown).  The documentation for building on Windows was, until recently, in "README.Win32.md"; in the main branch, it's now in "README.windows.md" (for reasons given in the commit message for cb781a609f22e6b9e049d68026b0dbe07db0eae5 - tl;dr: the 20th century called, they want their Windows back).

> So I assume it handeld it for me.

No, because there's neither standard installation location for either the Npcap or WinPcap SDKs nor a standard guaranteed-to-work way to determine that installation location without the user having to tell the build process where it's installed.  You have to tell the build process where you put it.

> Since everything compiles perfectly fine.

"libpcap without the ability to capture packets" is a legitimate and, in some cases, perhaps *desired* outcome; it lets you write programs that can read pcap files and many pcapng files without having to write you own code to parse those file formats.  As such, not finding support for a capture file format at configure time is not considered an error.

Perhaps, instead, it should, by default, fail if no capture support is found (meaning it didn't find a native capture mechanism on a UN\*X and wasn't told where to find Npcap/WinPcap on windows), and require that the user build with "use the "null" capture mechanism" option if they don't want capture support.

**Comment by MathiasDeWeerdt** [comment]
> > I have it installed in "C:\npcap-sdk" but not referenced anywhere since I didnt find any documentation with libtins or with libpcap for vcpkg.
> 
> If you downloaded the libpcap source, or checked it out from Git, in order to build it, you should look in that source for the documentation.
> 
> The documentation for building libpcap on various platforms is in the "doc" directory, in files named either "README.{platform}" or "README.{platform}.md" (either unformatted text or Markdown). The documentation for building on Windows was, until recently, in "README.Win32.md"; in the main branch, it's now in "README.windows.md" (for reasons given in the commit message for [cb781a6](https://github.com/the-tcpdump-group/libpcap/commit/cb781a609f22e6b9e049d68026b0dbe07db0eae5) - tl;dr: the 20th century called, they want their Windows back).
> 
> > So I assume it handeld it for me.
> 
> No, because there's neither standard installation location for either the Npcap or WinPcap SDKs nor a standard guaranteed-to-work way to determine that installation location without the user having to tell the build process where it's installed. You have to tell the build process where you put it.
> 
> > Since everything compiles perfectly fine.
> 
> "libpcap without the ability to capture packets" is a legitimate and, in some cases, perhaps _desired_ outcome; it lets you write programs that can read pcap files and many pcapng files without having to write you own code to parse those file formats. As such, not finding support for a capture file format at configure time is not considered an error.
> 
> Perhaps, instead, it should, by default, fail if no capture support is found (meaning it didn't find a native capture mechanism on a UN*X and wasn't told where to find Npcap/WinPcap on windows), and require that the user build with "use the "null" capture mechanism" option if they don't want capture support.

Oh, look what I found in the vcpkg ports/patches directory ...

![image](https://github.com/the-tcpdump-group/libpcap/assets/7256303/9f75a184-689c-4d8c-b50e-f8687bd5da69)

**Comment by infrastation** [comment]
Perhaps on Unix-like systems the same logic would be useful too (currently Autoconf automatically defaults to `pcap-null.c` with a warning).

**Comment by guyharris** [comment]
> Perhaps, instead, it should, by default, fail if no capture support is found (meaning it didn't find a native capture mechanism on a UN*X and wasn't told where to find Npcap/WinPcap on windows), and require that the user build with "use the "null" capture mechanism" option if they don't want capture support.

Done.  On Windows, it will tell the user that you need to install Npcap/WinPcap and the corresponding SDK, and tell CMake where the SDK is located.

**Comment by maordadush** [comment]
@guyharris If I use vcpkg so where do I need to add `-DPacket_ROOT=` argument in the libpcap portfile.cmake file?

```
if(EXISTS "${CURRENT_INSTALLED_DIR}/share/winpcap")
    message(FATAL_ERROR "FATAL ERROR: winpcap and libpcap are incompatible.")
endif()

if(VCPKG_TARGET_IS_LINUX)
    message(
"libpcap currently requires the following libraries from the system package manager:
    flex
    libbison-dev
These can be installed on Ubuntu systems via sudo apt install flex libbison-dev"
    )
endif()

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO the-tcpdump-group/libpcap
    REF "libpcap-${VERSION}"
    SHA512 7352ff4d5bded916c0802e4a846fcb6b26e3ea8025dbbf58543abd9d9f6e8f7f5d60e03bcadb222d20434b7e052f663a560d7487af4b81fba74cf5aea040d733
    HEAD_REF master
    PATCHES 
        install-pc-on-msvc.patch
        add-disable-packet-option.patch
)

vcpkg_find_acquire_program(BISON)
get_filename_component(BISON_PATH ${BISON} DIRECTORY)
vcpkg_add_to_path(${BISON_PATH})
vcpkg_find_acquire_program(FLEX)
get_filename_component(FLEX_PATH ${FLEX} DIRECTORY)
vcpkg_add_to_path(${FLEX_PATH})

string(COMPARE EQUAL "${VCPKG_CRT_LINKAGE}" "static" USE_STATIC_RT)

vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
    DISABLE_PARALLEL_CONFIGURE
    OPTIONS
		-DPacket_ROOT="C:/npcap-sdk"
        -DDISABLE_NETMAP=ON
        -DDISABLE_BLUETOOTH=ON
        -DDISABLE_DBUS=ON
        -DDISABLE_RDMA=ON
        -DDISABLE_DAG=ON
        -DDISABLE_SEPTEL=ON
        -DDISABLE_SNF=ON
        -DDISABLE_TC=ON
        -DDISABLE_PACKET=OFF
        -DENABLE_REMOTE=OFF
        -DUSE_STATIC_RT=${USE_STATIC_RT}
)

vcpkg_cmake_install()
vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/LICENSE")

# On Windows 64-bit, libpcap 1.10.1 installs the libraries in a x64 subdirectory of the usual directories
if(VCPKG_TARGET_IS_WINDOWS AND VCPKG_TARGET_ARCHITECTURE STREQUAL "x64")
    set(libsubdir "x64")
    file(GLOB_RECURSE FILES_TO_MOVE "${CURRENT_PACKAGES_DIR}/lib/${libsubdir}/*")
    file(COPY ${FILES_TO_MOVE} DESTINATION "${CURRENT_PACKAGES_DIR}/lib")
    file(GLOB_RECURSE FILES_TO_MOVE "${CURRENT_PACKAGES_DIR}/debug/lib/${libsubdir}/*")
    file(COPY ${FILES_TO_MOVE} DESTINATION "${CURRENT_PACKAGES_DIR}/debug/lib")
    file(GLOB_RECURSE FILES_TO_MOVE "${CURRENT_PACKAGES_DIR}/bin/${libsubdir}/*")
    file(COPY ${FILES_TO_MOVE} DESTINATION "${CURRENT_PACKAGES_DIR}/bin")
    file(GLOB_RECURSE FILES_TO_MOVE "${CURRENT_PACKAGES_DIR}/debug/bin/${libsubdir}/*")
    file(COPY ${FILES_TO_MOVE} DESTINATION "${CURRENT_PACKAGES_DIR}/debug/bin")
    file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/lib/${libsubdir}"
                        "${CURRENT_PACKAGES_DIR}/debug/lib/${libsubdir}"
                        "${CURRENT_PACKAGES_DIR}/bin/${libsubdir}"
                        "${CURRENT_PACKAGES_DIR}/debug/bin/${libsubdir}")
endif()

# Even if compiled with BUILD_SHARED_LIBS=ON, pcap also install a pcap_static library
if(VCPKG_TARGET_IS_WINDOWS AND VCPKG_LIBRARY_LINKAGE STREQUAL "dynamic")
    file(REMOVE "${CURRENT_PACKAGES_DIR}/lib/pcap_static.lib" "${CURRENT_PACKAGES_DIR}/debug/lib/pcap_static.lib")
endif()

vcpkg_fixup_pkgconfig()

if(VCPKG_LIBRARY_LINKAGE STREQUAL "static")
    file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/bin" "${CURRENT_PACKAGES_DIR}/debug/bin")
endif()
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include" "${CURRENT_PACKAGES_DIR}/debug/share" "${CURRENT_PACKAGES_DIR}/share/man")
```
