### ISSUE TITLE
Should libpcap's API headers require VS 2015?

### ISSUE THREAD

**Issue by dmiller-nmap** [the-tcpdump-group/libpcap#1034]
865e63e236b1d521c340bdb1b233e15aeae45665 introduces a check for VS 2015 to ensure `%zu` format string support. Does this belong in the public API headers, or is it only required when building libpcap itself? Npcap users are finding that it affects building their software with the Npcap SDK, so if that could be removed to an internal header that would be preferable.

**Comment by guyharris** [comment]
Note that the main and 1.10 branches of libpcap also require some C99 features, including a C99-compliant `snprintf()`.  See 28e59ef688d13addc6fb5df8362ad61ac6ce826d.  Presumably that doesn't require that applications *using* libpcap use VS 2015.

It's not just `%zu` string support.  Several public libpcap headers also use the `uint8_t`/`uint16_t`/`uint32_t` types.  pcap/pcap.h *itself* currently doesn't, but I'd prefer not to have to ensure that to be true for eternity.

**Comment by guyharris** [comment]
We could do the check in pcap/pcap-inttypes.h and, if the VS version is too old, put in our own definitions of the types, and do something else to ensure that libpcap *itself* isn't built with a pre-VS 2015 compiler.

BTW, does this mean that applications using Npcap will be built with older compilers *and* possibly deployed on systems without the Universal CRT?  If so, is Npcap being *statically* linked with the C runtime?  If not, then it probably needs to be.

**Comment by dmiller-nmap** [comment]
Yes, Npcap is statically linked (`<RuntimeLibrary>MultiThreaded</RuntimeLibrary>`) with the C runtime. We may consider linking with the Universal CRT for Windows 10 installs at a later time.

We haven't declared support for a particular version of Visual Studio. This issue comes via a request from a licensee who wants to build with VS 2012. Our workaround for that licensee was to download the previous Npcap SDK with the libpcap 1.9 headers, since the API is compatible enough. We will continue using more recent versions of VS (currently 2019) to actually build Npcap (including libpcap as wpcap.dll). It looks like there are only a few possibilities, which we'd like your help in sorting out:

1. Libpcap changes its public headers/API to keep support for older compilers.
2. Npcap documents specific VS versions supported by each SDK so licensees can use an older one (forgoing new features in libpcap as need be).
3. Npcap modifies the libpcap public headers distributed with the Npcap SDK to maintain support for older VS versions.

I would much rather not do number 3, not least because it's more work for me and might break things. Option 1 is what I was suggesting here, since I did not see the reason why the compiler version matters for API headers. Obviously it matters for building the library itself, but if we statically link a compatible CRT, would there still be a problem?

It looks like any versions of VS prior to 2015 are in Extended Support, with 2013 being dropped in April 2024. We'll probably have to make a decision on declaring a support lifecycle soon anyway. Knowing where libpcap stands on this will help us make the decision.

**Comment by guyharris** [comment]
Should be fixed by 17f04d83389cb3698a043bf968c8651d7776ceee.

libpcap still requires VS 2015 if you try to build it, but an SDK including the headers should prevent building applications *using* pcap with at least some older versions.
