### ISSUE TITLE
docs: pcap-filter man page - "=" vs "=="

### ISSUE THREAD

**Issue by bubbasnmp** [the-tcpdump-group/libpcap#1044]
It's not clear if `=` and `==` are equal (pun fully intended) on the `pcap-filter` man page.  

[pcap-filter - packet filter syntax](https://www.tcpdump.org/manpages/pcap-filter.7.html)  
  
`expr relop expr

True if the relation holds, where relop is one of >, <, >=, <=, =, !=, and expr is an arithmetic expression composed of integer constants (expressed in standard C syntax), the normal binary operators [+, -, *, /, %, &, |, ^, <<, >>], a length operator, and special packet data accessors.`  
  
`tcp[tcpflags] & (tcp-rst|tcp-ack) == (tcp-rst|tcp-ack)`  
  
`ether[0] & 1 = 0 and ip[16] >= 224`

**Comment by infrastation** [comment]
For what it's worth, `=` and `==` compile to the same packet-matching code.

**Comment by fxlb** [comment]
If I understand well, this line says "==" and "=" are equivalent:
https://github.com/the-tcpdump-group/libpcap/blob/69f105d57366027801c7767b7ba5d379aab09486/scanner.l#L394

**Comment by guyharris** [comment]
> If I understand well, this line says "==" and "=" are equivalent:

You understand correctly.  I've updated the man page in 74b51d5eb4697b59288d2c106e4856b69e893232 to speak of "= or ==" in the "*expr* *relop* *expr*" section.
