### ISSUE TITLE
Double free (crash) if CONFIG_PACKET_MMAP is not available

### ISSUE THREAD

**Issue by crappycrypto** [the-tcpdump-group/libpcap#1054]
If the kernel does not support mmap'ed packet sockets tcpdump crashes.  In this case the code takes the ENOPROTO path in `init_tpacket`

https://github.com/the-tcpdump-group/libpcap/blob/fa91341ab7647521c90b3e34c93026725bfb71dd/pcap-linux.c#L2752

Causing `prepare_tpacket_socket` to return an error. This triggers the error path in `setup_mmapped` which frees `oneshot_buffer` but doesn't zero the pointer in 

https://github.com/the-tcpdump-group/libpcap/blob/fa91341ab7647521c90b3e34c93026725bfb71dd/pcap-linux.c#L2686

The error is propagated to `pcap_activate_linux` which calls `pcap_cleanup_linux` which will attempt to free `oneshot_buffer` again at

https://github.com/the-tcpdump-group/libpcap/blob/fa91341ab7647521c90b3e34c93026725bfb71dd/pcap-linux.c#L835

Tested on debian bullseye tcpdump/libpcap:
* tcpdump 4.99.0
* libpcap 1.11.0

**Comment by guyharris** [comment]
Fixed in 892212ee18f0b45b56b19d58a0da55fa119e4a8d.  Now, instead of crashing, it'll just refuse to capture traffic....

**Comment by guyharris** [comment]
This can occur for other reasons; see issue #1098.
