### ISSUE TITLE
Description of pcap_next_ex return value is not complete

### ISSUE THREAD

**Issue by PeiweiHu** [the-tcpdump-group/libpcap#1059]
The document says pcap_next_ex returns 1 if the packet was read without problems. However, it seems should be > 0. It's better to correct the document if it does.

**Comment by guyharris** [comment]
> it seems should be > 0

Under what circumstances have you found that it returns a value > 1?

**Comment by PeiweiHu** [comment]
> > it seems should be > 0
> 
> Under what circumstances have you found that it returns a value > 1?

Sorry, I looked through pcap_offline_read and thought it will return a number representing packet count, but forgot that only cnt=1 is passed in pcap_next_ex. I will be more careful next time. Sorry again.
