### ISSUE TITLE
Link libpcap with Pybind fail - undefined symbols

### ISSUE THREAD

**Issue by FisherDock** [the-tcpdump-group/libpcap#1065]
Hi, 

I'm linking libpcap with Pybind to generated a shared library (to be used by Python). But when importing module in Python, it said  `"undefined symbol: pcap_dump_close"`.    I'm sure the `libpcap` library were actually linked by viewing `make` message.

After checking symbols with` ldd -r my.so`, there are many (about sixteen) undefined symbols:
```
pcap_dump_close
pcap_geterr
pcap_next
pcap_dump
```
....

My environment
Ubuntu 20.24,  Libpcap 1.10 source build. I linked `libpcap.a` or `libpcap.so`, and they all failed. 

The trick thing is the test code written in C++ (which calls functions from the shared library) works fine.

I appreciate your help. Thanks

**Comment by infrastation** [comment]
Could you provide exact steps to reproduce this?

**Comment by infrastation** [comment]
This bug report will be closed in 7 days if it does not have the steps to reproduce.

**Comment by infrastation** [comment]
it is time.
