### ISSUE TITLE
AppVeyor setup: enable warning -> error with Visual Studio?

### ISSUE THREAD

**Issue by fxlb** [the-tcpdump-group/libpcap#1066]
On AppVeyor CI, currently all the Visual Studio builds give "0 Warning(s)".
The only builds with warnings are the MinGW ones.

Should we enable warnings treated as errors (like -Werror) on the Visual Studio builds to get new warnings more easily?

**Comment by guyharris** [comment]
Already done by default in CMakeLists.txt if we have a .devel file; see the section beginning with the comment "# Check and add warning options if we have a .devel file." - and the section of .appveyor.yml beginning with the comment "Appveyor defaults to cmd.exe, so use cmd.exe syntax.", which does `type NUL >.devel` to force builds to be done in "developer mode" with warnings turned on.

We don't turn `-Werror` on with non-MSVC compilers yet.

**Comment by fxlb** [comment]
Ok, thanks!
