### ISSUE TITLE
Filter on IP field does not work when MPLS is present. 

### ISSUE THREAD

**Issue by edgar-costa** [the-tcpdump-group/libpcap#1070]
**Version:**

tcpdump version 4.9.3
libpcap version 1.8.1
OpenSSL 1.1.1  11 Sep 2018

I have experienced some weird behaviour when trying to match to `IP tos` field, when MPLS is present. To show you what happens, I am simply pinging between two nodes, the ping goes encapsulated over mpls, while the reply has no mpls. For all the experiments I am sending one single ping (request and reply). 

```
sudo tcpdump -n  -i POR-eth2 -vv
tcpdump: listening on POR-eth2, link-type EN10MB (Ethernet), capture size 262144 bytes
01:25:49.817640 MPLS (label 1 (router alert), exp 0, [S], ttl 62)
        IP (tos 0x0, ttl 64, id 32764, offset 0, flags [DF], proto ICMP (1), length 84)
    10.0.15.1 > 10.0.2.1: ICMP echo request, id 2323, seq 1, length 64
01:25:49.834338 IP (tos 0x0, ttl 61, id 42664, offset 0, flags [none], proto ICMP (1), length 84)
    10.0.2.1 > 10.0.15.1: ICMP echo reply, id 2323, seq 1, length 64
```

So far, so good. And as you can see, for both packets it parses the `IP tos` field. However, I want to only capture packets with some specific tos field, thus I use the filter `ip[1]==tos`.  However, when doing so, `mpls` packets are not displayed, only the IP ping reply. 

```
sudo tcpdump -n  -i POR-eth2 -vv ip[1]==0
tcpdump: listening on POR-eth2, link-type EN10MB (Ethernet), capture size 262144 bytes
01:27:52.422301 IP (tos 0x0, ttl 61, id 64249, offset 0, flags [none], proto ICMP (1), length 84)
    10.0.2.1 > 10.0.15.1: ICMP echo reply, id 2630, seq 1, length 64
```

Ok, I thought I need to extend the filter to have mpls && ip[1]==0 or ip[1]==0. So if i try that... for some reason I am only getting the `mpls` packet, why?

```
sudo tcpdump -n  -i POR-eth2 -vv "(mpls && ip[1]==0) or ip[1]==0"
tcpdump: listening on POR-eth2, link-type EN10MB (Ethernet), capture size 262144 bytes
01:30:37.420896 MPLS (label 1 (router alert), exp 0, [S], ttl 62)
        IP (tos 0x0, ttl 64, id 57604, offset 0, flags [DF], proto ICMP (1), length 84)
    10.0.15.1 > 10.0.2.1: ICMP echo request, id 3046, seq 1, length 64
```

However, if I if keep the same filter, but I reverse the logical expression it does work, like why?? I am missing something, is this a bug? See below:

```
sudo tcpdump -n  -i POR-eth2 -vv "ip[1]==0 or (mpls && ip[1]==0)"
tcpdump: listening on POR-eth2, link-type EN10MB (Ethernet), capture size 262144 bytes
01:32:13.875259 MPLS (label 1 (router alert), exp 0, [S], ttl 62)
        IP (tos 0x0, ttl 64, id 65009, offset 0, flags [DF], proto ICMP (1), length 84)
    10.0.15.1 > 10.0.2.1: ICMP echo request, id 3286, seq 1, length 64
01:32:13.891797 IP (tos 0x0, ttl 61, id 48789, offset 0, flags [none], proto ICMP (1), length 84)
    10.0.2.1 > 10.0.15.1: ICMP echo reply, id 3286, seq 1, length 64
```

Is there any difference between the last two expressions? I could not find anything in the documentation.

Thanks!

**Comment by infrastation** [comment]
For posterity, there is now a [FAQ entry](https://www.tcpdump.org/faq.html#q13) about this.
