### ISSUE TITLE
Is it safe to modify "bytes" (received packet) in packet handler?

### ISSUE THREAD

**Issue by ghuser187** [the-tcpdump-group/libpcap#1077]
Hello,

My application looks like:

```
//...includes
void p_handler(u_char *user, const struct pcap_pkthdr *h, const u_char *bytes) {
    u_char *bytes2=(u_char*)bytes;
    for(int i=0;i<6;i++) {
	u_char tmp=bytes2[i];
	bytes2[i]=bytes2[i+6];
	bytes2[i+6]=tmp;
    }
    pcap_inject((pcap_t*)user, bytes2, h->caplen);
}

int main(int argc, char * const argv[]) {
    //...init pcap code...
    pcap_loop(p, 0, p_handler, (u_char* )p);
    return 0;
}

```

so... I converted const u_char* to u_char* and then modified received packet and sent it back. It works but I'm not sure if is safe or not. I don't want to copy memory every time when it's required to send packet like received. Can somebody help me to understand if I'm using libpcap correct or not?

**Comment by guyharris** [comment]
> It works but I'm not sure if is safe or not.

We do not guarantee that it is safe.

> I don't want to copy memory every time when it's required to send packet like received.

We do not support that.

**Comment by ghuser187** [comment]
@guyharris thank you for your reply
