### ISSUE TITLE
Interface has snapshot length xxxxx different from the snapshot length of the first interface

### ISSUE THREAD

**Issue by kmccleanWork** [the-tcpdump-group/libpcap#1078]
Version: latest and master branch

Unable to read a pcap with multiple interfaces that contain different snapshot lengths. 

To Reproduce: 
- We merged together multiple pcaps with different snapshot lengths.

**Comment by infrastation** [comment]
Please be more specific. How did you merge the files? Can you provide any examples of the input and the output files? What is the issue with the output file? Are there any associated error codes or messages?

**Comment by guyharris** [comment]
> Unable to read a pcap with multiple interfaces that contain different snapshot lengths.

By "pcap" you presumably mean "pcapng capture file".  (Could people stop using "pcap" to mean "capture file", and reserve it to mean "capture file in pcap format"?)

Given that, this is an inherent limitation of the current libpcap API, which has:

- `pcap_datalink()`, which "returns the link-layer header type for the live capture  or '\'\savefile'';
- `pcap_snapshot()`, which "returns the snapshot length specified when **pcap_set_snaplen(3PCAP)** or **pcap_open_live(3PCAP)** was called, for a live capture, or the snapshot length from the capture file, for a \'\'savefile'';

both of which make the assumption that there *is* "*the* link-layer type for the ... or savefile" and "*the* ... snapshot length from the capture file, for a savefile".

When libpcap was originally written, the only format for a savefile was pcap format, which stores the link-layer type and snapshot length in the file header, and supports only one link-layer type and snapshot length for a file.

We added *limited* support for pcapng files in the 1.1 release; it added no new routines to the API, and only supports pcapng files in which all the interfaces have the same link-layer type and snapshot length.

Fixing this will require adding new interfaces to expose the full capabilities of pcapng (while still transparently allowing pcap files to be read); for any *given* program to read all pcapng files, it will have to be changed to use the new interfaces if they're available (tcpdump will probably be the first program to which support is added).

So this issue will be used as an enhancement issue for the new interfaces.

(Note that the filter interfaces are a sticking point, as the current BPF compiler generates code for a specific link-layer type, and that won't work with arbitrary pcapng files.  Either the program has to say "use this filter expression", with the compilation done for each link-layer type seen, or some partial compilation that doesn't assume a particular link-layer type must be done, with the final code generation done for each link-payer type seen, or something such as that.)

**Comment by guyharris** [comment]
> From what I understand this is not planned to be supported

It is not planned to be supported with the *current* API routines.  We want to support it with *new* API routines that fully support pcapng but...

> and would be a large amount of work to support.

Yes.

**Comment by kmccleanWork** [comment]
Thanks very much, I will close this.
