### ISSUE TITLE
CMake (version 3.22.1) Deprecation Warning

### ISSUE THREAD

**Issue by fxlb** [the-tcpdump-group/libpcap#1094]
```
CMake Deprecation Warning at CMakeLists.txt:16 (cmake_policy):
  The OLD behavior for policy CMP0042 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.
```

**Comment by guyharris** [comment]
[Policy CMP0042](https://cmake.org/cmake/help/v3.23/policy/CMP0042.html) affects macOS; I'll have to see what else would have to change, if anything, and what side effects it would have.

**Comment by fxlb** [comment]
More information here:
https://cmake.org/cmake/help/latest/policy/CMP0042.html

**Comment by fxlb** [comment]
There is a fix proposal in this PR: #1111.

**Comment by guyharris** [comment]
See also 16e1e243a9e9f03d8e8f4ee1067ba46795439a8d.

**Comment by infrastation** [comment]
That's a good idea. In case any other long-standing warnings remain in the problem space, the build scripts might need to introduce something such as `LIBPCAP_CMAKE_TAINTED` and `TCPDUMP_CMAKE_TAINTED`.

**Comment by fxlb** [comment]
Done for libpcap with 0898548236721388d576d330971113eb23e2e517.

**Comment by fxlb** [comment]
Done for tcpdump with https://github.com/the-tcpdump-group/tcpdump/commit/625657ada89f6ab9056e3f918edb7052d3067438.
