### ISSUE TITLE
Dropped packets when snaplen > 600

### ISSUE THREAD

**Issue by guyharris** [the-tcpdump-group/libpcap#11]
Converted from [SourceForge issue 612342](http://sourceforge.net/support/tracker.php?aid=612342), submitted by bkosbab

If I set the snaplength parameter to a value that is > 600, libpcap does not capture all packets.  The problem grows worse as the snaplength value increases.  However, if I set the value to a small value such as 64 libpcap gets 100% of the packets.

Platform is 500Mhz Sun Blade 100 with Solaris 8.2, 64-bit kernel.

**Comment by infrastation** [comment]
Closing as troubleshooting isn't feasible.

**Comment by guyharris** [comment]
This might just be a result of running out of buffer space - the bigger the snapshot length, the more space packets take in the STREAMS queue (for DLPI, which is what's being used here, given that it's Solaris 8 - BPF wasn't introduced until Solaris 11).

For DLPI, libpcap sets the "chunk size" to 65536; a comment claims that this is the largest value to which it can be set.  If that's the case, this may be the best we can do for Solaris until Solaris 11, where we use BPF.
