### ISSUE TITLE
Diag macros for _MSC_VER/__clang__

### ISSUE THREAD

**Issue by gvanem** [the-tcpdump-group/libpcap#1101]
Some libpcap headers have blocks like:
```c
#if defined(_MSC_VER)
  ...
#elif PCAP_IS_AT_LEAST_CLANG_VERSION(2,8)
  ...
#endif
```

But using `clang-cl` on Windows to compile with (a MSVC-compatible compiler driver), this includes `_MSC_VER` as
a built-in. Hence the above blocks should be swapped:
```c
#if PCAP_IS_AT_LEAST_CLANG_VERSION(2,8)
  ...
#elif defined(_MSC_VER)
  ...
#endif
```
(or read `#if defined(_MSC_VER) && !defined(__clang__)`).

I'm not sure what was the first version of `clang-cl`. But it's safe to ass-u-me it was > ver. 2.8.

**Comment by guyharris** [comment]
Fixed in 49c94a759ccfebf157d549954b5254ecc39ee53d.
