### ISSUE TITLE
pcap_activate return -6 for compatible wifi device

### ISSUE THREAD

**Issue by oldtune** [the-tcpdump-group/libpcap#1102]
Hi, I'm noob to this and what i'm trying to do is to set my network interface to monitor mode. I successfully set the interface to monitor mode by using
```
ifconfig wlp3s0 down
iwconfig wlp3s0 mode monitor
ifconfig wlp3s0 up
```
but when using the ```pcap_set_rfmon``` and ```pcap_activate```. It just keep returning -6 on ```pcap_activate```.
Here's my code:
```
#include <pcap.h>
main()
{
    char error_buffer[PCAP_ERRBUF_SIZE];
    pcap_t *handle;
    int result;

    handle = pcap_create("wlp3s0", error_buffer);
    if (handle == NULL)
    {
        printf("failed to create a handle: %s\n",
               error_buffer);
        return 2;
    }

    result = pcap_set_rfmon(handle, 1);
    if (result != 0)
    {
        printf("failed to set pcap rfmon: %s (%s)\n",
               pcap_statustostr(result),
               pcap_geterr(handle));
        return 2;
    }

    result = pcap_activate(handle);
    if (result != 0)
    {
        printf("failed to activate handle: %s (%s)\n",
               pcap_statustostr(result),
               pcap_geterr(handle));
        return 2;
}
```
i built the program using: ```gcc try_pcap.c -l pcap```
and ran it using root permission ```sudo ./a.out```

**Comment by guyharris** [comment]
-6 is `PCAP_ERROR_RFMON_NOTSUP`; it means that monitor mode isn't supported.  The error message you got presumably indicated that.

On Linux, in libpcap 1.10 or later, monitor mode is only supported if libpcap was configured to use libnl.

**Comment by infrastation** [comment]
Closing as resolved.
