### ISSUE TITLE
Bug: Why `DllMain` is still kept in pcap.c and it indeed does nothing? 

### ISSUE THREAD

**Issue by r4ve1** [the-tcpdump-group/libpcap#1127]
I'm developing a shared dll on Windows using CMake + vcpkg + MSVC, and I need `libpcap` to be statically linked into it. 
By setting the proper CMake variables, I got most of the part worked, but during linking, the linker report this problem: 

<img width="530" alt="image" src="https://user-images.githubusercontent.com/59314380/194758776-4ec2c923-1e5b-4cb4-8424-7a8654815674.png">

Then I found there is a `DllMain` in `pcap.c` and seems it does nothing. 
Don't know why it's kept, someone please explain to me.
Or if it's just a piece of junk code, will it be removed someday in the future?

**Comment by guyharris** [comment]
> Don't know why it's kept, someone please explain to me.

Because it was overlooked with the (Windows-only) critical section was removed when the work was done to make the pcap compiler thread-safe.

**Comment by r4ve1** [comment]
Fixed and I'll close this issue 👍

**Comment by r4ve1** [comment]
I reopened this issue because I think a tag should be granted for this fix, otherwise other projects like vcpkg that uses a tag to reference this project can't be gracefully updated 🤔

**Comment by infrastation** [comment]
Such as `libpcap-1.10.2` after backporting the bu fix and making the release?

**Comment by r4ve1** [comment]
Yep that will be enough

**Comment by r4ve1** [comment]
What do you think 🤔? If you add a tag I can then request to update libpcap's port in vcpkg, really need this fixed.

**Comment by infrastation** [comment]
You would have either to wait until the release (this might take time) or to apply the fixing commit to your copy of libpcap.

**Comment by infrastation** [comment]
Thank you for waiting, the bug fix is now available via the `libpcap-1.10.2` git tag as discussed.
