### ISSUE TITLE
How many  pcap_open_live  can be opened simultaneously in a process?

### ISSUE THREAD

**Issue by chushuai** [the-tcpdump-group/libpcap#1128]

**Comment by guyharris** [comment]
A number that depends on

- the operating system on which you're running;
- the limits the operating system places on open file descriptors (UN\*X)/HANDLEs (Windows) per process (at least on UN\*Xes, the limit may be settable);
- the type of device you're trying to open.

On most UN|*Xes, each live capture will consume one file descriptor; on Linux, with newer versions of libpcap, opens of regular interfaces will consume two (one of which is used to cause `pcap_breakloop()` to immediately wake up a `pcap_dispatch()`/`pcap_loop()`/`pcap_next()`/`pcap_next_ex()` if it's blocked).

**Comment by infrastation** [comment]
This question has been answered in detail, closing.
