### ISSUE TITLE
PCAP_TIMEOUT=1000 pcap_snaplen=1500; Is it possible to drop packets?

### ISSUE THREAD

**Issue by chushuai** [the-tcpdump-group/libpcap#1130]
pc = pcap_open_live(iface, pcap_snaplen, PCAP_PROMISC, PCAP_TIMEOUT, errbuf);

**Comment by infrastation** [comment]
```
To report bugs and other problems, contribute patches, request a
feature, provide generic feedback etc please see the file
CONTRIBUTING.md in the libpcap source tree root.
```
This text is in the new issue template for a reason. If there is a practical problem, please read the file and follow the provided guidelines.

**Comment by guyharris** [comment]
And the answer is "it depends".

Presumably this question is being asked about high packet rates; if one packet arrives per hour, the answer is almost certainly "no".

Given that, it depends on how quickly the program reads and processes the packets, and on how large the packet buffer in the kernel is.

For Ethernet, that snapshot length is only 14 bytes shorter than the packets you'll typically receive (1514 bytes, with the Ethernet header but without the CRC), so the snapshot length won't help much, if at all - all it will do is chop off the last 14 bytes of the Ethernet payload in a full-sized packets (and chop off between 1 and 13 bytes in packets of a size between 1501 and 1513 total bytes, including the Ethernet header).
