### ISSUE TITLE
pcap_compile update?

### ISSUE THREAD

**Issue by sychen12345** [the-tcpdump-group/libpcap#1132]
Excuse me, how does this method update the filtering rules?
/*filter communication
	 *pcap_compile(pcap_t *p,struct bpf_program *fp,char *str,int optimize,bpf_u_int32 netmask)
	 *int pcap_setfilter(pcap_t *p, struct bpf_program *fp)
 */

**Comment by infrastation** [comment]
As can be seen from libpcap source code, each libpcap module implements its own `pcap_setfilter()` function. So as soon as you determine which specific module interests you and which source file implements it, it will be easier to take it from there. If this request does not require any follow-up, it will be closed before the end of 2022.

**Comment by guyharris** [comment]
`pcap_compile()` turns a filter in text format, such as "host 127.0.0.1 and port 137", into BPF pseudo-machine code.

`pcap_setfilter()` sets a BPF pseudo-machine code program a a filter for a `pcap_t`.  As Denis noted, the way that happen depends on whether you're capturing from a device or reading from a file and, if you're capturing from a device, the device from which you're capturing.

**Comment by infrastation** [comment]
It is time.
