### ISSUE TITLE
"Could not activate the pcap handler" error from Scapy trying to open en0 in monitor mode

### ISSUE THREAD

**Issue by 2076625923** [the-tcpdump-group/libpcap#1136]
I try to sniffer wi-fi on ubuntu, I use Scapy and Python, but I can’t get the dBm_AntNoise of wi-fi, there is an OSError:Could not activate the pcap handler, (PCAP_ERROR -1 ).
my codes are as follows:
from scapy.all import *

conf.use_pcap=True

def callBack(pkg):
    if pkg.haslayer(Dot11):
        if pkg.type == 0 and pkg.subtype == 8:
            print("dBm_AntSignal",pkg.dBm_AntSignal)
            print("dBm_AntNoise=",pkg.dBm_AntNoise)
            
sniff(iface='en0', monitor='True', prn=callBack)

my error like this:
File "/usr/local/lib/python3.10/site-packages/scapy/arch/libpcap.py", line 247, in __init__
    raise OSError("Could not activate the pcap handler")
OSError: Could not activate the pcap handler

**Comment by guyharris** [comment]
I suggest you check the Scapy documentation to see whether there's a way to get the error message text provided by libpcap for `PCAP_ERROR`, and arrange to get that error.  Otherwise, we can only attempt to guess what the most likely causes is for this error.

**Comment by infrastation** [comment]
`en0` is an unusual network interface name for a Linux system. On the Internet people comment that macOS uses `en0` for its wireless interface, so it seems possible that the code you are trying to run on Linux was developed on macOS, in which case it would be your responsibility to handle the differences.

However, if the Linux system in fact has a wireless interface named `en0`, it would help to check that you are using the latest stable version of Scapy and libpcap, which might already have a fix for the root cause of this fault, whatever it is.

**Comment by 2076625923** [comment]
Actually, "wlp1s1" is my network interface name, I have set it into monitor mode, the Scapy version is 2.5.0rc2, the libpcap version is 1.9.1, the python version is 3.8.10. When I use wireshark to capture packets in wlp1s1, the dBm_AntNoise is absent in Radiotap Header.

**Comment by 2076625923** [comment]
Actually, I want to get the wifi SIGNAL-NOISE RATIO by sniffer, my codes can run on MacOS, but it can work on ubuntu for some unknown reasons, Who can help me?

**Comment by guyharris** [comment]
> my codes can run on MacOS, but it can work on ubuntu for some unknown reasons

If you mean "but it ***can't*** work on ubuntu for some unknown reasons", then:

For code that does `sniff(iface='en0', monitor='True', prn=callBack)`, the reason is known:

There. Is. No. Device. Named. "en0". On. A. Linux. Box.

"en0" is, ***on macOS***, the name of the Wi-Fi interface on an Apple laptop with no built-in Ethernet interface (i.e., any modern Apple laptop).

So, if your Wi-Fi interface is named "wlp1s1", capture on *that*, not on "en0".

**Comment by 2076625923** [comment]
This is my real codes:
#!~/Project/python/venv/bin/python3
from scapy.all import *
from scapy.config import conf
from scapy.layers.dot11 import Dot11


conf.use_pcap = True


def call_back(pkg):
    if pkg.haslayer(Dot11):
        if pkg.type == 0 and pkg.subtype == 8:
            print("dBm_AntSignal=", pkg.dBm_AntSignal)
            print("dBm_AntNoise=", pkg.dBm_AntNoise)
            print("-----------------")


interface = 'wlp1s1'
sniff(iface=interface, monitor='True', prn=call_back)

**Comment by 2076625923** [comment]
This my error:
/home/chowhao/Project/python/venv/bin/python /home/chowhao/Project/python/scn/demo/test4.py 
/home/chowhao/Project/python/venv/lib/python3.8/site-packages/scapy/layers/ipsec.py:471: CryptographyDeprecationWarning: Blowfish has been deprecated
  cipher=algorithms.Blowfish,
/home/chowhao/Project/python/venv/lib/python3.8/site-packages/scapy/layers/ipsec.py:485: CryptographyDeprecationWarning: CAST5 has been deprecated
  cipher=algorithms.CAST5,
Traceback (most recent call last):
  File "/home/chowhao/Project/python/scn/demo/test4.py", line 19, in <module>
    sniff(iface=interface, monitor='True', prn=call_back)
  File "/home/chowhao/Project/python/venv/lib/python3.8/site-packages/scapy/sendrecv.py", line 1263, in sniff
    sniffer._run(*args, **kwargs)
  File "/home/chowhao/Project/python/venv/lib/python3.8/site-packages/scapy/sendrecv.py", line 1127, in _run
    sniff_sockets[L2socket(type=ETH_P_ALL, iface=iface,
  File "/home/chowhao/Project/python/venv/lib/python3.8/site-packages/scapy/arch/libpcap.py", line 376, in __init__
    self.ins = open_pcap(iface, MTU, self.promisc, 100,
  File "/home/chowhao/Project/python/venv/lib/python3.8/site-packages/scapy/arch/libpcap.py", line 247, in __init__
    raise OSError("Could not activate the pcap handler")
OSError: Could not activate the pcap handler

Process finished with exit code 1

**Comment by guyharris** [comment]
> File "/home/chowhao/Project/python/venv/lib/python3.8/site-packages/scapy/arch/libpcap.py", line 247, in **init** raise OSError("Could not activate the pcap handler") OSError: Could not activate the pcap handler

Well, Scapy gets today's award for throwing away information provided by libpcap.  That error messages is only a slight improvement over "Something didn't work".  TIme to file a bug against Scapy to get that improved....

There are a *lot* of reasons why `pcap_activate()` might fail, and that error message fails to indicate which one it was.

Are you running this script as root?  By default, Linux will only let root open a PF_PACKET socket, so Linux will only let root attempt to sniff packets.

**Comment by 2076625923** [comment]
Yes, I run my code as root user. The error code is -1(PCAP_ERROR)

**Comment by guyharris** [comment]
> The error code is -1(PCAP_ERROR)

How did you determine this?  Scapy doesn't return the error code from `pcap_activate()`, it just reports the not-very-useful error "Could not activate the pcap handler" if the return value is non-zero (which is bogus for *multiple* reasons - - for one thing, `pcap_activate()` can return a *warning*, which means that the pcap handler *could* be activated, and *was* activated, but there was a problem that should be reported to the user).

**Comment by guyharris** [comment]
Just apply [these changes](https://github.com/secdev/scapy/pull/3796/files), from secdev/scapy#3796, to your copy of Scapy and try again, so that we can get a useful error message for this case.

**Comment by 2076625923** [comment]
this is the original code about line 246 in scapy/arch/libpcap.py:

 if pcap_activate(self.pcap) != 0:
         raise OSError("Could not activate the pcap handler")
---------------------------------------------------------------------------------
I have changed the code as follows to get the error code
code = pcap_activate(self.pcap)
if code != 0:
     raise OSError("Could not activate the pcap handler", code)

**Comment by infrastation** [comment]
User @2076625923, please pay attention and do as the developer asks you. This is your last warning.

**Comment by infrastation** [comment]
Closing due to lack of feedback.
