### ISSUE TITLE
CMake Deprecation Warning at CMakeLists.txt:7 (cmake_minimum_required)

### ISSUE THREAD

**Issue by fxlb** [the-tcpdump-group/libpcap#1138]
https://github.com/the-tcpdump-group/libpcap/blob/2180b6e56a5538c3c3720f22cc3491f02b5276e4/CMakeLists.txt#L7
```
CMake Deprecation Warning at CMakeLists.txt:7 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
```

**Comment by fxlb** [comment]
cmake v2.8.6 on Oct 4, 2011.
cmake v2.8.12 on Oct 8, 2013.
All tests in CI with 2.8.12 are OK (#1141).
(Windows minimum required is already 3.12.)
Thus I think we can update the minimum required VERSION to 2.8.12 (or later).

**Comment by infrastation** [comment]
I do not know what the rationale is, but it would help to understand the reason for the current requirement and whether it still works as originally intended.

Is there a simple way to try the current source with CMake 2.8.6 (using an old Linux distribution, for example) to see if it still works?

**Comment by guyharris** [comment]
> I do not know what the rationale is, but it would help to understand the reason for the current requirement

At one point, that was the version of CMake that was provided for the version of Solaris 11 I had on a VM.

I now have another Solaris 11 VM with a 3.x version.

Unless there's some ancient "proudly trailing edge" enterprise Linux distribution version that we need to care about and that comes with a pre-2.8.12 version, I'd update the version.

**Comment by infrastation** [comment]
Thank you for explaining. As far as rpm.pbone.net search results go, even RHEL 7 has CMake 2.8.12, so even the most conservative bump up should be straightforward.
