### ISSUE TITLE
run error: undefined reference to 'pcap_dump_open_append'

### ISSUE THREAD

**Issue by dshup** [the-tcpdump-group/libpcap#1140]
libpcap version : 1.10.1
pcap.h show me that pcap_dump_open_append was avaliable in 1.7
readelf -s libpcap.so.1.10.1, pcap_dump_open_append exist

So when executed program, why it showed "undefined reference to 'pcap_dump_open_append' "?

**Comment by infrastation** [comment]
Please see with which shared library the program links:
```
ldd /path/to/program | grep libpcap
```
Then you can see that shared library version and whether it has the function:
```
strings /path/to/libpcap.so | grep 'libpcap version'
nm -D /path/to/libpcap.so | grep pcap_dump_open_append
```

**Comment by dshup** [comment]
> Please see with which shared library the program links:
> 
> ```
> ldd /path/to/program | grep libpcap
> ```
> 
> Then you can see that shared library version and whether it has the function:
> 
> ```
> strings /path/to/libpcap.so | grep 'libpcap version'
> nm -D /path/to/libpcap.so | grep pcap_dump_open_append
> ```

thank you!!! there is no problem with so file and functions.

**Comment by infrastation** [comment]
In this case, if the problem still stands, you can try the following:
```
LD_DEBUG=symbols /path/to/program
LD_DEBUG=bindings /path/to/program
```
This is going to be a lot of output, so please before posting the results here study the output closely and pick only the lines that are relevant to the undefined reference. If possible, please post exact steps to reproduce the problem and any other relevant information.

**Comment by infrastation** [comment]
This problem no longer stands, correct?

**Comment by infrastation** [comment]
Closing as not reproducible.
