### ISSUE TITLE
Wrong install location for pcap-util.h?

### ISSUE THREAD

**Issue by rfrancoise** [the-tcpdump-group/libpcap#1149]
Hi,

1.10.2 includes a new header file `pcap-util.h` which gets installed to the prefix root, e.g. `/usr/include/pcap-util.h`.

I would have expected it to be installed as `/usr/include/pcap/util.h` and used via `#include <pcap/util.h>` instead, following the pattern for other new header files.

Thanks.

**Comment by infrastation** [comment]
Thank you for reporting this issue. From the contents of the file it seems as if this header was not supposed to be in `PUBHDR` because only libpcap source code needs it to compile, but not libpcap users. @guyharris, could you confirm please?

**Comment by guyharris** [comment]
No, it wasn't intended to be installed.  Sorry, my bad.  Let's move it from `PUBHDR` to `HDR`.

**Comment by rfrancoise** [comment]
Thanks. I'll cherry-pick the fix before I upload 1.10.2 to Debian/Ubuntu, then. We don't want anyone to start using this file.

**Comment by guyharris** [comment]
Fix in 2958853565585bed6a02e0ecda7fb598e320f152 and ecdafb17a21463fc550326080b2169aada3ca060 in main and in 663a4e0e881d373a4a7bccdeba977a0a217167ae and 48845c295a1bfc0300e59c9ad5889af111fab209 in the 1.10 branch.

Should we re-release 1.10.2, or leave this for 1.10.3?

**Comment by infrastation** [comment]
Thank you. 1.10.2 has been published, so it would be best to let 1.10.3 include this bug fix. If necessary, 1.10.3 could be released sooner than it would usually happen.

**Comment by infrastation** [comment]
This is resolved in libpcap 1.10.3, which is now available for download. Closing as resolved.
