### ISSUE TITLE
how to configure、make and make install libpcap in Windows operating system？

### ISSUE THREAD

**Issue by Cloudyunn** [the-tcpdump-group/libpcap#1150]
Can I compile libpcap under Windows operating system? When I install other software under Windows, I need to rely on the libpcap library:

ERROR! libpcap library not found, go get it from http://www.tcpdump.org or your distribution:

However, I lack the libpcap library, which makes it impossible for me to continue. When downloading the source code and running "./configure" as required, it reports an error:

![image](https://user-images.githubusercontent.com/73875002/210740630-4f3d3366-21ca-4858-8368-058ff55e332b.png)

I can't solve the problem after looking up many documents, so I can't compile libpcap under Windows operating system, can I? I've seen someone say that one port for installing libpcap to Windows is WinPcap; It includes necessary drivers, but my computer is also configured with npcap/winpcap, but still displays libpcap library not found. Is there any solution?

Thanks for checking~

**Comment by guyharris** [comment]
> Can I compile libpcap under Windows operating system?

Yes.

>  When downloading the source code and running "./configure" as required, it reports an error:

We do not support using the configure script when building on Windows; we only support using CMake.  [Here's our documentation on using Visual Studio and CMake to build Wireshark.](https://github.com/the-tcpdump-group/libpcap/blob/master/doc/README.Win32.md)

> I've seen someone say that one port for installing libpcap to Windows is WinPcap; It includes necessary drivers, but my computer is also configured with npcap/winpcap, but still displays libpcap library not found.

WinPcap and Npcap are both ports for installing libpcap on Windows.  WinPcap is no longer being developed or supported, and is based on an old version of libpcap; Npcap *is* being developed and supported, and is based on  a recent version of libpcap.

However, to build with Npcap, you must install the Npcap SDK.  See [the Npcap home page](https://npcap.com) to download the SDK.

Note also that, as the documentation on building libpcap on Windows indicates, you'd need to install Npcap and its SDK even just to build libpcap on Windows.

**Comment by Cloudyunn** [comment]
> 
Hello, I have compiled libpcap according to the requirements in this document： [https://github.com/the-tcpdump-group/libpcap/blob/master/doc/README.Win32.md](https://github.com/the-tcpdump-group/libpcap/blob/master/doc/README.Win32.md)but I still encounter some problems. There is no pcap.sln file in the libpcap file I generated. Is there something missing in the configuration process?For example, aircap, I have queried some information, but there is no relevant prompt... The specific error report is as follows:


```
D:\software\libpcap>cmake -G "MinGW Makefiles" "-DPacket_ROOT=C:/npcap_sdk" D:/software/libpcap1.10.1 -Wno-dev
-- Checking C compiler flag -std=gnu99
-- checking for Npcap's version.h
-- MISSING version.h
-- Use STATIC runtime
-- Support IPv6
-- Packet capture mechanism type: npf
-- Executing Finddpdk
-- Executing find_path
-- Could NOT find dpdk (missing: dpdk_INCLUDE_DIRS)
-- Checking for module 'dbus-1'
--   Package 'dbus-1', required by 'virtual:world', not found
-- Could NOT find DAG (missing: DAG_INCLUDE_DIR DAG_LIBRARY DAGCONF_LIBRARY)
-- Could NOT find SNF (missing: SNF_INCLUDE_DIR SNF_LIBRARY)
CMake Warning at CMakeLists.txt:1836 (find_package):
  By not providing "FindAirPcap.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "AirPcap", but
  CMake did not find one.

  Could not find a package configuration file provided by "AirPcap" with any
  of the following names:

    AirPcapConfig.cmake
    airpcap-config.cmake

  Add the installation prefix of "AirPcap" to CMAKE_PREFIX_PATH or set
  "AirPcap_DIR" to a directory containing one of the above files.  If
  "AirPcap" provides a separate development package or SDK, be sure it has
  been installed.


-- Could NOT find TC (missing: TC_INCLUDE_DIR TC_LIBRARY)
-- Checking C compiler flag -fvisibility=hidden
-- Lexical analyzer generator: C:/Program Files/winflexbison/win_flex.exe
-- Parser generator: C:/Program Files/winflexbison/win_bison.exe
-- Configuring done
-- Generating done
-- Build files have been written to: D:/software/libpcap
```

My own configuration process:

1. Npcap installed
2. Install npcap, wpdpack, winflexbison and other sdks, and put them in the specified path as required
3. Install cmake
4. Execute the command: cmake - G "MinGW Makefiles" "- DPacket_ROOT=C:/npcap_sdk" D:/software/libpcap1.10.1

Is there any problem with my configuration process?We look forward to your help
