### ISSUE TITLE
bpf_filter.c listed in the gitignore

### ISSUE THREAD

**Issue by Jimmyscene** [the-tcpdump-group/libpcap#1166]
As I was looking around the repo, I noticed that bpf_filter.c is listed in the gitignore, which doesn't seem correct to me.

Looking through the history it seems that file used to be auto-generated but is no longer. 
This is a super minor issue just thought I'd report it.

https://github.com/the-tcpdump-group/libpcap/blob/e57217b331b6afdacacaefe829ec419df9bad30d/.gitignore#L5

**Comment by infrastation** [comment]
Thank you for reporting this inconsistency, commit bbb12dc in the master branch fixes it.

**Comment by guyharris** [comment]
>  that file used to be auto-generated

It used to be an auto-generated symlink to, I think, net/bpf_filter.c, but we no longer store it in that subdirectory, it's now in the top-level directory.
