### ISSUE TITLE
Wireshark make our program dropless?

### ISSUE THREAD

**Issue by guoyaobit** [the-tcpdump-group/libpcap#1167]
Multi-process capture on the same NIC  is better than single-process.
Even running wireshark on the background ,make the our capture program drop less.
Why ?

**Comment by infrastation** [comment]
If you still experience the problem, please provide detailed steps to reproduce. Otherwise this request will be closed.

**Comment by guoyaobit** [comment]
> If you still experience the problem, please provide detailed steps to reproduce. Otherwise this request will be closed.

We apologize for not being able to figure it out at the moment. Perhaps the issue lies in the relationship between multiple NPCAP applications on Windows, especially in extremely high-speed situations.

**Comment by infrastation** [comment]
Please reopen after you have a detailed description of the problem.

**Comment by guyharris** [comment]
Note also that a lot of the packet capture code on any platform is in the underlying capture mechanism that libpcap uses.

On Windows with Npcap, that's the Npcap NPF driver and the packet32.dll library that uses it.  (On Linux, that would be the PF_PACKET socket code, and on \*BSDs, including ~~CupertinoBSD~~macOS, and in AIX and Solaris, the would be the BPF packet capture mechanism.)

None of those are developed and maintained by us.  For Npcap, you might want to file an issue on [the Npcap issues list](https://github.com/nmap/npcap).
