### ISSUE TITLE
Issue on Windows with timestamping types (frozen timestamps)

### ISSUE THREAD

**Issue by nikodul** [the-tcpdump-group/libpcap#1219]
Hi,

OS: Windows 11
SDK: NPCAP 1.13, x64
libpcap master branch

On Windows, after testing on at least two computers, we figured out that activating certain timestamping types alter the behaviour of other timestamping types.
In the attached capture test (modified from the capture test program on the git), we open, capture and close a device several times, with different timestamping types.
Where as the captured packets timestamping seem to work ok in the first round of timestamping types, switching back to PCAP_TSTAMP_HOST captures packets with frozen timestamps.

Restarting the program does not fix the problem: timestamps are frozen except with PCAP_TSTAMP_HOST_LOWPREC and PCAP_TSTAMP_HOST_HIPREC which still seem to work ok.

Only rebooting seems to re-enable correct timestamping with other types (e.g. PCAP_TSTAMP_HOST, PCAP_TSTAMP_HOST_HIPREC_UNSYNCED), until once again the faulty mode is activated (PCAP_TSTAMP_HOST_LOWPREC or PCAP_TSTAMP_HOST_HIPREC or both).

Attached: the capturetest.c file that allows to reproduce the issue, and a log that shows frozen timestamps. (rename capturetest.txt to capturetest.c).

[capturetest.txt](https://github.com/the-tcpdump-group/libpcap/files/12513864/capturetest.txt)
[test.log](https://github.com/the-tcpdump-group/libpcap/files/12513871/test.log)

Can you reproduce the issue?
We didn't test under Linux yet.

**Comment by guyharris** [comment]
> We didn't test under Linux yet.

99 44/100% of the code path for packet timestamping is outside libpcap; it's in the packet capture mechanism code.  Testing on Linux might well find its own "interesting" issues, but they will probably be completely different issues, so 1) testing the behavior on other OSes might find results worthy of being filed as issues but 2) would be irrelevant to issues found on other platforms.

**Comment by guyharris** [comment]
> OS: Windows 11
> SDK: NPCAP 1.13, x64
> libpcap master branch

Which version of Npcap?  (Npcap version numbers and Npcap SDK numbers are not related.)

**Comment by guyharris** [comment]
> Restarting the program does not fix the problem: timestamps are frozen except with PCAP_TSTAMP_HOST_LOWPREC and PCAP_TSTAMP_HOST_HIPREC which still seem to work ok.

In Npcap, `PCAP_TSTAMP_HOST`, `PCAP_TSTAMP_HOST_LOWPREC`, and `PCAP_TSTAMP_HOST_HIPREC` all involve the Npcap driver calling routines in the NT kernel to provide the time stamp.

`PCAP_TSTAMP_HOST_HIPREC_UNSYNCED`, however, combines an OS-provided capture start time and initial performance counter value with the current performance counter value to get a time stamp.

So my *guess* is that testing any of the non-UNSYNCED HOST types, followed by testing `PCAP_TSTAMP_HOST_HIPREC_UNSYNCED`, followed by testing with any of the non-UNSYNCED HOST types (not necessarily the one you start with), will show the same results.

My guess is *also* that this is a function of the time stamping code in the Npcap driver, meaning that the right place to file this issue would be on [the Npcap issue list](https://github.com/nmap/npcap/issues).

**Comment by guyharris** [comment]
> (rename capturetest.txt to capturetest.c).

Time for me (and everybody else annoyed by this) to file an issue against GitHub itself.  I'm not sure what their rationale is for disallowing ".c" files as a type of file to upload (or any *other* source code file type), but it gets in the way of people filing issues from uploading test programs (they can do it, but they have to give it a different extension).

See, for example, https://github.com/orgs/community/discussions/4077 (the "answer" to which doesn't answer the main question) and https://github.com/orgs/community/discussions/34909 (which is unanswered).  I've upvoted both of those, and will file another one to deal with https://github.com/orgs/community/discussions/4077 having been "answered" with an answer to the parenthetical note at the end but not having been *answered* with an answer to the request to upload a PDF.

**Comment by nikodul** [comment]
Thanks for the rapid and smart analysis!
Npcap version is 1.76 (so, the most recent).
I'll then open an issue on the Npcap issue list.
