### ISSUE TITLE
Error with flex command --header-file=NUL:

### ISSUE THREAD

**Issue by MonicaLiu0311** [the-tcpdump-group/libpcap#1227]
Using the `flex` command with [`--header-file=NUL:`](https://github.com/the-tcpdump-group/libpcap/blob/libpcap-1.10.4/CMakeLists.txt#L2529-L2545) results in the following error:
```
error delete file C:\Users\AzDevOps\AppData\Local\Temp\~1_flex_5win_flex.exe: error deleting file C:\Users\AzDevOps\AppData\Local\Temp\~flex_out_main_2
CMake Error at CMakeLists.txt:2539 (message):
  D:/downloads/tools/win_flex/2.5.25/win_flex.exe is insufficient to compile
  libpcap.

  libpcap requires Flex 2.5.31 or later, or a compatible version of lex.

  If a suitable version of Lex/Flex is available as a non-standard command

  and/or not in the PATH, you can specify it using the LEX environment

  variable.  That said, on some systems the error can mean that Flex/Lex is

  actually acceptable, but m4 is not.  Likewise, if a suitable version of

  m4 (such as GNU M4) is available but has not been detected, you can

  specify it using the M4 environment variable.
```

Changing to `--header-file=NULL` can solve the issue. For details, see: https://github.com/microsoft/vcpkg/pull/34670.

**Comment by guyharris** [comment]
We do not appear to see this error when configuring with CMake on either Windows or any UN*X - it merely causes the header file to be written to the null device, as we don't care about any of Flex's output when doing that test, we just want to see whether it succeeds, or fails, trying to generate a scanner from scanner.l.  See [my comment in microsoft/vcpkg#34670](https://github.com/microsoft/vcpkg/pull/34670#issuecomment-1774801277).
