### ISSUE TITLE
duplicate link-layer headers are being written to a pcap file

### ISSUE THREAD

**Issue by folkertvanheusden** [the-tcpdump-group/libpcap#1231]
Hi,

I'm seeing duplicate pcap-headers in the generated .pcap-file when using libpcap:

```
0000000 c3d4 a1b2 0002 0004 0000 0000 0000 0000
0000020 ffff 0000 0003 0000 c3d4 a1b2 0002 0004
0000040 0000 0000 0000 0000 ffff 0000 0003 0000
0000060 9ff4 6554 4495 0000 0030 0000 0030 0000
0000100 a6a2 40a8 4040 a060 7288 ac8c 6390 cd03
0000120 0300 cc00 0407 0100 88a0 8c72 90ac c002
```
Above you see c3d4 etc twice. Wireshark also complains about this file (it being corrupted).

[test-kiss-ad94.zip](https://github.com/the-tcpdump-group/libpcap/files/13363477/test-kiss-ad94.zip)

The code causing this is:

```c++
        std::mutex pcap_lock;
        pcap_t   *ph                  { nullptr };
        pcap_dumper_t *pdh            { nullptr };
...
        std::unique_lock<std::mutex> lck(pcap_lock);

        if (!ph)
                ph = pcap_open_dead_with_tstamp_precision(3, 65535, PCAP_TSTAMP_PRECISION_MICRO);

        if (pdh)
                CDOLOG(ll_error, "[phys]", "pcap already running\n");
        else {
                pdh = pcap_dump_open(ph, pcap_file.c_str());
                if (!pdh)
                        error_exit(false, "pcap_dump_open(%s) failed: %s", pcap_file.c_str(), pcap_geterr(ph));
        }
```

I also created a test-program to see if I can reproduce it but that program does not show the problem. I added a printf to sf_write_header (libpcap function) and verified that it is called only once (also verified using ltrace).

The test program which does **NOT** show the behaviour is:

```c++
#include <pcap.h>
#include <stdio.h>
#include <sys/time.h>

unsigned char test_dat[] = {
  0xa0, 0x88, 0x72, 0x8c, 0xac, 0x90, 0x03, 0xa0, 0x88, 0x72, 0x8c, 0xac,
  0x90, 0x05, 0x03, 0xcd, 0x00, 0x03, 0x00, 0xcc, 0x07, 0x04, 0x00, 0x02,
  0xa0, 0x88, 0x72, 0x8c, 0xac, 0x90, 0x65, 0xc0, 0xa8, 0x64, 0x02, 0xa0,
  0x88, 0x72, 0x8c, 0xac, 0x90, 0x00, 0xc0, 0xa8, 0x64, 0x01, 0xeb, 0xc2
};
unsigned int test_dat_len = 48;

int main(int argc, char *argv[])
{
        pcap_t        *ph  = pcap_open_dead_with_tstamp_precision(3, 65535, PCAP_TSTAMP_PRECISION_MICRO);
        pcap_dumper_t *pdh = pcap_dump_open(ph, "test.pcap");

        pcap_pkthdr header { 0 };
        gettimeofday(&header.ts, nullptr);
        header.len = header.caplen = test_dat_len;

        for(int i=0; i<10; i++) {
                pcap_dump(reinterpret_cast<u_char *>(pdh), &header, test_dat);
                header.ts.tv_usec++;
        }

        pcap_dump_close(pdh);

        return 0;
}
```

Any ideas?

**Comment by mcr** [comment]
````
pcap_dump_open(ph, pcap_file.c_str());
````

what do you think this is doing?

**Comment by mcr** [comment]
I don't see a loop in your test program where you read the packets from ph, and then write them to pdh.

**Comment by folkertvanheusden** [comment]
> ```c++
> pcap_dump_open
> ```

What I *think* I'm doing there, is first allocate some structure which describes the session (pcap_open_dead_with_tstamp_precision) and then using pcap_dump_open create a new file. Isn't that right?

**Comment by guyharris** [comment]
> I don't see a loop in your test program where you read the packets from ph,

That's a "dead" handle, used to create the dump handle (`pcap_dump()`, unfortunately, makes the assumption that the *only* source of packets to be written is a live capture with libpcap or a capture file being read with libpcap), so the code won't be reading packets from it.

But we *do* need the code that's getting the packets from whatever source it gets them, and then writing them with `pcap_dump()`, as the code *getting* the packets may be, somehow, causing double link-layer headers to appear.  Without that, we cannot determine why duplicate link-layer headers are appearing in the file.

**Comment by folkertvanheusden** [comment]
The code is in this repo:
* https://github.com/folkertvanheusden/MyIP/

In https://github.com/folkertvanheusden/MyIP/blob/master/phys.cpp#L83 there's a method called start_pcap which creates the .pcap-file and the next 3 methods are for closing the file, and writing packets to it.

In https://github.com/folkertvanheusden/MyIP/blob/master/main.cpp#L456 the capture is started and at e.g. https://github.com/folkertvanheusden/MyIP/blob/master/phys_kiss.cpp#L288 a packet is written.

**Comment by guyharris** [comment]
Try dumping the contents of the blob of bytes provided by `ax25_packet::generate_packet()` in `phys_kiss::transmit_ax25()` to see whether it has only one link-layer header or has two of them.

**Comment by folkertvanheusden** [comment]
Well, it is AX.25 over KISS (kiss is a framing protocol to transmit AX.25 packets over serial/rs232 alike connections to a tnc (device that transmits the packet over radio)). And in my tests it is even IPv4 over AX.25 over KISS. Do you mean that that confuses wireshark?

**Comment by guyharris** [comment]
No, I mean that if a hex dump of the raw bytes provided by `ax25_packet::generate_packet()` shows

```
0000000 c3d4 a1b2 0002 0004 0000 0000 0000 0000
0000020 ffff 0000 0003 0000 c3d4 a1b2 0002 0004
0000040 0000 0000 0000 0000 ffff 0000 0003 0000
0000060 9ff4 6554 4495 0000 0030 0000 0030 0000
0000100 a6a2 40a8 4040 a060 7288 ac8c 6390 cd03
0000120 0300 cc00 0407 0100 88a0 8c72 90ac c002
```

then it means that the double link-layer header is being generated by `ax25_packet::generate_packet()`.

**Comment by folkertvanheusden** [comment]
Ah, no that is not in the raw bytes of the first 5 packets that I dumped that way.
E.g. the packet:
```
0000000 a0 88 72 8c ac 90 03 a0 88 72 8c ac 90 05 03 cd
0000020 00 03 00 cc 07 04 00 02 a0 88 72 8c ac 90 65 c0
0000040 a8 64 02 a0 88 72 8c ac 90 00 c0 a8 64 01 eb c2
```
and the pcap file:
```
0000000 d4 c3 b2 a1 02 00 04 00 00 00 00 00 00 00 00 00
0000020 ff ff 00 00 03 00 00 00 d4 c3 b2 a1 02 00 04 00
0000040 00 00 00 00 00 00 00 00 ff ff 00 00 03 00 00 00
0000060 e8 25 55 65 86 86 0a 00 30 00 00 00 30 00 00 00
0000100 a2 a6 a8 40 40 40 60 a0 88 72 8c ac 90 63 03 cd
```

Also strange that I don't see the packet literally in the pcap-file. As if some corruption takes place somewhere.

**Comment by guyharris** [comment]
> and the pcap file:
> 
> ```
> 0000000 d4 c3 b2 a1 02 00 04 00 00 00 00 00 00 00 00 00
> 0000020 ff ff 00 00 03 00 00 00 d4 c3 b2 a1 02 00 04 00
> 0000040 00 00 00 00 00 00 00 00 ff ff 00 00 03 00 00 00
> 0000060 e8 25 55 65 86 86 0a 00 30 00 00 00 30 00 00 00
> 0000100 a2 a6 a8 40 40 40 60 a0 88 72 8c ac 90 63 03 cd
> ```

That pcap file dump shows *two* copies of the magic number (`d4 c3 b2 a1`).

Do you have two handles open, both writing to the same file?

**Comment by infrastation** [comment]
At a glance, the presence of a mutex hints there may be more than one thread trying to write to the same file after opening, which could explain the duplicate header.

**Comment by folkertvanheusden** [comment]
@guyharris only 1 handle per file, that's where the md5 trickery of the devicename+index is for https://github.com/folkertvanheusden/MyIP/blob/master/phys.cpp#L96

@infrastation Multiple threads can write to the file but due to the mutex this cannot (should not) happen concurrently.

**Comment by guyharris** [comment]
Well, *somebody*'s causing two writes of pcap file header data to the file.

If you're using a version of libpcap that supports `pcap_dump_flush()`, try doing a `pcap_dump_flush()`, with the mutex held, after the one-and-only call to `pcap_dump_open()`, and after every call to `pcap_dump()`.

**Comment by folkertvanheusden** [comment]
@guyharris indeed with the flush no double headers are seen.

Using ltrace I verified that only 1 thread (the main) creates the files (using pcap_dump_open) in the version without flush?!

**Comment by guyharris** [comment]
> indeed with the flush no double headers are seen.

So this is probably a case where two threads are causing the buffer for the `FILE *` that's being used by the pcap writing routines in libpcap to be written to the underlying file.

> Using ltrace I verified that only 1 thread (the main) creates the files (using pcap_dump_open) in the version without flush?!

Make sure that, at *no* point, is more than one thread doing *anything* with the handle, including closing it.

**Comment by fxlb** [comment]
> Well, it is AX.25 over KISS

You use 3 as linktype  in pcap_open_dead_with_tstamp_precision() call.
3 is DLT_AX25 /  LINKTYPE_AX25 
DLT_AX25_KISS / LINKTYPE_AX25_KISS are: 202.

**Comment by folkertvanheusden** [comment]
> > indeed with the flush no double headers are seen.
> 
> So this is probably a case where two threads are causing the buffer for the `FILE *` that's being used by the pcap writing routines in libpcap to be written to the underlying file.

Makes sense!
Thanks for your support. I'll close the bug.
