### ISSUE TITLE
[VCPKG] libpcap for Windows, doesn't support live packet capture

### ISSUE THREAD

**Issue by maordadush** [the-tcpdump-group/libpcap#1238]
Hi,

If I use vcpkg to install libpcap(x64-windows-static), where do I need to add `-DPacket_ROOT=` argument in the libpcap portfile.cmake file to support live packet capture?

> https://github.com/the-tcpdump-group/libpcap/issues/1016

thanks!

**Comment by guyharris** [comment]
There is no "portfile.cmake" file in the libpcap source; that's presumably a vcpkg file.

CMake needs to have Packet_ROOT defined before the check in libpcap's CMakeLists.txt for the packet capture mechanism is done.  Ask the vcpkg people how that should be accomplished.
