### ISSUE TITLE
pcap_pkthdr caplen is 0

### ISSUE THREAD

**Issue by rprp413** [the-tcpdump-group/libpcap#1249]
This issue is occurring in v1.10.3. I'm capturing using non-blocking pcap_dispatch and my packet handling function seems to be collecting packets properly and dumping them into the file because I can open the file in Wireshark and see that there are packets. But I cannot seem to track the size since caplen is 0 and the len field is sometimes the same large number (in this case 896715280) or 0. Is there a change that causes this to happen? I think I could calculate the size in version 1.10.0.

**Comment by rprp413** [comment]
I am running this on a custom linux embedded device that has linux kernel 5.4.245. It is ARM based.

The code that I have is:

```
void handler(u_char *myData, const struct pcap_pkthdr *packetHeader, const u_char *packet)
{
   MyObject *obj = reinterpret_cast<MyObject*>(myData);
   assert(obj);
   unsigned int capLen = packetHeader->caplen; // this is 0
   unsigned int len        = packetHeader->len;      // this is sometimes 0, sometimes a large number
   size_t totalCaptureSize = obj->getSize();
   if((size + capLen) > MaxSize)
   {
      obj->SetFull();
      return;
   }
   
   obj->setSize(size + capLen);
   pcap_dump(reinterpret_cast<u_char*>(obj->getDumper()), packetHeader, packet);
}
```

**Comment by rprp413** [comment]
It is ARMv7, so 32-bit. I am cross-compiling the application from 64-bit Linux.

Here is the output:
Offset of ts.tv_sec is 0, size of ts.tv_sec is 8
Offset of ts.tv_usec is 8, size of ts.tv_usec is 8
Offset of caplen is 16, value of caplen is 0
Offset of len is 20, value of len is 898193936

**Comment by guyharris** [comment]
Try cross-compiling this C program for your ARMv7 machine on your 64-bit machine, running it on the ARMv7 machine, and report its output:

```
#include <stdio.h>
#include <time.h>

int
main(void)
{
	time_t now = time(NULL);

	printf("%s", ctime(&now));
	return 0;
}
```

**Comment by rprp413** [comment]
This is the output I get:
Thu Dec 14 15:03:54 2023

**Comment by guyharris** [comment]
Now try that with this program (note that it has a one-second delay, so don't kill it if it doesn't respond instantly):

```
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <sys/time.h>

struct twotime {
	struct timeval time1;
	struct timeval time2;
};

int
main(void)
{
	struct twotime times;
	char *timestr;
	char *nl;

	if (gettimeofday(&times.time1, NULL) == -1) {
		fprintf(stderr, "First gettimeofday() failed: %s\n",
		    strerror(errno));
		return 2;
	}
	sleep(1);
	if (gettimeofday(&times.time2, NULL) == -1) {
		fprintf(stderr, "Second gettimeofday() failed: %s\n",
		    strerror(errno));
		return 2;
	}
	timestr = ctime(&times.time1.tv_sec);
	nl = strchr(timestr, '\n');
	if (nl != NULL)
		*nl = '\0';
	printf("Time 1: %s.%06d\n", timestr, times.time1.tv_usec);
	timestr = ctime(&times.time2.tv_sec);
	nl = strchr(timestr, '\n');
	if (nl != NULL)
		*nl = '\0';
	printf("Time 2: %s.%06d\n", timestr, times.time2.tv_usec);
	return 0;
}
```

**Comment by rprp413** [comment]
I get:

Time 1: Thu Dec 14 15:49:29 2023.568972
Time 2: Thu Dec 14 15:49:30 2023.569128

**Comment by guyharris** [comment]
Try this:

```
#include <stdio.h>
#include <sys/time.h>

int
main(void)
{
	printf("sizeof(time_t) is %zu\n", sizeof(time_t));
	return 0;
}
```

**Comment by rprp413** [comment]
Returns: sizeof(time_t) is 4.

**Comment by guyharris** [comment]
Now add

```
std::cerr << "sizeof(time_t) is " << sizeof(time_t) << "\n"
```

to your program, before the other printouts, and try that.

**Comment by rprp413** [comment]
There has been changes to use 64 bit times, perhaps that is the issue...

**Comment by rprp413** [comment]
It says it is 8

**Comment by rprp413** [comment]
We seemed to have started defining __USE_TIME_BITS64, which is making the size 8 instead of 4.

**Comment by guyharris** [comment]
> We seemed to have started defining __USE_TIME_BITS64, which is making the size 8 instead of 4.

If you are using a library that 1) provides to its callers data structures that depend on the size of `time_t` - libpcap is such a library - and 2) was built with `__USE_TIME_BITS64` being defined differently from how your program is build, Bad Things Will Happen.

There's not much we can do about it.

**Comment by rprp413** [comment]
You are saying that libpcap has to have time_t defined as 32 bit to return those values correctly?

**Comment by guyharris** [comment]
> I think I understand what you mean. I should build libpcap with the same def.

Yes - if your program is built with `__USE_TIME_BITS64` defined, it will have to be linked with a version of libpcap that's built with `__USE_TIME_BITS64` defined - *and*, if it's dynamically rather than statically linked with libpcap, there will have to be a dynamically-linked version of libpcap, built with `__USE_TIME_BITS64` defined, on the target machine, such that your program will link with that version at run time.

This may apply to other libraries used by your program as well.
