### ISSUE TITLE
Legacy BPF Packet access instructions

### ISSUE THREAD

**Issue by V0idk** [the-tcpdump-group/libpcap#1335]
https://www.kernel.org/doc/html/v6.1/bpf/linux-notes.html#id3

![image](https://github.com/the-tcpdump-group/libpcap/assets/17514799/2570014d-e8eb-4105-9188-21fcc4ae3b84)

Will this effect? i see tcpdump -dd is still using legacy instructions, i don't know if it will cause compatibility issues

![image](https://github.com/the-tcpdump-group/libpcap/assets/17514799/c249b938-042f-4813-b25e-74d4aadeb9e6)

**Comment by guyharris** [comment]
> Will this effect?

What do you mean by that?

> i see tcpdump -dd is still using legacy instructions

There are two separate machine languages called "BPF" - the original language, developed by the LBL Network Group, sometimes now called "cBPF" for "classic BPF", and the new "extended" or "enhanced" or whatever BPF, originally developed for Linux, called "eBPF". See "[classic BPF vs. eBPF](https://www.kernel.org/doc/html/v6.1/bpf/classic_vs_extended.html)".

Libpcap currently only generates cBPF code.  The Linux kernel originally only supported cBPF code in filters and I think may not have supported setting eBPF filters on sockets even when eBPF support was available in the kernel; I think it now supports both.  It translates cBPF programs into eBPF programs.

So libpcap - and programs that use it, such as tcpdump and Wireshark - aren't using *any* eBPF instructions, they're using cBPF instructions.  The "legacy BPF" instructions are *eBPF* instructions, so libpcap isn't using them.  Those instructions are, presumably, primarily used by binary-to-binary translators that translate cBPF code into eBPF code.

> i don't know if it will cause compatibility issues

The only compatibility issue would be if the Linux kernel removed the cBPF-to-eBPF translator.  If support for the "legacy BPF" eBPF instructions were removed, the cBPF-to-eBPF translator would have to use different instructions.

I don't expect that to happen any time soon, and I suspect it will be along time, if ever, before the cBPF-to-eBPF translator si removed.
