### ISSUE TITLE
I have installed libpcap-1.10.4 on arm64, but it still prompts' undefined 'during go build

### ISSUE THREAD

**Issue by lichao5585** [the-tcpdump-group/libpcap#1338]
I have installed libpcap-1.10.4 on arm64, but it still prompts' undefined 'during go build 
![image](https://github.com/user-attachments/assets/8593d0ca-3378-4835-a949-803f1ccf6d14)

**Comment by guyharris** [comment]
None of those functions are part of libpcap.

They are part of [GoPacket](https://github.com/google/gopacket/tree/master).

You should file this as an issue with gopacket on [the GoPacket issues list](https://github.com/google/gopacket/issues/).
