### ISSUE TITLE
 configure problems with checks on snprintf() when using some sanitize options

### ISSUE THREAD

**Issue by fxlb** [the-tcpdump-group/libpcap#1396]
- [x] This is not a security issue (See first line).

On Debian 12:
```
CC="clang-16" CFLAGS='-fsanitize=undefined,integer,signed-integer-overflow -fno-sanitize-recover=undefined,integer -fno-omit-frame-pointer -fno-optimize-sibling-calls -fPIC -g3 -ggdb3 -O0' ./configure
[...]
checking whether snprintf is suitable... no
configure: error: The snprintf(3) implementation in this libc is not suitable,
libpcap would not work correctly even if it managed to compile.

in config.log:
conftest.c:43:37: runtime error: negation of 100 cannot be represented in type 'unsigned long'
    #0 0x55ea26c29867 in main /home/cpe/soft-origin/tcpdump/my-libpcap/conftest.c:43:37

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior conftest.c:43:37
```
Pb with:
`snprintf(buf, sizeof(buf), "%zd", -sizeof(buf));`

If lines 231-233 are commented in configure.ac, after ./autogen.sh, also:
```
[...]
checking whether snprintf is suitable... no
configure: error: The snprintf(3) implementation in this libc is not suitable,
libpcap would not work correctly even if it managed to compile.

in config.log:
conftest.c:47:42: runtime error: negation of 4294967296 cannot be represented in type 'uint64_t' (aka 'unsigned long')
    #0 0x55f0538e6873 in main /home/cpe/soft-origin/tcpdump/my-libpcap/conftest.c:47:42

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior conftest.c:47:42
```
Pb with:
`snprintf(buf, sizeof(buf), "%" PRId64, -t);`

**Comment by guyharris** [comment]
> On Debian 12:

And on macOS 13 with Xcode 15.

Tcpdump's configure script does the same thing; Denis copied the changes for libpcap from the tcpdump configure script.

The following change appears to fix it:

```
diff --git a/configure.ac b/configure.ac
index e3a2590d..e01a4458 100644
--- a/configure.ac
+++ b/configure.ac
@@ -222,29 +222,32 @@ AC_RUN_IFELSE(
 int main()
 {
   char buf[100];
-  uint64_t t = (uint64_t)1 << 32;
+  unsigned int ui = sizeof(buf);
+  int i = sizeof(buf);
+  int64_t i64 = INT64_C(0x100000000);
+  uint64_t ui64 = UINT64_C(0x100000000);
 
-  snprintf(buf, sizeof(buf), "%zu", sizeof(buf));
+  snprintf(buf, sizeof(buf), "%zu", (size_t)ui);
   if (strncmp(buf, "100", sizeof(buf)))
     return 1;
 
-  snprintf(buf, sizeof(buf), "%zd", -sizeof(buf));
+  snprintf(buf, sizeof(buf), "%zd", (ssize_t)(-i));
   if (strncmp(buf, "-100", sizeof(buf)))
     return 2;
 
-  snprintf(buf, sizeof(buf), "%" PRId64, -t);
+  snprintf(buf, sizeof(buf), "%" PRId64, -i64);
   if (strncmp(buf, "-4294967296", sizeof(buf)))
     return 3;
 
-  snprintf(buf, sizeof(buf), "0o%" PRIo64, t);
+  snprintf(buf, sizeof(buf), "0o%" PRIo64, ui64);
   if (strncmp(buf, "0o40000000000", sizeof(buf)))
     return 4;
 
-  snprintf(buf, sizeof(buf), "0x%" PRIx64, t);
+  snprintf(buf, sizeof(buf), "0x%" PRIx64, ui64);
   if (strncmp(buf, "0x100000000", sizeof(buf)))
     return 5;
 
-  snprintf(buf, sizeof(buf), "%" PRIu64, t);
+  snprintf(buf, sizeof(buf), "%" PRIu64, ui64);
   if (strncmp(buf, "4294967296", sizeof(buf)))
     return 6;
 
```

It assumes a power-of-2 word size, but if you don't have a power-of-2 word size, you will probably have problems with libpcap and tcpdump that would require significant reworking, and the only non-power-of-2-word-size machine I know of that supports a UN\*X was the BBN C Machine and that's *long* dead.

It also assumes that neither 1) passing a `sizeof` expression to `snprintf()` nor 2) setting variables with a shift expression nor 3) the casts are necessary for producing the unsuitable behavior.

@infrastation? Would the script, with those changes, still catch the problems?  (I have neither a Solaris 9 VM nor a Windows VM with MinGW on which to test it.)

**Comment by guyharris** [comment]
>  Would the script, with those changes, still catch the problems?

At least on Solaris 9/SPARC, the configure script catches the problem (`snprintf(buf, sizeof(buf), "%zu", <unsigned integer equal to 100>);` failed to produce 100).

Shall I submit this as a pull request?

**Comment by infrastation** [comment]
I tried comprehending the nature of this undefined behaviour, but could not get it quickly. If you understand it well and can fix it with a comment that will prevent me from making the same mistake again, that would be a good resolution.
