### ISSUE TITLE
filter on src host does not work

### ISSUE THREAD

**Issue by guyharris** [the-tcpdump-group/libpcap#141]
Converted from [SourceForge issue 3040174](http://sourceforge.net/support/tracker.php?aid=3040174), submitted by esenlik

using: tcpdump 4.1.1 and libpcap 1.1.1

I tried to filter out my capture file trough tcpdump to display only the tcp connections between 1.1.1.1 to 2.2.2.2 (ips are just ie) by using the filter commands below:
tcpdump -r file.pcap src host 1.1.1.1 or dst host 1.1.1.1 
and also 
host 1.1.1.1

For some reason it only displays 1.1.1.1 host on the destination side (2.2.2.2 -> 1.1.1.1) and does keep the 1.1.1.1 on the source side. (1.1.1.1 -> 2.2.2.2)

I could not find this bug on this but I would appreciate if you culd point me if there is any work around for this bug. thanks

**Comment by infrastation** [comment]
This bug report was made on 2010-08-05 and last updated on 2010-10-04. The problem has not beent reproduced. Closing.
