### ISSUE TITLE
non-blocking libpcap + select = lost packets

### ISSUE THREAD

**Issue by guyharris** [the-tcpdump-group/libpcap#169]
Converted from [SourceForge issue 3548076](http://sourceforge.net/support/tracker.php?aid=3548076), submitted by None

It seems that libpcap is losing response packets when the come back to fast (when using a non-blocking pcap handler with select). For more details, please check http://stackoverflow.com/questions/11637063/asynchronous-libpcap-losing-packets.

**Comment by infrastation** [comment]
libpcap 1.5.0 had introduced support for TPACKET_V3 in 2013. So long as the original questions have been answered and the issue does not have a reporter anymore and it does not describe a problem that can be worked on I am closing it.
