### ISSUE TITLE
configure does not check for netlink/genl/genl.h

### ISSUE THREAD

**Issue by guyharris** [the-tcpdump-group/libpcap#172]
Converted from [SourceForge issue 3565777](http://sourceforge.net/support/tracker.php?aid=3565777), submitted by roflz

./pcap-linux.c:267:31: fatal error: netlink/genl/genl.h: No such file or directory

configure should check for its existence, and if it is needed, abort there

**Comment by rofl0r** [comment]
nice. may i ask which release flavor you used for testing - img file for qemu or just the precompiled rootfs extracted and used via chroot, bwrap, or other sandboxing tool ?
