### ISSUE TITLE
pcap_loop stops capturing

### ISSUE THREAD

**Issue by guyharris** [the-tcpdump-group/libpcap#177]
Converted from [SourceForge issue 3569206](http://sourceforge.net/support/tracker.php?aid=3569206), submitted by None

After running for several days, capturing packets, pcap_loop hangs in the poll() call. 

This is running on Debian Squeeze kernel 2.6.32-5-amd64 and 3.2.0-0.bpo.3-amd64 
#0  0x00007ffff6d5c998 in poll () from /lib/libc.so.6
#1  0x00007ffff7f3acd7 in ?? () from /usr/lib/x86_64-linux-gnu/libpcap.so.0.8
#2  0x00007ffff7f41f01 in pcap_loop () from /usr/lib/x86_64-linux-gnu/libpcap.so.0.8
#3  0x0000000000417332 in main (argc=<value optimized out>, argv=<value optimized out>) at main.cpp:113

Version 1.3.0 of libpcap.

Restarting the program makes it run normally again. 

the program is basically:
while(1){
        int r = pcap_loop(descr, 0, got_packet, (u_char*)&info);
}

and got packet does it's stuff with the packet and returns. This is very low traffic interface, so no CPU or memory problems

**Comment by herlenashavi** [comment]
Hi,
I run into the same issue with version 1.8.0. 
@guyharris : Did you manage to resolve this?

Thanks,
Avinash

**Comment by infrastation** [comment]
The original bug report was made on 2012-09-19. @herlenashavi, does this issue reproduce on the current master branch?

**Comment by infrastation** [comment]
Closing due to lack of feedback.
