### ISSUE TITLE
Use tcpdump to write file will stop

### ISSUE THREAD

**Issue by guyharris** [the-tcpdump-group/libpcap#189]
Converted from [SourceForge issue 3607864](http://sourceforge.net/support/tracker.php?aid=3607864), submitted by yungyung919

I use tcpdump-3.9.1   libpcap-1.1.1
When I start to capture packet, I use tcpdump -i eth0 -w /pkt.cap -W 1 -C 50 -s 0
packet flow is very fast, about 10mb/s
the file will be stopped to increase randomly.
but I use libpcap-0.9.8, it will be normal, but it does not support vlan tag
so I want to use libpcap-1.1.1 by fixing file is not increased problem
is there anyone have this issue?

**Comment by infrastation** [comment]
The original bug report was made on 2013-03-13, it concerns a libpcap version released in 2010 and a tcpdump version released in 2004 or 2005. So 8 and a half years ago it was already not actionable. Closing.
