### ISSUE TITLE
[Feature] Allow to install only static on only dynamic libraries

### ISSUE THREAD

**Issue by guyharris** [the-tcpdump-group/libpcap#281]
Converted from [SourceForge issue 2986373](http://sourceforge.net/support/tracker.php?aid=2986373), submitted by alonbl

Currently the installation forces both .a and .so (AIX dynamic .a only)
However there is a need to use only static libraries in many configurations.
Can you please add support for --enable-static/--disable-static --enable-dyanmic/--disable-dynamic in the configure.ac?

**Comment by infrastation** [comment]
The original request dates back to 2010-04-13, there were no meaningful follow-ups. That said, building and installing both shared and static library does not prevent the user from choosing which one to link with:

```text
$ ./pcap-config --libs
-L/tmp/tcpdump_build_matrix.B68HfbAk/lib -Wl,-rpath,/tmp/tcpdump_build_matrix.B68HfbAk/lib -lpcap
$ ./pcap-config --libs --static
-L/tmp/tcpdump_build_matrix.B68HfbAk/lib -lpcap -lnl-genl-3 -lnl-3  -ldbus-1
```

Hence it is fine to close this issue.
