### ISSUE TITLE
[Feature] Deactivate capture

### ISSUE THREAD

**Issue by guyharris** [the-tcpdump-group/libpcap#288]
Converted from [SourceForge issue 3602077](http://sourceforge.net/support/tracker.php?aid=3602077), submitted by wandrewx

Sometimes it is necessary to capture handle always exist, but don't receive any traffic. Like severals capture sessions. I don't find any API to do that.
For example:
- set receive buffer to 0 not possible for active capture
- set direction to not IN and not OUT
- pcap_deactivate(pcap_t *)

Please add this feature. Thanks.

**Comment by infrastation** [comment]
(This commend is mainly for historic consistence.) As far as I understand, after the pcap_t handle has been set up and activated, `pcap_loop()` can be used to start receiving packets and `pcap_breakloop()` can be used to stop receiving packets. This can be repeated as many times as necessary.

Closing.

**Comment by guyharris** [comment]
And if, for some mysterious reason, somebody wants a `pcap_t` that never ever ever provides packets, they can use `pcap_setfilter()` on that `pcap_t` to set the filter to a BPF filter program that just does `RET 0` (rejecting all packets).

**Comment by infrastation** [comment]
The comments in the original SF issue (somehow not automatically copied into here during the migration) explain that the original requester was considering to have buttons in the GUI to switch the software between active and idle modes without restarting the software (as in Wireshark).

**Comment by guyharris** [comment]
For those curious, the first comment was:

Pete - 2013-05-14
Need more details, please. What problem are you trying to solve? Can you give some pseudo code for how you envision this ability used? Would you want the ability to also reactivate capture?

and the second comment, a reply by the person who asked the question, was:

Wandrew - 2013-05-15
I write capture object NetCap for several network cards. For generic cards i use libpcap, but specific cards (like Endace DAG) use own API. Upper layer use capture sessions, but my object musn't be destroyed. It provide link status for opened device. Link status is monitoring parameter for application internal self check logic.
This is just example:

    static void selfCheck(void *arg)
    {
        NetCap *nc = arg;
        Flags f= nc.flags();
        if (f & IFF_UP)
        {
            led.set(LINK_UP);
        }
        else
        {
            led.unset(LINK_UP);
        }
    }
    main()
    {
        list = NetCap::enumerateDevices();
        NetCap nc(list.first());
        if (!nc.isValid())
        {
            return;
        }
        /* Create thread for SelfCheck */
        hThread = CreateThread(selfCheck, &nc);
        /* Application GUI started here */
        /* User press "Start capture button" */
        nc.open(); ///< Here i need to activate data receive
        // Process traffic
        /* User press "Stop button" */
        nc.close(); ///< Stop. I don't wan't any data
        /* Here i don't want any data, only link status. NetCap instance must exist */
        /* User press "Start capture button" again */
        nc.open(); ///< For now, if pcap capture handle was not deleted above, so i receive traffic not belong to my capture session
        // Process traffic
        nc.close();
        }
        nc constructor need to contain [pcap_open_live() and pcap_deactivate_capture()] or pcap_open_live(CREATE_DEACTIVATED);
        nc.open() = pcap_activate_capture();
        nc.close() = pcap_deactivate_capture();

**Comment by guyharris** [comment]
And, so, if you *really* want to deactivate captures on a `pcap_t`, just set a "reject all packets" filter and, to re-activate it, put back the original filter (or, if there is no filter, set an "accept all packets" filter).

However, there is no "provide link status" API for libpcap, so I don't see why it's necessary to keep the `pcap_t` open.

**Comment by dimich-dmb** [comment]
@guyharris 
`pcap_deactivate()` would be useful when we want to stop capturing at some point but not to lose packets already received by interface and aren't yet read-out from buffer.
`pcap_deactivate()` will cause descriptor obtained by `pcap_get_selectable_fd()` to HUP, the same as interface down do. So application can continue to read already received packets until buffer is empty and `pcap_next_ex()` return 0.
Without `pcap_deactivate()` i don't see other ways to stop capturing at some time point other than comparing packet's `pcap_pkthdr->ts` to time when stop is requested. But this way is sensitive to system time discontinious jumps.

**Comment by guyharris** [comment]
>` pcap_deactivate()` will cause descriptor obtained by `pcap_get_selectable_fd()` to HUP

Presumably "will cause the descriptor obtained by `pcap_get_selectable_fd()` to HUP" means "will cause a `poll()` on that descriptor to report `POLLHUP`, will cause a `select()` to report an exceptional condition, and will cause a `kevent()` to indicate an exceptional condition".

If so, then it will do so only if there's a way to mark an arbitrary descriptor to do so.

> So application can continue to read already received packets until buffer is empty and `pcap_next_ex()` return 0.

So is the reason why setting a "reject all packets" filter not suffice that setting the filter flushes unread packets?

If so, presumably if there was a "set a filter but don't flush unread packets" call, setting a "reject all packets" filter with that call would suffice.

**Comment by dimich-dmb** [comment]
> If so, presumably if there was a "set a filter but don't flush unread packets" call, setting a "reject all packets" filter with that call would suffice.

@guyharris Exactly. "reject all packets" filter would suffice if not for this (from `pcap-linux.c` `set_kernel_filter()`):
> We therefore discard all packets queued up on the socket when setting a kernel filter.

**Comment by infrastation** [comment]
How far `pcap_breakloop()` is from the desired solution space?

**Comment by dimich-dmb** [comment]
> How far `pcap_breakloop()` is from the desired solution space?

It's not applicable for non-blocking model with `pcap_next_ex()`.

**Comment by guyharris** [comment]
> Well, unread packets discard on pcap_setfilter() can be worked around with...

On Linux.

On FreeBSD, macOS, and NetBSD (but not DragonFly BSD, OpenBSD, AIX, and Solaris 11), at least with newer versions it can be worked around by directly doing a `BIOCSETFNR` ioctl to set the filter.

Bugs should probably be filed against DragonFly BSD and OpenBSD to add `BIOCSETFNR` - it should be a trivial change (modify the routine that sets the filter to take a "should I flush the buffer?" argument and, if that argument indicates "no", don't call the "flush the buffer" routine).  I'm not sure what buttons to push to get IBM and Oracle to add it.

On Windows, a bug should be filed against Npcap to add `BIOCSETFNR` - again, trivial, just don't call `NPF_ResetBufferContents()`.

**Comment by guyharris** [comment]
> On FreeBSD, macOS, and NetBSD

Nope, not NetBSD.
