### ISSUE TITLE
libpcap.so fails with dflag symbol not found

### ISSUE THREAD

**Issue by rometoroam** [the-tcpdump-group/libpcap#323]
1) git clone working branch/ previous branch
2) ./configure --enable-yydebug --enable-optimizer-dbg
3) make all -> genreates libpcap.so.1XXXX
4) tcpdump -d -p -n -s 0 -i eth0 host 192.168.20.0
tcpdump: symbol lookup error: /usr/lib64/libpcap.so.1: undefined symbol: dflag

note: dflag should not be part of the shared object compile in the first place..

**Comment by infrastation** [comment]
@guyharris has fixed this bug with libpcap commit 131f5a8b (available since libpcap 1.8.1) and tcpdump commit the-tcpdump-group/tcpdump@817aadf, thank you for the report!
