### ISSUE TITLE
current libcap does not compile when bluez5 is present

### ISSUE THREAD

**Issue by jmayer** [the-tcpdump-group/libpcap#343]
The bluetooth code was written for bluez4. It checks for the presence of bluez and just assumes it being bleuz4. As the API changed with bluez5 the code no longer compiles when the bluez5 development package is installed.

**Comment by fxlb** [comment]
The immediate cause is fixed  by #425 (b3776f3d50df9de9fcf702bd21a3ecb2539ffef4). Closing.
