### ISSUE TITLE
fails to compile w/Bluetooth

### ISSUE THREAD

**Issue by infrastation** [the-tcpdump-group/libpcap#345]
libpcap fails to compile on an i686 host running Fedora Linux 20 (with both GCC and Clang):

```
$ rpmquery bluez-libs-devel clang gcc
bluez-libs-devel-5.16-1.fc20.i686
clang-3.3-4.fc20.i686
gcc-4.8.2-7.fc20.i686
$ CC=/usr/bin/clang ./configure
[...]
checking bluetooth/bluetooth.h usability... yes
checking bluetooth/bluetooth.h presence... yes
checking for bluetooth/bluetooth.h... yes
configure: Bluetooth sniffing is supported
checking if struct sockaddr_hci has hci_channel member... yes
checking if HCI_CHANNEL_MONITOR is defined... yes
[...]
$ make
[...]
./pcap-bt-monitor-linux.c:42:10: fatal error: 'bluetooth/mgmt.h' file not found
#include <bluetooth/mgmt.h>
         ^
1 error generated.
```

@MichalLabedzki, could you review?

**Comment by radix-platform** [comment]
**I think the following patch will be usefull to be able build libpcap:**

diff -b --unified -Nr bluez-5.42-orig/Makefile.am bluez-5.42/Makefile.am
--- bluez-5.42-orig/Makefile.am	2016-09-26 15:29:00.000000000 +0300
+++ bluez-5.42/Makefile.am	2016-10-23 20:23:30.538995315 +0300
@@ -75,7 +75,7 @@
 BUILT_SOURCES = $(local_headers) src/builtin.h
 
 if LIBRARY
-include_HEADERS += $(lib_headers)
+include_HEADERS += $(lib_headers) $(extra_headers)
 
 lib_LTLIBRARIES += lib/libbluetooth.la
 
diff -b --unified -Nr bluez-5.42-orig/Makefile.in bluez-5.42/Makefile.in
--- bluez-5.42-orig/Makefile.in	2016-09-26 15:29:40.000000000 +0300
+++ bluez-5.42/Makefile.in	2016-10-23 20:23:30.538995315 +0300
@@ -88,7 +88,7 @@
 noinst_PROGRAMS = $(am__EXEEXT_5) $(am__EXEEXT_6) $(am__EXEEXT_7) \
 	$(am__EXEEXT_8) $(am__EXEEXT_11)
 libexec_PROGRAMS = src/bluetoothd$(EXEEXT) obexd/src/obexd$(EXEEXT)
-@LIBRARY_TRUE@am__append_1 = $(lib_headers)
+@LIBRARY_TRUE@am__append_1 = $(lib_headers) $(extra_headers)
 @LIBRARY_TRUE@am__append_2 = lib/libbluetooth.la
 DIST_COMMON = $(srcdir)/Makefile.plugins $(srcdir)/Makefile.tools \
 	$(srcdir)/Makefile.obexd $(srcdir)/android/Makefile.am \

**Comment by guyharris** [comment]
Duplicate of #343
