### ISSUE TITLE
With a timeout of 0, pcap_next_ex()/pcap_dispatch() can return 0

### ISSUE THREAD

**Issue by msekletar** [the-tcpdump-group/libpcap#350]
I'd like to know if this is expected? See simple reproducer here [1]. Either way, this is change in behaviour compared to version of libpcap using TPACKET_V2.

When running reproducer like "./repro icmp" strange is that epoll_wait() returns EPOLLIN right away even tough we capture from "lo" and there is nothing sending icmp packets. If I understand kernel code correctly, when there are no packets then there shouldn't be any block in the ring dispatched to userspace thus epoll_wait() should _not_ return EPOLLIN.

If you run reproducer and then launch ping on separate terminal you will see output indicating that _sometimes_ pcap_next_ex() returns normally other time it returns 0 indicating timeout.

[1] https://gist.github.com/msekletar/10465629

**Comment by infrastation** [comment]
For posterity, there is now a [FAQ entry](https://www.tcpdump.org/faq.html#q15) about this.
