### ISSUE TITLE
poll() plus pcap_dispatch() does not work in versions 1.5.x

### ISSUE THREAD

**Issue by LStranger** [the-tcpdump-group/libpcap#364]
I test a simple application:

    int main()
    {
        char dev[]="br0";
        char errbuf[PCAP_ERRBUF_SIZE];
        pcap_t* descr;
        struct bpf_program fp;        /* hold compiled program */
        bpf_u_int32 maskp,netp;     /* subnet mask */
        struct pollfd pfd;
        pcap_lookupnet(dev, &netp, &maskp, errbuf);
        descr = pcap_open_live(dev, BUFSIZ, 1,-1, errbuf);
        pcap_compile(descr, &fp, "udp and dst port 67", 0, netp);
        pcap_setfilter(descr, &fp);
        pcap_loop(descr, -1, callback_function, NULL);
        return 0;
    }

It works fine, passes every packet to callback_function().
Then I replace pcap_loop(...) line with:

    pfd.fd = pcap_get_selectable_fd(descr);
    while(1) {
        pfd.events = POLLIN;
        pfd.revents = 0;
        if (poll(&pfd, 1, -1) < 1) break;
        int ec = pcap_dispatch(descr, -1, callback_function, NULL);
        printf("pcap_dispatch() result: %d\n", ec);
    }

and it reports

pcap_dispatch() result: 0

on every packet, and callback_function() is never called anymore.

**Comment by guyharris** [comment]
Linux kernel bug, about which there's not much we can do.  If you're not using non-blocking mode and `select()`/`poll()`/`epoll()`, we work around it, as best we can, with a short `select()` timeout inside libpcap.  If you *are* using non-blocking mode and `select()`/`poll()`/`epoll()`, *you* have to work around it by making sure you have a short timeout in the `select()`/`poll()`/`epoll()`, at least on kernels with the bug, and, if the timer expires, call `pcap_dispatch()`.  (With a high packet arrival rate, when blocking mode is used, TPACKET_V3 drops fewer packets than TPACKET_V2, so "don't use TPACKET_V3 on pre-3.19 kernels" isn't the right answer.)
