### ISSUE TITLE
dumpcap: SIOCSIWMODE failed: Operation not permitted

### ISSUE THREAD

**Issue by johngood80** [the-tcpdump-group/libpcap#367]
I am using Fedora 20 (uname: Linux localhost 3.11.10-301.fc20.x86_64). When I try to capture in monitor mode from wlo1 interface, using Wireshark 1.10.7, after capturing a random amount of packets, the capture stops by itself and  I get the following error:

(wireshark:2020): Gtk-WARNING **: Failed to set text from markup due to error parsing markup: Error on line 3 char 6: Invalid UTF-8 encoded text in name - not valid 'Unknown message from dumpcap, try to show it as a string: Can't restore interface wlo1 wireless mode (SIOCSIWMODE failed: Operation not permitted).
Please adjust manually.
\xa7{\xe6\u007f'

Apparently this is a libpcap issue. Any suggestions?

**Comment by jesipr** [comment]
Having this same problem. I'm running Ubuntu 14.04. Wireshark 1.10.6.

**Comment by infrastation** [comment]
Could you post the exact steps to reproduce this?

**Comment by infrastation** [comment]
Closing due to lack of feedback.

**Comment by f380cedric** [comment]
I have the same issue on Fedora 29.
``` 
$ sudo dumpcap -I -i wlp3s0 
Capturing on 'wlp3s0'
File: /var/tmp/wireshark_wlp3s0_20190315174028_xuB0yY.pcapng
Packets captured: 844
Packets received/dropped on interface 'wlp3s0': 844/0 (pcap:0/dumpcap:0/flushed:0/ps_ifdrop:5) (100.0%)
Can't restore interface wlp3s0 wireless mode (SIOCSIWMODE failed: Operation not permitted).
Please adjust manually.
```
