### ISSUE TITLE
TPACKET_V3 problem 

### ISSUE THREAD

**Issue by klaus3000** [the-tcpdump-group/libpcap#380]
Hi! I use dnscap on Linux to capture DNS traffic. What dnscap does is basically:

pcap = pcap_open_live(name, SNAPLEN, promisc, 1, errbuf);
fdes = pcap_get_selectable_fd(pcap);
pcap_setnonblock(pcap, TRUE, errbuf)
// compile and load filter
select(pcap_maxfd+1, &readfds, NULL, NULL, NULL);
n = pcap_dispatch(pcap, -1, dl_pkt, (u_char *)mypcap);

Then I ping the host and start dnscap to capture the pings:

On Ubuntu 10.04 (libpcap 1.0.0 and kernel 2.6.32) everythings works as expected, packets are captured.

On Ubuntu 14.04 (libpcap 1.5.3 and kernel 3.13.0-34) I do not get any packets captured. Select() returns 1, but the following pcap_dispatch() returns 0. I observed the follwing things:
- when doing flood-ping I get packets captured, but not when pinging once a second
- playing around with the pcap_open_live() timeout parameter (e.g. setting to 1000) sometimes gives me packets (not the first one, but later packets)
- removing the select() and periodically calling pcap_dispatch() gives me all packets: pcap_dispatch() returns 1 after every ICMP packet.
- force init_tpacket(handle, TPACKET_V2, "TPACKET_V2"); in pcap-linux.c also gives me all packets

So, I suspect there is a problem with TPACKET_V3 and select() usage before pcap_dispatch(). Maybe dnscap does wrong and the bug is only triggered when using TPACKET_V3, or dnscap is fine and there is a bug somewhere else.

Thanks
Klaus

**Comment by guyharris** [comment]
And that's now in the 3.19 kernel.

**Comment by guyharris** [comment]
Linux kernel bug, about which there's not much we can do.  If you're not using non-blocking mode and `select()`/`poll()`/`epoll()`, we work around it, as best we can, with a short `select()` timeout inside libpcap.  If you *are* using non-blocking mode and `select()`/`poll()`/`epoll()`, *you* have to work around it by making sure you have a short timeout, at least on kernels with the bug.
