### ISSUE TITLE
pcap_next() doesn't return immediately with a snaplen of 1 and to_ms set on pcap_open_live()

### ISSUE THREAD

**Issue by Sworddragon** [the-tcpdump-group/libpcap#382]
I'm using Linux 3.16.3 (x86_64) with libpcap 1.6.2 and if the snaplen on pcap_open_live() is set to 1 while to_ms is given a call to pcap_next() does not immediately return if a packet is seen. The documentation says that to_ms on pcap_open_live() works on some platforms like a buffer which seems to be the case here. But the problem is that the buffer is waiting here for more data then given in snaplen. Here is a testcase:

```
#include <pcap.h>

int main()
{
    char error[PCAP_ERRBUF_SIZE];
    pcap_t *capture;
    struct pcap_pkthdr header;

    if((capture = pcap_open_live("eth0", 1, 1, 5000, error)) == NULL)
    {
        printf("%s\n", error);
        return 1;
    }
    for(;;)
    {
        pcap_next(capture, &header);
        printf("Packet captured\n");
    }
    pcap_close(capture);
    return 0;
}
```

Cmpiling and executing this application while pinging permanently a server (for example with "ping 8.8.8.8") does not immediately show if a packet was captured.

**Comment by infrastation** [comment]
For posterity, there is now a [FAQ entry](https://www.tcpdump.org/faq.html#q15) about this.
