### ISSUE TITLE
Recently added VLAN filtering is only filtering on ethertype 0x9100

### ISSUE THREAD

**Issue by morphyno** [the-tcpdump-group/libpcap#397]
This is in regard to the recently closed https://github.com/the-tcpdump-group/libpcap/pull/391 committed by @msekletar

VLAN filtering is only working for 0x9100 and not 0x8100 or 0x88a8 ethertype, below are some testing i did using Scapy via loop back interface

from scapy prompt
sendp(Ether(src="aa:bb:cc:dd:ee:ff",dst="11:22:33:44:55")/Dot1Q(vlan=100)/IP(src="12.1.1.1",dst="23.2.2.1")/TCP(sport=23,dport=233),iface='lo',count=1)

sudo tcpdump -s 0 -nei lo vlan 100
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on lo, link-type EN10MB (Ethernet), capture size 262144 bytes

When i set the ethertype to 0x9100, it runs fine

from scapy prompt
sendp(Ether(src="aa:bb:cc:dd:ee:ff",dst="11:22:33:44:55")/Dot1Q(vlan=100,tpid=0x9100)/IP(src="12.1.1.1",dst="23.2.2.1")/TCP(sport=23,dport=233),iface='lo',count=1)

on tcpdump
sudo tcpdump -s 0 -nei lo vlan 100
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on lo, link-type EN10MB (Ethernet), capture size 262144 bytes
16:56:25.932998 aa:bb:cc:dd:ee:ff > 11:22:33:44:55:66, ethertype 802.1Q-9100 (0x9100), length 58: vlan 100, p 0, ethertype IPv4, 12.1.1.1.23 > 23.2.2.1.233: Flags [S], seq 0, win 8192, length 0

**Comment by morphyno** [comment]
Debug output

sudo tcpdump -d -s 0 -nei lo vlan 100
[sudo] password for morgany: 
(000) ldh      [12]
(001) jeq      #0x8100          jt 3	jf 2
(002) jeq      #0x9100          jt 3	jf 7
(003) ldh      [14]
(004) and      #0xfff
(005) jeq      #0x64            jt 6	jf 7
(006) ret      #262144
(007) ret      #0

**Comment by msekletar** [comment]
Generated BPF filter code doesn't actually use extensions, notice (000) ldh 12 and (003) ldh 14, these are loads from absolute offsets in L2 datagram, however kernel already stripped vlan headers once these intructions get executed. Thus no vlan packets pass the filter (if tpid is 0x8100). Presumably Ubuntu's kernel doesn't do that if tpid is 0x9100. This is clearly their kernel bug. I think we can close this issue.

**Comment by morphyno** [comment]
@msekletar, you are right, there is an issue with ubuntu's kernel handling tpid 0x9100. However, there is still an issue with RH7 on vlan filtering only working for 0x8100. For many existing QinQ and multiple VLAN environments, we encounter 0x9100, 0x9200, and 0x88a8 as the outter most VLAN type. Should a RH7 kernel be filed as well?

**Comment by msekletar** [comment]
I suppose there is a kernel bug in RHEL/CentOS 7 kernel as well. Maybe @borkmann can shed some light on this. Daniel any idea why no vlan packets are getting through when outer most tpid is not 0x8100?

**Comment by morphyno** [comment]
@guyharris ,can you explain the reference to this issue?

**Comment by guyharris** [comment]
That's tcpdump#397, not libpcap#397.
