### ISSUE TITLE
Large/fragmented packet Irix bug

### ISSUE THREAD

**Issue by guyharris** [the-tcpdump-group/libpcap#4]
Converted from [SourceForge issue 586764](http://sourceforge.net/support/tracker.php?aid=586764), submitted by nbarclay

When trying to use libpcap to capture large (24,000 
byte) UDP packets split into fragments, I got a mismatch 
between caplen and len on the fragments.  This was 
using an SGI Irix 6.5 system which uses pcap-snoop.c.  
Specifically, the len field came back as 1514 bytes, while 
caplen was only 1500 bytes.

Digging into the pcap-snoop.c code, the problem 
appears to result from how some of the size check code 
fits together in pcap_open_live.  At present, the routine's 
logic is:

1) Check whether snaplen is greater than the MTU and, 
if so, reduce it to the MTU.
2) Set snooplen to snaplen minus the link-layer header 
length.
3) Pass snooplen to the SIOCSNOOPLEN ioctl.

Thus, the snooplen passed to the ioctl ends up being 
several bytes smaller than the MTU rather than being 
equal to the MTU.  If I understand the implications of 
caplen &lt; len correctly, this results in some data loss with 
maximum-size fragments, and I'm guessing it would 
cause similar problems with maximum-size non-
fragmented packets.

At first appearance, it looks like the problem can be 
solved by moving the line &quot;snoop_len = snap_len - 
ll_hdrlen&quot; up above the check against ifr.ifr_mtu and 
changing the ifr.ifr_mtu check to check snoop_len 
instead of snap_len.  But that means snap_len itself 
doesn't get checked against the MTU, and I don't know 
the code enough to be sure whether it ought to be 
checked against the MTU for some other reason.  I 
should also note that I'm working with an Ethernet 
interface and can't say for sure how similar problems 
would affect other interfaces.

**Comment by infrastation** [comment]
Closing as Irix was discontinued a long time ago.

**Comment by guyharris** [comment]
At present (as in "tip of the master branch"), the routine's logic is:

1. If SIOCGIFMTU is defined, get the MTU and, if the snapshot length is greater than the MTU *plus the link-layer header size*, reduce the snapshot length to the MTU *plus the link-layer header size*.

1. Set snooplen to snaplen minus the link-layer header length.

1. Pass snooplen to the SIOCSNOOPLEN ioctl.

Thus, the snooplen passed to the ioctl ends up being equal to the MTU.

Commit 1f419aeb14d7788ac46cec61c492530cb87e0ef0 changed "the MTU" to "the MTU plus the link-layer header size"; it was checked in on 2002-07-30.  The SourceForge bug is no longer available, so I don't know whether it was filed against a version with, or without, that change.  I'll assume, based on the text in the bug, that it was filed against a version without that change, and that the change in question fixed it.

**Comment by infrastation** [comment]
The links for those converted issues are now broken because SourceForge at some point had dropped the HTTP redirection they had in place for the old "artifact IDs", which the SF->GH switch used to generate the links on GH as SF started to replace those ID only well after the bug tracker switch.

However, in the two mapping tables ([one](http://seclists.org/tcpdump/2013/q4/31) for tcpdump and [another](http://seclists.org/tcpdump/2013/q4/48) for libpcap) it is recorded that the current GH issue was converted from what is now [SF libpcap bug 4](https://sourceforge.net/p/libpcap/bugs/4/). Now it becomes clear that the SF bug was not properly converted and follow-up comments were lost (copied for historic reference below), which tell this change was indeed made before libpcap 0.7.2.

I will update the bug markup as appropriate.

---
```
 Guy Harris - 2002-07-27

Logged In: YES
user_id=541179

The IRIX 6.5 SNOOP(7P) man page says:

The SIOCSNOOPLEN command takes the address of an integer
telling how many bytes of packet data to capture (the
link-layer header is always captured).

If I remember correctly, we found that setting the snapshot
length to a value equal to the maximum packet size,
including the link-layer header size - 1514 for Ethernet,
for example - got an error from the SIOCSNOOPLEN ioctl.

Given what the man page says, and the behavior we observed,
we inferred that the argument to SIOCSNOOPLEN should be the
maximum amount of link-layer payload to capture and copy to
userland, not the maximum amount of packet data to capture
and copy to userland, i.e. it should be the maximum amount
of packet data minus the link-layer header length.

Does SIOCGIFMTU return the maximum amount of link-layer
payload for an interface, or the maximum packet size
including the link-layer header? E.g., for Ethernet, does
it return 1500, or 1514?

If it returns the maximum amount of link-layer payload, e.g.
1500 on Ethernet, then we should probably compare &quot;snaplen&quot;
with &quot;ifr.ifr_mtu + ll_hdrlen&quot; and, if it's greater than
that value, set it to &quot;ifr.ifr_mtu + ll_hdrlen&quot;, as the
&quot;snaplen&quot; argument to &quot;pcap_open_live()&quot; is supposed to be
the maximum amount of packet data, *including the link-layer
header*, to capture, not the maximum amount of link-layer
payload to capture.
```
---
```
 Nathan A. Barclay - 2002-07-30

Logged In: YES
user_id=584513

I added a printf statement and verified that ifr.ifr_mtu is
coming back 1500 rather than 1514, which is exactly what it
looked like had to be happening. I tried the idea of changing

if (snaplen &gt; ifr.ifr_mtu)
snaplen = ifr.ifr_mtu;

to

if (snaplen &gt; ifr.ifr_mtu + ll_hdrlen)
snaplen = ifr.ifr_mtu + ll_hdrlen;

and that solved the problem for the case where I previously
wasn't getting the whole packets. I'm attaching a modified
pcap-snoop.c with that change.

Nathan
```
---
```
 Nathan A. Barclay - 2002-07-30

Modified pcap-snoop that adds ll_hdrlen when checking/correcting snaplen
 
pcap-snoop.c
```
---
```
 Guy Harris - 2002-07-30

    status: open --> closed-fixed
```
---
```
 Guy Harris - 2002-07-30

Logged In: YES
user_id=541179

I've checked in that change, so the next release will have
that fix.
```
