### ISSUE TITLE
Sending packets on a live device and capture them with the same device - Linux

### ISSUE THREAD

**Issue by seladb** [the-tcpdump-group/libpcap#400]
Hi,
I'm trying to test some code I wrote. For this test I do the following:
1. Get PCAP descriptor using pcap_open_live (promisc mode)
2. Open a new thread and run pcap_dispatch in an endless loop
3. On the main thread I'm using the same descriptor and send packets from a PCAP file using pcap_sendpacket

When I run this on Windows using WinPcap I manage to capture the packets I sent.
When running the same code on Linux (using libpcap) I can't see any of these packets.
I tried to run this on Ubuntu 12.04 and Fedora 15, libpcap-devel-1.1.1-3.fc15.x86_64

Thanks

**Comment by jsommers** [comment]
@seladb Did you ever get any answer about this issue?  The behavior you describe is exactly what happens on other platforms I've written libpcap code for (i.e, macOS and FreeBSD), but I've observed the same issue on Linux as what you describe.

**Comment by jsommers** [comment]
BTW, using a straight PF_PACKET (raw) socket on Linux, I observe the same behavior.  I had thought the problem described in your original post is a limitation of the raw packet socket on Linux, and that does seem to be true.  It's not a limitation of libpcap, per se.  Still, annoying.

**Comment by seladb** [comment]
@jsommers thanks for your answer, I didn't realize it's a limitation of Linux... So why is it happening also on macOS and FreeBSD?

**Comment by jsommers** [comment]
@seladb macOS, FreeBSD and other BSD systems don't use the same PF_PACKET socket mechanism (it is (or may be) unique to Linux).  Instead, they use /dev/bpf, which clearly has different behavior.  

In any case, I think this issue can be closed.

**Comment by seladb** [comment]
I didn't quite understand. You say it happens only on Linux? I thought you said you saw the exact same limitation in macOS and FreeBSD

**Comment by jsommers** [comment]
@seladb Sorry if I was not clear earlier.  This behavior (not receiving a packet injected/sent on the same libpcap handle) is --- as far as I understand --- only on Linux.  I haven't observed it on different OSes (i.e., macOS, FreeBSD, and other BSD variants).

**Comment by seladb** [comment]
Oh, ok, thanks

**Comment by mcr** [comment]
Linux has different behaviour for -i any than for other interfaces, and other OSes do not have -i any. What interfaces are you binding/capturing on, and what is your test traffic that you see/miss?  As these issues are rather old, I'm gonna close the issue, but please re-open if you like.
