### ISSUE TITLE
New DLT value Request - Wattstopper DLM

### ISSUE THREAD

**Issue by skarg** [the-tcpdump-group/libpcap#401]
For a few years I have been using DLT_USER0 147 (user defined) for capturing and saving a serial protocol used by Wattstopper Digital Lighting Management products (see wattstopper.com website) and dissecting via Wireshark and Lua.  I'm planning on adding this pcap file logging to a product, and would like to have a DLT defined for this usage.  Can I ask here on Github for a new DLT, or must I use tcpdump-workers@lists.tcpdump.org to request a new DLT?

**Comment by guyharris** [comment]
As per Michael's mail, use tcpdump-workers@lists.tcpdump.org.

Have you yet seen the tcpdump-workers messages yet? In one, I asked whether there's a specification for the protocol and for the packets - we want that so we can specify it on the link-layer header types page at http://www.tcpdump.org/linktypes.html.

**Comment by skarg** [comment]
Sorry, I haven't seen any messages since I'm not subscribed to tcpdump-workers@lists.tcpdump.org yet.  Today I filled in web request form and confirmed subscription. Thank you for posting here - not sure how I'll reply to a message I haven't received - maybe you can re-post, or I can resend my initial request.

**Comment by infrastation** [comment]
This allocation had been done through pull request #403. Closing.
