### ISSUE TITLE
First packet missing from tcpdump output (TPACKET_V2, cooked mode)

### ISSUE THREAD

**Issue by msekletar** [the-tcpdump-group/libpcap#405]
Hello libpcap hackers,

I recently I got a bug report about first packet missing from tcdpump output (e.g first SYN in tcp flow) when tcpdump is ran as follows, `tcpdump -i any -nn port 30000`. I can't figure out what is wrong so I am trying my luck here.

This doesn't happen when user runs tcpdump on specific interface.

I did bisect git and I was able to track the issue to commit `91758e29467459dc45f25f0e558e3e76afcee66d`. 

Also notice that libpcap is compiled with following patch (i.e. TPACKET_v3 disabled).

```
diff --git a/pcap-linux.c b/pcap-linux.c
index 74de6a3..525001c 100644
--- a/pcap-linux.c
+++ b/pcap-linux.c
@@ -198,9 +198,6 @@ static const char rcsid[] _U_ =
   * uses many ring related structs and macros */
 # ifdef TPACKET_HDRLEN
 #  define HAVE_PACKET_RING
-#  ifdef TPACKET3_HDRLEN
-#   define HAVE_TPACKET3
-#  endif /* TPACKET3_HDRLEN */
 #  ifdef TPACKET2_HDRLEN
 #   define HAVE_TPACKET2
 #  else  /* TPACKET2_HDRLEN */
```

Any help is much appreciated.

Michal

**Comment by msekletar** [comment]
I just found out that that before ```91758e29467459dc45f25f0e558e3e76afcee66d``` condition where bpf_filter is called on packet ```pcap-linux.c:4221``` is never true while after that commit execution goes via true path (```handlep->filter_in_userland``` is true) of `if` statement when the first packets arrives.

**Comment by msekletar** [comment]
Also above comment applies to non-cooked mode capture, however in that case first packet is captured, i.e. passes userland filtering. Seems like our user land BPF filtering doesn't work on packets with cooked header.

**Comment by msekletar** [comment]
If there is more information you need me to gather/provide, please ask.

**Comment by msekletar** [comment]
I think it is obvious that new logic implemented by 91758e29 doesn't work for TPACKET_V2. My temporary workaround was to revert some changes related to TPACKET_V2 from that commit. However before going further with debugging, @guyharris any comments on this?

**Comment by guyharris** [comment]
Presumably the issue is that the count of blocks to filter in userland is wrong - either calculated wrong or decremented at the wrong time - in which case it might not be specific to TPACKET_V{1,2}.

**Comment by osdefsec** [comment]
Hello, 

I encountered this issue, where tcpdump does not show the first packet, while using BPF. 
# tcpdump -h
tcpdump version 4.5.1
libpcap version 1.5.3

# tcpdump -i <if> -nn  -c 5   host <ip>
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on ******, link-type LINUX_SLL (Linux cooked), capture size 65535 bytes

5 packets captured
6 packets received by filter
0 packets dropped by kernel

I was using python-scapy 2.2.0-1, were I encountered this problem. On further checking, the same issue was replicated with tcpdump.

**Comment by guyharris** [comment]
> 5 packets captured

Tcpdump maintains that count, which it increments by 1 every time it receives a packet.

> 6 packets received by filter

On most OSes, the *kernel* maintains that count, and tcpdump merely calls a libpcap routine that retrieves it from the kernel.

When *that* count is incremented depends on the OS.  From "LINUX_SLL", this is presumably Linux, so it's capturing using a PF_PACKET socket.  Packets are counted if they pass the filter and are put into the buffer to be read by userland (i.e., by libpcap in this case).  They might not actually have been *read* by userland, and passed to tcpdump, however; the `-c` limit is imposed by tcpdump, and, when it finishes, there may well be packets in the buffer that were counted by the kernel, and that will show up in the results of `pcap_stats()` and thus in the summary from tcpdump, but will *not* have been read by the program.

To quote the `pcap_stats()` man page:

       The statistics do not  behave  the  same  way  on  all  platforms.
       ps_recv  might  count  packets  whether they passed any filter set
       with pcap_setfilter(3PCAP) or not, or it might count only  packets
       that  pass the filter.  It also might, or might not, count packets
       dropped because there was no room in the operating system's buffer
       when  they arrived.  ps_drop is not available on all platforms; it
       is zero on platforms where it's not available.  If packet  filter-
       ing  is  done  in libpcap, rather than in the operating system, it
       would count packets that don't pass the filter.  Both ps_recv  and
       ps_drop  might,  or might not, count packets not yet read from the
       operating system  and  thus  not  yet  seen  by  the  application.
       ps_ifdrop  might, or might not, be implemented; if it's zero, that
       might mean that no packets were dropped by the  interface,  or  it
       might  mean that the statistic is unavailable, so it should not be
       treated as an indication that the interface did not drop any pack-
       ets.

Or, in other words, don't take anything you get from `pcap_stats()`, except *maybe* `ps_drop`, too seriously.  (No, this is not something that libpcap can easily fix, as the count isn't implemented in libpcap.)
