### ISSUE TITLE
breakage on mips64/octeon

### ISSUE THREAD

**Issue by nortobor** [the-tcpdump-group/libpcap#406]
please see: https://dev.openwrt.org/ticket/17753

the same is happening here too, obn my edge router lite... also tried the latest version (1.6.2)

any idea, what's happening, or how to debug this?

**Comment by guyharris** [comment]
Try building a version from the trunk of the Git repository.

**Comment by nortobor** [comment]
i did, but no success

**Comment by guyharris** [comment]
So what were the error messages from the configure or build?

**Comment by nortobor** [comment]
Sorry, next time i write a proper error report instead of linking to one ^^

Actually, it's segfaulting at runtime, and all i can tell, all my libpcap/tcpdumps builds from openwort worked fine, until i switched to an MIPS64 based edgerouter-lite... all programs that use libcap are segfaulting, btw

strace looks similar to the one in the linked openwrt-ticket above

**Comment by nortobor** [comment]
Core was generated by `tcpdump -i eth1'.
Program terminated with signal 11, Segmentation fault.
#0  0x000000ffefb31eb8 in __prefix_array (dirname=0x127db4030 "", array=0x0, n=1099239037960) at libc/misc/glob/glob.c:187
187           size_t eltlen = strlen (array[i]) + 1;
(gdb) bt
#0  0x000000ffefb31eb8 in __prefix_array (dirname=0x127db4030 "", array=0x0, n=1099239037960) at libc/misc/glob/glob.c:187
#1  0x000000ffefbcbe8c in pcap_compile (p=0x127db4030, program=0xffff929c80, buf=0x0, optimize=<optimized out>, mask=<optimized out>) at ./gencode.c:453
#2  0x0000000120006e98 in main (argc=<optimized out>, argv=<optimized out>) at ./tcpdump.c:1640

**Comment by nortobor** [comment]
seems to be a compiler bug, broken with gcc-4.6 and 4.7, works when compiled with 4.8+
