### ISSUE TITLE
Consider not pushing your work-in-progress branches upstream

### ISSUE THREAD

**Issue by msekletar** [the-tcpdump-group/libpcap#420]
Not that this is a big deal, but in my opinion it would be nice not to have random branches appearing in upstream repository. I'd like to kindly ask upstream maintainers not to push random test/work-in-progress branches to the-tcpdump-group/{libpcap,tcpdump}. Please keep them in your own fork and merge/push them onto master once they are ready. Of course I am not speaking about maintenance branches. Pushing those others branches upstream brings little benefit to community and only clutters repo and makes it more bloated. Moreover brings painful memories of pre-git times :)

Thanks,

Michal

**Comment by mcr** [comment]
I will try to make the automatic script a bit more cleaver, and I'll clean out the silly branches.
