### ISSUE TITLE
the latest libpcap support 802.1Q virtual lan?

### ISSUE THREAD

**Issue by orange-jacky** [the-tcpdump-group/libpcap#426]
hi somebody,
   I am writing a sniffer application by libpcap, when analyse a Ethernet II->802.1Q Virtual Lan->ip->tcp packet, I found that the function of pcap_loop() can't  callback.
  i wanna know that can libpcap support 802.1Q vlan?if not support,how i can make libpcap support 802.1Q vlan?
  thanks to answer my question, anybody.

**Comment by orange-jacky** [comment]
my develop machine is mac yosemite 10.10, my mac can't support?

**Comment by infrastation** [comment]
To learn libpcap API please study http://www.tcpdump.org/manpages/ and other documentation available on the same web-site.

**Comment by guyharris** [comment]
> I found that the function of pcap_loop() can't callback

Presumably you mean that your callback routine isn't getting called.

Are you using a capture filter?  If so, what is the filter string you're using?

**Comment by orange-jacky** [comment]
i set filter "ip or vlan", it can works. thanks anybody.
