### ISSUE TITLE
how many traffics libpcap can handle in realtime?

### ISSUE THREAD

**Issue by orange-jacky** [the-tcpdump-group/libpcap#427]
i have a pc server, it has 16 thread core, 32G memory, 500GB disk, 1000M network card.  i  code a sniffer application with the latest libpcap. i wanna know that how many traffics libpcap can handle in realtime. especically how many  MB/s.  and libpcap can improve its handling capacity?

thanks anyone to answer my question.

**Comment by w-vi** [comment]
I never had an issue that pcap would be the bottleneck ... but it depends on what BPF filters you have set, are you sniffing in promiscuous mode etc so it's hard to tell. Benchmark it yourself, try offline mode from file, disk i/o is often slower than network but at least it will give you a lower bound what your sniffer is capable of.

**Comment by orange-jacky** [comment]
i plan to design my sniffer handling 500-600MB/s traffic of capacity in realtime and 500M-600MB/s offline from file. Have you test your sniffer about offline from file,how big of capacity it need reading and writing disk i/o ?

**Comment by w-vi** [comment]
1Gb card can do theoretically 125 MB/s so achieving 500 MB/s is impossible with such card.

**Comment by w-vi** [comment]
Reading 500MB/s from disk is again very hard to imagine, possible with SSD at least in theory though.

**Comment by infrastation** [comment]
Closing. For the record: the simplest way would be to try and see, as performance depends both on the hardware, the filters in place and kind of traffic.
