### ISSUE TITLE
Optimization breaks matching: len >= 2147483648 & 2147483648 or len < 0 | 2147483648

### ISSUE THREAD

**Issue by kbara** [the-tcpdump-group/libpcap#434]
The filter `len >= 2147483648 & 2147483648 or len < 0 | 2147483648` matches packets if and only if optimization is disabled with -O.

```
% tcpdump -O -ntr ../tests/data/tcp-ack-66-bytes.pcap 'len >= 2147483648 & 2147483648 or len < 0 | 2147483648'
reading from file ../tests/data/tcp-ack-66-bytes.pcap, link-type EN10MB (Ethernet)
IP 149.174.156.93.54192 > 178.79.150.233.80: Flags [.], ack 3209860838, win 31, options [nop,nop,TS val 2756387939 ecr 4173199779], length 0
```

```
% tcpdump  -ntr ../tests/data/tcp-ack-66-bytes.pcap 'len >= 2147483648 & 2147483648 or len < 0 | 2147483648' 
reading from file ../tests/data/tcp-ack-66-bytes.pcap, link-type EN10MB (Ethernet)
(No packet matched)
```

The test packet can be downloaded from https://github.com/Igalia/pflua/raw/master/tests/data/tcp-ack-66-bytes.pcap , but essentially any packet should demonstrate the same problem.

This is a fairly minimal test case; every variant I've tried involving changing the value from 2147483648 (0x80000000) or simplifying either clause makes the discrepancy between the optimized and unoptimized behaviour disappear.

**Comment by kbara** [comment]
This is also triggered by ```len <= 4294967295 & 2147483647 and len > 2147483647 + 0```. Removing the + 0 makes it behave correctly.

**Comment by kbara** [comment]
A few more examples:
```len == 0 | 2147483648 or len < 2147483648 << 0```
```len > 4294967295 | 4294967295 or len < 4294967295 & 4294967295```
```len != 0 + 2147483648 and len >= 2147483648 | 0```
```len < 1585815551 * 2147483648 and len >= 0 | 2147483648```
```len = 0 + 2147483647 or len < 4294967295 - 2147483648```

**Comment by tenarchits** [comment]
Works for me using tcpdump built with #972 applied.

**Comment by guyharris** [comment]
#972 merged.
