### ISSUE TITLE
Missing #if HAVE_TPACKET3 check in pcap-linux.c

### ISSUE THREAD

**Issue by mwmarkland** [the-tcpdump-group/libpcap#441]
While trying to compile libpcap on the following:

Linux login4 2.6.32.59-0.7.1_1.0402.7496-cray_ss_s #1 SMP Wed Feb 26 06:01:23 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

after a plain ./configure I saw the following error:

markland@login4:/scratch/markland/libpcap-master> make
gcc -fpic -I.  -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include   -DHAVE_CONFIG_H  -D_U_="__attribute__((unused))" -g -O2    -c ./pcap-linux.c
./pcap-linux.c: In function ‘set_poll_timeout’:
./pcap-linux.c:1370: error: ‘TPACKET_V3’ undeclared (first use in this function)
./pcap-linux.c:1370: error: (Each undeclared identifier is reported only once
./pcap-linux.c:1370: error: for each function it appears in.)
./pcap-linux.c:1370: error: ‘broken_tpacket_v3’ undeclared (first use in this function)
make: *** [pcap-linux.o] Error 1

It appears that near line 1370 there is a missing #if HAVE_TPACKET3 check that would mirror the functionality of the one on line 1346. 

If I add said check around the use of TPACKET_V3 near line 1385, the library builds as expected.

This is using a downloaded zip file dated 2015/06/08 15:22pm CDT.

Thanks for taking a look.

**Comment by guyharris** [comment]
Thanks for the report.  Fixed in 38ac49e9e9dc464d2f31e22cf05d6af653c2151d.
