### ISSUE TITLE
tcpdump on AIX cannot sniff en0 on virtualized LPAR, can however sniff lo0

### ISSUE THREAD

**Issue by jfree9876543212** [the-tcpdump-group/libpcap#448]
This is a very strange issue.

'tcpdump -V' returns:
tcpdump version aix3.9.8
libpcap version aix0.9.8

'ifconfig -a' returns:
en0: flags=1e080967,480<UP,BROADCAST,DEBUG,NOTRAILERS,RUNNING,PROMISC,SIMPLEX,MULTICAST,GROUPRT,64BIT,CHECKSUM_OFFLOAD(ACTIVE),CHAIN>
        inet xx.xx.xxx.xx netmask 0xffffff00 broadcast xx.xx.x.xxx
         tcp_sendspace 262144 tcp_recvspace 262144 rfc1323 1
lo0: flags=e08084b,c0<UP,BROADCAST,LOOPBACK,RUNNING,SIMPLEX,MULTICAST,GROUPRT,64BIT,LARGESEND,CHAIN>
        inet xxx.x.x.x netmask 0xff000000 broadcast xxx.xxx.xxx.xxx
        inet6 ::1%1/0
         tcp_sendspace 131072 tcp_recvspace 131072 rfc1323 1

'netstat -in' returns:
Name  Mtu   Network     Address           Ipkts Ierrs    Opkts Oerrs  Coll
en0   1500  link#2      5e.35.54.d7.c.2  850411140     0 797017317     0     0
en0   1500  xx.xx.xxx   xx.xx.xx.xxx     850411140     0 797017317     0     0
lo0   16896 link#1                       34380614     0 34380404     0     0
lo0   16896 127         127.0.0.1        34380614     0 34380404     0     0
lo0   16896 ::1%1                        34380614     0 34380404     0     0

'tcpdump -i en0' returns:
0 packets received by filter
0 packets dropped by kernel

The netstat command show packets on en0 for a busy server. However tcpdump cannot sniff packets on en0! It can sniff packets on lo0.

What configuration option for the LPAR virtual network interface (or AIX) could be causing this issue?

**Comment by infrastation** [comment]
Those versions date back to 2007. Could you please check if the problem reproduces with the latest (or at least more recent) versions of tcpdump and libpcap?

**Comment by guyharris** [comment]
> libpcap version aix0.9.8

That's not one of our versions; is this just the tcpdump that ships with AIX?  If so, the bug is best reported to IBM, not us; we have no idea what their version of libpcap does, as they don't make the source available.

**Comment by infrastation** [comment]
Resolved a long time ago, closing.
