### ISSUE TITLE
pcap_compile causing leak in application memory

### ISSUE THREAD

**Issue by sandhu-ramandeep** [the-tcpdump-group/libpcap#449]
I am using libpcap to capture multicast udp packets on CentOS. My application does the following :

Allocate a buffer (linked list of Packets) to store the captured data
Use libpcap to capture a fixed amount of data for a specified filter
Release the buffer after processing the captured data
After doing all this, almost the entire allocated memory is getting leaked.

After doing some debugging I found that this is only happening if I use pcap_compile().

Any help will be greatly appreciated.

**Comment by guyharris** [comment]
Do you call `pcap_compile()` more than once?

If so, each call to `pcap_compile()` allocates a new data structure for the compiled BPF code, and you have to free it when you're done.  To quote the `pcap_freecode()` man page:

       pcap_freecode()  is used to free up allocated memory pointed to by
       a bpf_program struct generated by  pcap_compile()  when  that  BPF
       program  is  no  longer needed, for example after it has been made
       the filter program for a pcap structure by a call to  pcap_setfil-
       ter().

**Comment by sandhu-ramandeep** [comment]
Yes, I am calling pcap_freecode() post pcap_setfilter().

The interesting thing is that the memory being held is the one being allocated for the capture buffers I am using. I have checked the code thoroughly and made sure the buffer destructors are being called as expected.

I also doubt whether the System Monitor is showing the right memory stats.

**Comment by guyharris** [comment]
> I also doubt whether the System Monitor is showing the right memory stats.

Many system memory allocators, when told to free memory, will add the blocks of memory to a pool of free memory, but will not explicitly shrink the address space of the process, so that any monitoring process that reports address space size will not indicate any shrinkage in address space size as a result of freeing the memory.

**Comment by sandhu-ramandeep** [comment]
Is there a way to change this behavior? Like using different memory allocators ? Ours is a c++ based application

**Comment by guyharris** [comment]
Whether you can change it is dependent on the memory allocator the compiler uses and the system library supports.

Note that the memory is *not* "leaked", unless your memory allocator is horribly buggy.  Instead, as I said, it's added to a pool of free memory; subsequent memory allocations will try to get memory from that pool, reusing the memory after it's been freed.

**Comment by sandhu-ramandeep** [comment]
Thanks !! Appreciate your response. Will test it to check if the memory is actually being reused.

**Comment by sandhu-ramandeep** [comment]
We were able to solve the problem by setting "M_MMAP_THRESHOLD" for the malloc command. By default anything less than 128 KB was going to a free list and later getting reused. We got rid of this behavior by setting the M_MMAP_THRESHOLD as 0. Now everything is released when we do a free or delete. 

Thanks for the directions :-)
