### ISSUE TITLE
Does Libpcap on RHEL6 have PF_RING support

### ISSUE THREAD

**Issue by sandhu-ramandeep** [the-tcpdump-group/libpcap#452]
Hello,

I was going through the document : http://www.eetimes.com/document.asp?doc_id=1271874

Just wondering that the libpcap installed on RHEL 6 have PF_RING support by default or will I need to follow the steps as described in the link above.

Thanks in anticipation.

**Comment by juaristi** [comment]
Hi,

I'm not a RHEL user, but probably not. AFAIR the PF_RING patch over libpcap used PF_RING primitives behind the scenes, which have extra requirements, such as the PF_RING kernel module (pf_ring.ko).

On 08/27/2015 05:09 PM, sandhu-ramandeep wrote:
> Hello,
>
> I was going through the document : http://www.eetimes.com/document.asp?doc_id=1271874
>
> Just wondering that the libpcap installed on RHEL 6 have PF_RING support by default or will I need to follow the steps as described in the link above.
>
> Thanks in anticipation.
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/the-tcpdump-group/libpcap/issues/452>.
>

-- 
Regards,
- AJ

**Comment by infrastation** [comment]
libpcap does not include PF_RING code by default, the ntop project maintains a modified version of libpcap with necessary changes. To tell if the RHEL libpcap package is based on the ntop version a RHEL user would have to look in the respective libpcap source RPM package. Closing.
