### ISSUE TITLE
sana

### ISSUE THREAD

**Issue by Sido74118** [the-tcpdump-group/libpcap#456]

**Comment by infrastation** [comment]
From the bug description, which made it into an email but for whatever reason isn't on the web-interface anymore, it is possible to understand you only discovered the dependency on yacc/bison when running "make all" in the libpcap directory. Could you confirm the configure script checked for yacc/bison in its due time and what its test results were? If the configure script failed the test, could you explain where the Makefile came from? Thank you.

**Comment by infrastation** [comment]
Closing due to lack of feedback.
