### ISSUE TITLE
Hardware time stamp clock synchronisation

### ISSUE THREAD

**Issue by euromonkey** [the-tcpdump-group/libpcap#459]
Hi all,

I am using pf_ring with pcap to capture packets arriving on multiple Intel i350 ethernet devices.  

I setup hardware time stamping as follows and both functions return 0.

int status = pcap_set_tstamp_type(deviceHandle, PCAP_TSTAMP_ADAPTER);
status = pcap_set_tstamp_precision(deviceHandle, PCAP_TSTAMP_PRECISION_NANO);

The manual says:  "PCAP_TSTAMP_ADAPTER is a high-precision time stamp supplied by the capture device; it's synchronized with the system clock."

My questions are:

1) How does the clock in each ethernet device get synchronised with the system clock?
2) How often does the synchronisation take place?

Details on OS/versions etc. below.

Many thanks!
Ken

cat /etc/system-release
CentOS Linux release 7.1.1503 (Core) 

uname -a
Linux localhost.localdomain 3.10.0-229.el7.x86_64 #1 SMP Fri Mar 6 11:36:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

libpcap-1.6.2 (part of pf_ring from github on 07.10.2015)

ethtool -T enp5s0f1
Time stamping parameters for enp5s0f1:
Capabilities:
       hardware-transmit     (SOF_TIMESTAMPING_TX_HARDWARE)
    software-transmit     (SOF_TIMESTAMPING_TX_SOFTWARE)
    hardware-receive      (SOF_TIMESTAMPING_RX_HARDWARE)
    software-receive      (SOF_TIMESTAMPING_RX_SOFTWARE)
    software-system-clock (SOF_TIMESTAMPING_SOFTWARE)
    hardware-raw-clock    (SOF_TIMESTAMPING_RAW_HARDWARE)
PTP Hardware Clock: 6
Hardware Transmit Timestamp Modes:
    off                   (HWTSTAMP_TX_OFF)
    on                    (HWTSTAMP_TX_ON)
Hardware Receive Filter Modes:
    none                  (HWTSTAMP_FILTER_NONE)
    all                   (HWTSTAMP_FILTER_ALL)

**Comment by mcr** [comment]
I don't think libpcap can answer your questions, I think you need to ask i350 experts.

**Comment by guyharris** [comment]
> I don't think libpcap can answer your questions, I think you need to ask i350 experts.

...because all that *libpcap* does is to 1) ask that the adapter do hardware time stamping, with a `SIOCSHWTSTAMP` ioctl, and 2) request the particular form of hardware time stamping for the socket being used, with a `SOL_PACKET`/`PACKET_TIMESTAMP` `setsockopt()` call.

After that, it's all up to the driver and the kernel's networking stack; libpcap has nothing to do with it.
