### ISSUE TITLE
test/opentest.c on MSVC

### ISSUE THREAD

**Issue by gvanem** [the-tcpdump-group/libpcap#460]
The `test/opentest.c` doesn't compile using MSVC since it doesn't have `<unistd.h>` and `__attribute__` . A simple fix that I'm using here is:
```
--- a/tests/opentest.c 2015-02-05 23:18:27
+++ b/tests/opentest.c 2015-09-02 13:39:22
@@ -30,8 +30,12 @@
 #include <stdlib.h>
 #include <string.h>
 #include <stdarg.h>
-#include <unistd.h>
 #include <errno.h>
+#ifndef _MSC_VER
+#include <unistd.h>
+#endif
+
+#include "gencode.h"  /* __attribute__() */

 #define MAXIMUM_SNAPLEN                65535
```

The other `test/*.c`file have problems too, but this one is easiest to fix.

**Comment by guyharris** [comment]
So MinGW *does* have `<unistd.h>`, so it should be based on "MSVC or not" rather than "Windows or not"?

**Comment by gvanem** [comment]
Yes. Hence the `#ifndef _MSC_VER`.

**Comment by guyharris** [comment]
So what does MinGW declare in `<unistd.h>`?  [Their home page](http://www.mingw.org) says:

> MinGW compilers provide access to the functionality of the Microsoft C runtime and some language-specific runtimes. MinGW, being Minimalist, does not, and never will, attempt to provide a POSIX runtime environment for POSIX application deployment on MS-Windows. If you want POSIX application deployment on this platform, please consider Cygwin instead.

and `<unistd.h>` is a POSIX header rather than a C header.  On UN\*X, we include it for `getopt()`, but, on Windows, we supply our own `getopt()` and, as of as of a77491e209e49a16cda89508e86cf71c04d6a2c4, we supply our own header for it, so we include that header instead of `<unistd.h>` on Windows (regardless of the compiler).

**Comment by gvanem** [comment]
> ... On UN*X, we include it for getopt(), but, on Windows, we supply our own getopt() and, as of as of a77491e ...

Fine, that seems cleaner.

**Comment by guyharris** [comment]
I've redone the `__attribute__` stuff in the test programs in 17e43dfad4f2923adc1a6c396b4e8e30a6a1dbb9; that should fix the Windows build (and also should at least attempt to put the right attributes on functions, when possible, with compilers that don't define `__GNUC__`).

**Comment by gvanem** [comment]
Can this issue be closed now?

**Comment by guyharris** [comment]
> Can this issue be closed now?

If test/opentest.c builds, yes.

**Comment by gvanem** [comment]
It builds and runs fine.
