### ISSUE TITLE
libpcap can't dump an interface when there is no IPv4 support

### ISSUE THREAD

**Issue by isomer** [the-tcpdump-group/libpcap#468]
If you are on a machine without IPv4 support and try and use tcpdump on an interface other than "any" you get an error:

    # tcpdump -i eth0
    tcpdump: socket for SIOCETHTOOL(ETHTOOL_GET_TS_INFO): Address family not supported by protocol

This is due to iface_ethtool_get_ts_info having "fd = socket(AF_INET, SOCK_DGRAM, 0);", and bailing if that fails.  A workaround for this is to use "-i any", which skips this check.

Please allow libpcap to work on interfaces on machines without IPv4 support.

**Comment by infrastation** [comment]
What would be the easiest way to get a Linux host without IPv4 support?

**Comment by guyharris** [comment]
Should be fixed in 3515b2fd2bb729d07cd9f61d9c9ccfdba34d065b.
