### ISSUE TITLE
I am getting error when trying to build tcpdump

### ISSUE THREAD

**Issue by RGSL** [the-tcpdump-group/libpcap#475]
./libpcap/libpcap.a(pcap.o): In function `pcap_datalink_name_to_val':
    pcap.c:(.text+0x5c4): multiple definition of `pcap_datalink_name_to_val'
    dlnames.o:dlnames.c:(.text+0x0): first defined here
    ./libpcap/libpcap.a(pcap.o): In function `pcap_datalink_val_to_name':
    pcap.c:(.text+0x660): multiple definition of `pcap_datalink_val_to_name'
    dlnames.o:dlnames.c:(.text+0x80): first defined here
    ./libpcap/libpcap.a(pcap.o): In function `pcap_datalink_val_to_description':
    pcap.c:(.text+0x7b4): multiple definition of `pcap_datalink_val_to_description'
    dlnames.o:dlnames.c:(.text+0xac): first defined here
    ./libpcap/libpcap.a(pcap.o): In function `pcap_list_datalinks':
    pcap.c:(.text+0xb30): multiple definition of `pcap_list_datalinks'
    datalinks.o:datalinks.c:(.text+0x0): first defined here
    ./libpcap/libpcap.a(savefile.o): In function `pcap_dump_ftell':
    savefile.c:(.text+0x1124): multiple definition of `pcap_dump_ftell'
    pcap_dump_ftell.o:pcap_dump_ftell.c:(.text+0x0): first defined here
    ./libpcap/libpcap.a(gencode.o): In function `pcap_compile':
    gencode.c:(.text+0x1078): undefined reference to `pcap_parse'
    collect2: error: ld returned 1 exit status
    make[5]: *** [tcpdump] Error 1

Please suggest solution

**Comment by guyharris** [comment]
This is an error trying to *link* tcpdump.  tcpdump provides its own versions of those routines if *its* configure script doesn't find them in the version of libpcap it's being built with; this means that its configure script didn't find those routines, but the linker *is* finding them.

We don't know enough to solve the problem; you'd need to provide the contents of the `config.log` file in the tcpdump source directory, so we can see why its attempt failed, or, at least, the lines starting with the one that contains "checking for pcap_datalink_name_to_val" and ending with the one after the "checking for pcap_dump_ftell" line with "result: no".

**Comment by RGSL** [comment]
This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by configure, which was
generated by GNU Autoconf 2.61.  Invocation command line was

  $ ./configure --with-libpcap-includes=../libpcap-1.0.0-ring/ --with-libpcap-libraries=../libpcap-1.0.0-ring/ -with-libpfring-includes=../lib --with-libpfring-libraries=../lib LDFLAGS=-lpfring -lpcap

## --------- ##
## Platform. ##
## --------- ##

hostname = vineeth-VirtualBox
uname -m = i686
uname -r = 3.19.0-25-generic
uname -s = Linux
uname -v = #26~14.04.1-Ubuntu SMP Fri Jul 24 21:18:00 UTC 2015

/usr/bin/uname -p = unknown
/bin/uname -X     = unknown

/bin/arch              = unknown
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = unknown
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /opt/toolchains/stbgcc-4.8-1.0/bin
PATH: /opt/toolchains/uclibc-crosstools-gcc-4.2.3-4/usr/bin/
PATH: /projects/toolchains/hndtools-mipsel-linux-uclibc-4.2.3-4/usr/bin
PATH: /usr/local/sbin
PATH: /usr/local/sbin
PATH: /usr/local/bin
PATH: /usr/sbin
PATH: /usr/bin
PATH: /sbin
PATH: /bin
PATH: /usr/games
PATH: /usr/local/games


## ----------- ##
## Core tests. ##
## ----------- ##

configure:1751: checking build system type
configure:1769: result: i686-pc-linux-gnu
configure:1791: checking host system type
configure:1806: result: i686-pc-linux-gnu
configure:1948: checking for gcc
configure:1964: found /usr/bin/gcc
configure:1975: result: gcc
configure:2213: checking for C compiler version
configure:2220: gcc --version >&5
gcc (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE
configure:2223: $? = 0
configure:2230: gcc -v >&5
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/i686-linux-gnu/4.8/lto-wrapper
Target: i686-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.4-2ubuntu1~14.04' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-i386/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-i386 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-i386 --with-arch-directory=i386 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-targets=all --enable-multiarch --disable-werror --with-arch-32=i686 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=i686-linux-gnu --host=i686-linux-gnu --target=i686-linux-gnu
Thread model: posix
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04)
configure:2233: $? = 0
configure:2240: gcc -V >&5
gcc: error: unrecognized command line option '-V'
gcc: fatal error: no input files
compilation terminated.
configure:2243: $? = 4
configure:2266: checking for C compiler default output file name
configure:2293: gcc   -lpfring -lpcap conftest.c  >&5
/usr/bin/ld: cannot find -lpfring
/usr/bin/ld: cannot find -lpcap
collect2: error: ld returned 1 exit status
configure:2296: $? = 1
configure:2334: result:
configure: failed program was:
| /* confdefs.h.  */
| #define PACKAGE_NAME ""
| #define PACKAGE_TARNAME ""
| #define PACKAGE_VERSION ""
| #define PACKAGE_STRING ""
| #define PACKAGE_BUGREPORT ""
| /* end confdefs.h.  */
|
| int
| main ()
| {
|
|   ;
|   return 0;
| }
configure:2341: error: C compiler cannot create executables
See `config.log' for more details.

## ---------------- ##
## Cache variables. ##
## ---------------- ##

ac_cv_build=i686-pc-linux-gnu
ac_cv_env_CC_set=
ac_cv_env_CC_value=
ac_cv_env_CFLAGS_set=
ac_cv_env_CFLAGS_value=
ac_cv_env_CPPFLAGS_set=
ac_cv_env_CPPFLAGS_value=
ac_cv_env_CPP_set=
ac_cv_env_CPP_value=
ac_cv_env_LDFLAGS_set=set
ac_cv_env_LDFLAGS_value='-lpfring -lpcap'
ac_cv_env_LIBS_set=
ac_cv_env_LIBS_value=
ac_cv_env_build_alias_set=
ac_cv_env_build_alias_value=
ac_cv_env_host_alias_set=
ac_cv_env_host_alias_value=
ac_cv_env_target_alias_set=
ac_cv_env_target_alias_value=
ac_cv_host=i686-pc-linux-gnu
ac_cv_prog_ac_ct_CC=gcc

## ----------------- ##
## Output variables. ##
## ----------------- ##

CC='gcc'
CFLAGS=''
CPP=''
CPPFLAGS=''
DEFS=''
ECHO_C=''
ECHO_N='-n'
ECHO_T=''
EGREP=''
EXEEXT=''
GREP=''
INSTALL_DATA=''
INSTALL_PROGRAM=''
INSTALL_SCRIPT=''
LDFLAGS='-lpfring -lpcap'
LIBOBJS=''
LIBS=''
LOCALSRC=''
LTLIBOBJS=''
OBJEXT=''
PACKAGE_BUGREPORT=''
PACKAGE_NAME=''
PACKAGE_STRING=''
PACKAGE_TARNAME=''
PACKAGE_VERSION=''
PATH_SEPARATOR=':'
RANLIB=''
SHELL='/bin/bash'
SHLICC2=''
V_CCOPT='-O'
V_DEFS=''
V_GROUP=''
V_INCLS=''
V_PCAPDEP=''
ac_ct_CC='gcc'
bindir='${exec_prefix}/bin'
build='i686-pc-linux-gnu'
build_alias=''
build_cpu='i686'
build_os='linux-gnu'
build_vendor='pc'
datadir='${datarootdir}'
datarootdir='${prefix}/share'
docdir='${datarootdir}/doc/${PACKAGE}'
dvidir='${docdir}'
exec_prefix='NONE'
host='i686-pc-linux-gnu'
host_alias=''
host_cpu='i686'
host_os='linux-gnu'
host_vendor='pc'
htmldir='${docdir}'
includedir='${prefix}/include'
infodir='${datarootdir}/info'
libdir='${exec_prefix}/lib'
libexecdir='${exec_prefix}/libexec'
localedir='${datarootdir}/locale'
localstatedir='${prefix}/var'
mandir='${datarootdir}/man'
oldincludedir='/usr/include'
pdfdir='${docdir}'
prefix='NONE'
program_transform_name='s,x,x,'
psdir='${docdir}'
sbindir='${exec_prefix}/sbin'
sharedstatedir='${prefix}/com'
sysconfdir='${prefix}/etc'
target_alias=''

## ----------- ##
## confdefs.h. ##
## ----------- ##

#define PACKAGE_NAME ""
#define PACKAGE_TARNAME ""
#define PACKAGE_VERSION ""
#define PACKAGE_STRING ""
#define PACKAGE_BUGREPORT ""

configure: exit 77

**Comment by RGSL** [comment]
This is my config.log content

**Comment by guyharris** [comment]
Please try:

1. doing `make distclean` in the libpcap source directory.
2. doing `make distclean` in the tcpdump source directory.
3. undoing any changes you've made to the libpcap or tcpdump source.
4. doing `./configure` and `make` in the libpcap source directory.
5. doing `./configure` and `make` in the tcpdump source directory.

and see what happens.

**Comment by RGSL** [comment]
OK, I will try these

**Comment by infrastation** [comment]
Does this issue still stand?

**Comment by RGSL** [comment]
No, thank you for your support.

Sent from Outlook Mobile<https://aka.ms/blhgte>



On Fri, Apr 15, 2016 at 7:23 AM -0700, "Denis Ovsienko" <notifications@github.com<mailto:notifications@github.com>> wrote:


Does this issue still stand?

-
