### ISSUE TITLE
pcap_perror 'char *prefix' argument

### ISSUE THREAD

**Issue by raybellis** [the-tcpdump-group/libpcap#476]
The second argument to `void pcap_perror(pcap_t *p, char *prefix)` should probably be a `const char *` instead.

When compiling with C++ and `-Wpedantic` you can't pass a string literal in a plain `char *` argument, making it impossible to write e.g. `pcap_error(pc, "prefix")`

**Comment by guyharris** [comment]
Fixed in 98e570c4d9708e46033a6545690ced67cca6f0cb.

(These days, more and more people use `pcap_geterr()` and do their own message output, rather than using `pcap_perror()`, just as people use `strerror()` rather than `perror()`.)
