### ISSUE TITLE
Adding Windows loopback adapter detection for libpcap

### ISSUE THREAD

**Issue by hsluoyz** [the-tcpdump-group/libpcap#477]
How does libpcap tell whether an adatper is a loopback one (like lo in linux). I actually found
`if (ISLOOPBACK(name, flags)) curdev->flags |= PCAP_IF_LOOPBACK`; in `add_or_find_if` function of inet.c file, but the flags are not set anywhere, so I guess the actual execution of` ISLOOPBACK` macro is checking whether the name is something like "lo[digit or none]"?

In fact my implementation for lo in Windows is called "Npcap Loopback Adapter" in https://github.com/nmap/npcap. But the name variable is a random string like `\Device\{B4B27BF5-DECC-428F-AE74-C57344D5402B}` stored in registry. I added this check registry logic to packet.dll (the lower layer of libpcap) and exposed a function called `PacketIsLoopbackAdapter`, I hope libpcap could call this function to check if loopback adapter available for Windows. Is this a good practice?

**Comment by gvanem** [comment]
>  But the name variable is a random string like \Device{B4B27BF5-DECC-428F-AE74-C57344D5402B}

You mean `\Device\NPF_{B4B27BF5-DECC-428F-AE74-C57344D5402B}`?

But haven't you support for a particular `PacketRequest()` code that libpcap/Win32 could use? I.e. to check the cacababilities of your `NPcap`? I believe all drivers **must** support `OID_GEN_SUPPORTED_LIST`. So if the returned list contains a specific `OID_x_LOOPBACK`, libpcap can sure of that and set:
```
dev->flags |= PCAP_IF_LOOPBACK;
```

**Comment by guyharris** [comment]
> How does libpcap tell whether an adatper is a loopback one (like lo in linux).

On UN\*X systems that have an `IFF_LOOPBACK` interface flag, it tests whether that flag is set.

On UN\*X systems that *don't* have an `IFF_LOOPBACK` interface flag, it tests whether the interface name either is "lo" or is "lo" followed by a single digit.

On Windows, it does nothing, as WinPcap doesn't have a loopback interface, so, with NPcap, you're on your own - you can invent your own mechanism.

> I actually found if (ISLOOPBACK(name, flags)) curdev->flags |= PCAP_IF_LOOPBACK; in add_or_find_if function of inet.c file, but the flags are not set anywhere, so I guess the actual execution of ISLOOPBACK macro is checking whether the name is something like "lo[digit or none]"?

Only if the underlying OS doesn't helpfully tell you whether the interface is a loopback interface by supplying an IFF_LOOPBACK as one of the interface flags:

	$ ifconfig lo0
	lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
                           ^^^^^^^^
        options=3<RXCSUM,TXCSUM>
        inet6 ::1 prefixlen 128 
        inet 127.0.0.1 netmask 0xff000000 
        inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1 
        nd6 options=1<PERFORMNUD>

Other *BSDs, and Linux at least with newer kernels, have that flag as well.

> In fact my implementation for lo in Windows is called "Npcap Loopback Adapter" in https://github.com/nmap/npcap. But the name variable is a random string like \Device{B4B27BF5-DECC-428F-AE74-C57344D5402B} stored in registry. I added this check registry logic to packet.dll (the lower layer of libpcap) and exposed a function called PacketIsLoopbackAdapter, I hope libpcap could call this function to check if loopback adapter available for Windows. Is this a good practice?

Yes, that's one way of doing it.

**Comment by hsluoyz** [comment]
@gvanem I didn't find there's any PacketRequest call in libpcap. I presume you said PacketGetNetType call in the pcap_activate_win32 function of pcap-win32.c. It actually sends OID request, but it has no relationship with PCAP_IF_LOOPBACK, see inet.c. In Windows, PCAP_IF_LOOPBACK is never set.

**Comment by hsluoyz** [comment]
@guyharris I have replied in the libpcap list.

**Comment by gvanem** [comment]
> I didn't find there's any PacketRequest call in libpcap.

Look in `pcap-win32.c`. But no need to use this function directly. I forgot that libpcap have these:
```
pcap_oid_set_request()
pcap_oid_get_request()
```

Which are calling `PacketRequest()` via these func-ptrs:
```	
  p->oid_get_request_op = pcap_oid_get_request_win32;
  p->oid_set_request_op = pcap_oid_set_request_win32;
```

But do your driver have support for a specific OID that makes it possible to check if loop-back is available? Isn't that the whole purpose of  **Adding Windows loopback adapter detection for libpcap**?

**Comment by hsluoyz** [comment]
<blockquote>
Look in pcap-win32.c. But no need to use this function directly. I forgot that libpcap have these:
</blockquote>

 OK, I saw the functions now. I don't know what's wrong, because I searched the function in Github search box but didn't find anything.

<blockquote>
But do your driver have support for a specific OID that makes it possible to check if loop-back is available? Isn't that the whole purpose of Adding Windows loopback adapter detection for libpcap?
</blockquote>

I can add a specific OID to check loopback, But I didn't find it useful. Because the information root is in registry. The driver also knows which adapter is loopback by reading registry. So I think providing a packet.dll layer function called PacketIsLoopbackAdapter() is already enough? The problem I'm confronting is where to add this call. Like I said in the mail, I can't do this without changing inet.c, is inet.c changable?

**Comment by gvanem** [comment]
>  So I think providing a packet.dll layer function called PacketIsLoopbackAdapter() is already enough? > The problem I'm confronting is where to add this call. 

A `hDLL=LoadLibrary("Packet.dll")` + `GetProcAddress(hDll,"PacketIsLoopbackAdapter")`? 
Or yet another func-ptr?

> Like I said in the mail, I can't do this without changing inet.c, is inet.c changable?

No harm IMHO. Nothing is set in stone.

**Comment by hsluoyz** [comment]
<blockquote>
A hDLL=LoadLibrary("Packet.dll") + GetProcAddress(hDll,"PacketIsLoopbackAdapter")? 
Or yet another func-ptr?
</blockquote>

By func-ptr, you mean something like `p->activate_op = pcap_activate_win32;`? How to use this? I know `hDLL=LoadLibrary("Packet.dll") + GetProcAddress(hDll,"PacketIsLoopbackAdapter")` works, but it's not that good looking, I want a better way to add this optional PacketIsLoopbackAdapter function.

**Comment by hsluoyz** [comment]
Close this because the loopback feature has been merged.
