### ISSUE TITLE
Errors When Compiling libpcap with android-ndk for multiple architectures.

### ISSUE THREAD

**Issue by deepsidhu1313** [the-tcpdump-group/libpcap#481]
Hi,
I am getting following error when i try to compile latest libpcap and tcpdump on Linux Mint 17.3 using android-ndk. I am playing with a project pcapture and trying to learn Android-ndk.

    nika@nika:~/workspace/PcapCapture/jni$ bash /opt/android-ndk/ndk-build
    [arm64-v8a] SharedLibrary  : libpcap.so
    /home/nika/workspace/PcapCapture/obj/local/arm64-v8a/objs/pcap/libpcap-1.7.4/pcap.o:(.data.rel+0x0): undefined reference to `can_findalldevs'
    /home/nika/workspace/PcapCapture/obj/local/arm64-v8a/objs/pcap/libpcap-1.7.4/pcap.o:(.data.rel+0x8): undefined reference to `can_create'
    /home/nika/workspace/PcapCapture/obj/local/arm64-v8a/objs/pcap/libpcap-1.7.4/pcap.o:(.data.rel+0x10): undefined reference to `usb_findalldevs'
    /home/nika/workspace/PcapCapture/obj/local/arm64-v8a/objs/pcap/libpcap-1.7.4/pcap.o:(.data.rel+0x18): undefined reference to `usb_create'
    /home/nika/workspace/PcapCapture/obj/local/arm64-v8a/objs/pcap/libpcap-1.7.4/pcap.o:(.data.rel+0x20): undefined reference to `netfilter_findalldevs'
    /home/nika/workspace/PcapCapture/obj/local/arm64-v8a/objs/pcap/libpcap-1.7.4/pcap.o:(.data.rel+0x28): undefined reference to `netfilter_create'
    /home/nika/workspace/PcapCapture/obj/local/arm64-v8a/objs/pcap/libpcap-1.7.4/nametoaddr.o: In function `pcap_ether_hostton':
    /home/nika/workspace/PcapCapture/jni/libpcap-1.7.4/nametoaddr.c:490: undefined reference to `ether_hostton'
    collect2: error: ld returned 1 exit status
    make: *** [/home/nika/workspace/PcapCapture/obj/local/arm64-v8a/libpcap.so] Error 1

thanks :smile:

**Comment by guyharris** [comment]
What happens if, in the `/home/nika/workspace/PcapCapture/obj/local/arm64-v8a/objs/pcap/libpcap-1.7.4` directory, you run `make distclean` and then run `./configure`?  What does the configure script print, and what are the contents of the `config.h` file it produces?

**Comment by deepsidhu1313** [comment]
thanks for reply.
Now it says
`nika@nika:~/workspace/PcapCapture/jni$ bash /opt/android-ndk/ndk-build[arm64-v8a] Compile        : pcap <= pcap-linux.c
/home/nika/workspace/PcapCapture/jni/libpcap-1.7.4/pcap-linux.c:116:20: fatal error: config.h: No such file or directory
 #include "config.h"
                    ^
compilation terminated.
make: *** [/home/nika/workspace/PcapCapture/obj/local/arm64-v8a/objs/pcap/libpcap-1.7.4/pcap-linux.o] Error 1
`

**Comment by guyharris** [comment]
So 1) whatever produced the `config.h` did ***NOT*** produce a valid file for use when building for Android and 2) `ndk-build` doesn't handle autotools-based projects such as libpcap and tcpdump by itself.

You've now learned something about android-ndk, namely "it's not sufficient, by itself, to let you build autotools-based projects".

If you do a Web search for

    "autotools" "ndk" "android"

you'll find pages such as [this page on building autotools-based projects for Android](http://danielpocock.com/building-existing-autotools-c-projects-on-android).

**Comment by deepsidhu1313** [comment]
I somehow managed to compile old version of libpcap 1.3.0, but now i am getting error with tcpdump 4.3.0

          nika@nika:~/workspace/PcapCapture/jni$ bash /opt/android-ndk/ndk-build
         [arm64-v8a] Install        : libpcap.so => libs/arm64-v8a/libpcap.so
         [arm64-v8a] Compile        : tcpdump <= addrtoname.c
         In file included from /home/nika/workspace/PcapCapture/jni/tcpdump-4.3.0/addrtoname.c:67:0:
/home/nika/workspace/PcapCapture/jni/tcpdump-4.3.0/setsignal.h:26:13: error: expected declaration specifiers or '...' before '*' token
          RETSIGTYPE (*setsignal(int, RETSIGTYPE (*)(int)))(int);
                                    ^
         make: *** [/home/nika/workspace/PcapCapture/obj/local/arm64-v8a/objs/tcpdump/addrtoname.o]                   Error 1

**Comment by guyharris** [comment]
Remove the `config.h` file in the `/home/nika/workspace/PcapCapture/jni/tcpdump-4.3.0` directory - it's probably wrong, too.

**Comment by guyharris** [comment]
Or just read [Cross-Compiling or Building Android tcpdump?](http://www.androidtcpdump.com/android-tcpdump/compile) and follow its instructions - it doesn't waste time with `ndk-build`, which does not appear to work very well with autotools-based projects such as libpcap and tcpdump.
