### ISSUE TITLE
Request For PreBuilt Binary and Library files for All Android architectures!

### ISSUE THREAD

**Issue by deepsidhu1313** [the-tcpdump-group/libpcap#482]
Hi,

I am trying to build tcpdump and libpcap.so files from many days for android device and doing so i am encountering various errors. So i request you to please provide binary and library files for all architectures as you are the expert developers of both projects.

:smile:

**Comment by levizhao** [comment]
Please refer to [androidtcpdump](http://www.androidtcpdump.com/)  you will find the android binary of tcpdump, it will also tell you how to build libpcap and android with NDK.

**Comment by infrastation** [comment]
There is little to add to the previous comment, closing.
