### ISSUE TITLE
fatal error: 'openssl/crypto.h' file not found

### ISSUE THREAD

**Issue by mizhdi** [the-tcpdump-group/libpcap#483]
doing  make in the tcpdump source directory:

gcc  -DHAVE_CONFIG_H   -D_U_="__attribute__((unused))" -I. -I../libpcap-1.7.4  -DINET6 -g -O2 -c ./setsignal.c
gcc  -DHAVE_CONFIG_H   -D_U_="__attribute__((unused))" -I. -I../libpcap-1.7.4  -DINET6 -g -O2 -c ./tcpdump.c
./tcpdump.c:72:10: fatal error: 'openssl/crypto.h' file not found
#include <openssl/crypto.h>
         ^
1 error generated.
make: *** [tcpdump.o] Error 1

**Comment by guyharris** [comment]
What version of what operating system was this?  If it's OS X, there's a problem in the tcpdump 4.7.4 configure script that's fixed in the version on the master branch (see 548ed98f3b82f524d9bd64616d63c6ca0d9b1fd9).

**Comment by mizhdi** [comment]
thank you!!!
