### ISSUE TITLE
Mac OSX libpcap 1.7.4 forward declaration of 'pcap' !

### ISSUE THREAD

**Issue by liuguiyangnwpu** [the-tcpdump-group/libpcap#495]
/usr/local/Cellar/libpcap/1.7.4/include/pcap/pcap.h:79:16: note: forward declaration of 'pcap'
typedef struct pcap pcap_t;
               ^
1 error generated.

**Comment by guyharris** [comment]
dc65810c11ee4811ed930b888ad9a66ad35018bd should squelch those warnings.
