### ISSUE TITLE
1>..\..\Pcap-win32.c(1389): error C2065: 'flags' : undeclared identifier

### ISSUE THREAD

**Issue by hsluoyz** [the-tcpdump-group/libpcap#506]
If ``HAVE_PACKET_IS_LOOPBACK_ADAPTER`` macro is not defined, MSVC 2013 will report this error:
``1>..\..\Pcap-win32.c(1389): error C2065: 'flags' : undeclared identifier``

The faulty code:
https://github.com/the-tcpdump-group/libpcap/blob/master/pcap-win32.c#L1389

**Comment by guyharris** [comment]
Should be fixed now.
