### ISSUE TITLE
1>..\..\pcap.c(458): error C2065: 'ebuf' : undeclared identifier

### ISSUE THREAD

**Issue by hsluoyz** [the-tcpdump-group/libpcap#507]
MSVC 2013 reports this error:
``1>..\..\pcap.c(458): error C2065: 'ebuf' : undeclared identifier``

See here:
https://github.com/the-tcpdump-group/libpcap/commit/985f531bfaf50ebad71c512bf6c109f0bae6c443#diff-a9e8301ded6a2d84626ccc7062ed2f34R458

**Comment by guyharris** [comment]
Should be fixed by 5743940e7d263dd846d5be3e4cbf318e8e655027.
