### ISSUE TITLE
Libpcap-1.7.4 compile failed on MSVC

### ISSUE THREAD

**Issue by zdunker** [the-tcpdump-group/libpcap#515]
I got winpcap package from [http://www.winpcap.org/devel.htm](url) to build libpcap on Windows MSVC 2015. After copied 1.7.4 repo in winpcap, also copied scanner.c and grammar.c compiled by linux tools, I upgraded libpcap.dsp to libpcap.vcxproj. However, the build failed with following errors:
`C1189 #error Macro definition of vsnprintf conflicts with Standard Library function declaration
C2011 'bpf_insn': 'struct' type redefinition
C2011 'bpf_program': 'struct' type redefinition
C1083 Cannot open include file:'unistd.h': No such file or directory
` etc.
I understand unistd.h is POSIX header other than C header.
Is there any step I missed to build libpcap using MSVC?

**Comment by guyharris** [comment]
> Is there any step I missed to build libpcap using MSVC?

Three steps:

1. Use the current master or 1.8 branch version of libpcap.
2. Use CMake or, with the current master, use `Win32/Prj/wpcap.vcxproj`.
3. Install [WinFlexBison](https://sourceforge.net/projects/winflexbison/) and generate `scanner.c` and `grammar.c` on Windows.

**Comment by zdunker** [comment]
> Use CMake or, with the current master, use Win32/Prj/wpcap.vcxproj.
I saw they changes you've made in 1.8.0. Thanks for caring us MSVC users.
However, my winpcap package doesn't contain ../packetwin7/dll/no netcon and airpacket/packet.lib.
Is this what you built while working on libpcap?
In addition, will it be fine if I build packet.lib from packet9x?
The point I'm asking is if you have modified packet source as well.

**Comment by guyharris** [comment]
> However, my winpcap package doesn't contain ../packetwin7/dll/no netcon and airpacket/packet.lib.

packetwin7 is part of [Npcap](http://www.npcap.org); the current project file is set up for Npcap rather than WinPcap.

> Is this what you built while working on libpcap?

I built using CMake.

> In addition, will it be fine if I build packet.lib from packet9x?

If you are trying to use WinPcap with Windows 9x/Me, you're on your own.  That's not supported any more.

> The point I'm asking is if you have modified packet source as well.

No, I just installed the WinPcap SDK.

**Comment by hsluoyz** [comment]
Hi @zdunker ,

I'm the author of [Npcap](https://github.com/nmap/npcap). Npcap is a fork of WinPcap and supports Vista, Win7, Win8 and Win10. It contains all the functions of WinPcap.

WinPcap has been out of support for a long time. And It doesn't support the latest libpcap. Starting from 0.08, Npcap has added latest libpcap 1.8.0 support. So if you want the latest libpcap code work for you, a good practice is that you ``git clone`` Npcap from https://github.com/nmap/npcap, the ``git submodule`` function will also help you download libpcap repo into the Npcap's ``wpcap\libpcap`` folder. Maybe the shipped libpcap version is not up to date, you can pull the latest version via git on your own.

All components of Npcap are built by ``MSVC 2013`` and ``MSVC 2015``. It doesn't need any other build systems or environments like ``cygwin``. So it's very friendly.

Like Guy said, ``Win32/Prj/wpcap.vcxproj`` is for Npcap and may not work that smoothly on WinPcap. If you really want to do this, you may need to change the ``packet.dll``'s path to ``packetNtx`` for NT systems like XP. This is only one of the issues you will encounter.

**Comment by zdunker** [comment]
> This is only one of the issues you will encounter.
Like IKEA motorcycle engine, right?

Thanks for the reply, and thanks to you @guyharris too. I will switch to Npcap and see the outcome from there. If everything is going sweet, I will come back and close this issue.

**Comment by hsluoyz** [comment]
> Like IKEA motorcycle engine, right?
Yeah, that's it!
