### ISSUE TITLE
Has anywhere in libpcap defined the version string (like "1.8.0")?

### ISSUE THREAD

**Issue by hsluoyz** [the-tcpdump-group/libpcap#518]
I have [a C header](https://github.com/nmap/npcap/blob/master/wpcap/version.h#L7) in Npcap with content:
```c
//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
//

#include "..\version.h"

static const char pcap_version_string[] = "libpcap version " WINPCAP_LIBPCAP_VERSION;
```

And I defined the macro ``WINPCAP_LIBPCAP_VERSION`` as "1.8.0", so this will be returned in ``pcap_lib_version()`` and shown in softwares like Wireshark's About window like ``with Npcap version 0.08, based on libpcap version 1.8.0``. However, I think it's better if this string is defined in libpcap instead of Npcap. Is there any string like this? Thanks.

**Comment by infrastation** [comment]
Have you checked in the source code?

**Comment by hsluoyz** [comment]
OK. I saw this file: https://github.com/the-tcpdump-group/libpcap/blob/master/VERSION. You bumped this file together with the new git tag.

I think I need "include" this file in my C header. But since it only contains a version string, I don't know how to include it in a C syntax..

**Comment by fxlb** [comment]
You can see `version.c` building in `Makefile.in`.

**Comment by fxlb** [comment]
and http://www.tcpdump.org/manpages/pcap_lib_version.3pcap.html.

**Comment by guyharris** [comment]
As @fxlb noted, it's generated in `Makefile.in` from `VERSION` using various UN\*X commands; `version.h` is also generated in a similar fashion.

I don't know whether there's a way, using only what's available from within a Visual Studio project and tools available on Windows, to turn a file containing a version string (as text, not a C string) into a C source or header file that defines or declares a string based on that version string.  If there is, that's what you'd need to do.

**Comment by guyharris** [comment]
So this is now fixed, and this can be closed?

**Comment by hsluoyz** [comment]
I found a bug in in my code: https://github.com/the-tcpdump-group/libpcap/pull/520
