### ISSUE TITLE
Send PCAP invisible packets to local sockets

### ISSUE THREAD

**Issue by hxingpax** [the-tcpdump-group/libpcap#526]
HI, all.

I have to send packets to local sockets based on the packets I captured through PCAP, and I don't want PCAP to capture these new generated packets.

Though It's possible to leave these packets with dedicated filter rules, I think it's good to know if it's possible to send packets to local sockets with these packets completely invisible to PCAP, for efficiency.

**Comment by guyharris** [comment]
What do you mean by "local sockets"?  UNIX-domain sockets?  Internet-protocol sockets connecting to the loopback address (127.0.0.1 for IPv4, ::1 for IPv6)?  Internet-protocol sockets connecting to one of the machine's local addresses other than the loopback addresses?

Packets sent over UNIX-domain sockets *never* get handed to pcap.  Internet-protocol sockets connecting to the loopback address or to another of the same machine's local addresses get handed to pcap only if you're capturing on the loopback interface or, on Linux, the "any" interface.

**Comment by infrastation** [comment]
It seems to me there is nothing more to add to the answer.

**Comment by hxingpax** [comment]
@guyharris What if I change the word 'local' into 'network', I think I just picked the inpercise one.

**Comment by guyharris** [comment]
Internet-protocol sockets connecting to an address on another machine get handed to pcap if, and only if, you're capturing on the interface over which those packets are sent or, on Linux, the "any" interface.

The only way to keep a program using pcap, running on the machine sending the packets, from seeing the packets - whether they're sent locally or over a network - is to change that program to call `pcap_setdirection()` and requesting to see only incoming packets.  This might not work on all operating systems, so check the return code from `pcap_setdirection()`.
