### ISSUE TITLE
question on lib pcap

### ISSUE THREAD

**Issue by abhatikar** [the-tcpdump-group/libpcap#528]
Hi,

I have written an shared library that uses pcap library to capture 802.11 probe requests across different channels and later extract the mac addresses and rssi from the captured packets.

The application links to this library and creates a pthread to call the entry point of the library which setups the capture handle and starts pcap loop to capture the packets

The code organization for the library is as follows

1 setup timer to switch channels every 5 sec

timer_function()
{
            pcap_breakloop()
            pcap_freecode();
            pcap_close(handle)

}
2. setup pcap handle
int32_t pcap_setup_function()
{
            int32_t status = 0;

```
        /*
        * Create pcap handle
        */

        if((handle = pcap_create(pktcap->dev, pktcap->errbuf)) == NULL)
        {
                    fprintf(stderr, "pcap_create() failed: %s\n", pktcap->errbuf);
                    status = -EFAULT;
                    return status;
        }

        /*
        * Turn off promisc mode
        */

        if(pcap_set_promisc(handle, 0) != 0)
        {
                    fprintf(stderr, "Failed to disable promisc mode.\n");
                    status = -EFAULT;
                    wifi_pcap_close_function();
                    return status;
        }

        /*
        * Set SNAP len
        */

        if(pcap_set_snaplen(handle, BUFSIZ) != 0)
        {
                    fprintf(stderr, "Failed to set snaplen.\n");
                    status = -EFAULT;
                    wifi_pcap_close_function();
                    return status;
        }

        /*
        * Set capture timeout
        */

        if(pcap_set_timeout(handle, 1000) != 0)
        {
                    fprintf(stderr, "Failed to set timeout.\n");
                    status = -EFAULT;
                    wifi_pcap_close_function();
                    return status;
        }

        if(pcap_activate(handle) != 0)
        {
                    fprintf(stderr, "pcap_activate() failed\n");
                    status = -EFAULT;
                    wifi_pcap_close_function();
                    return status;
        }

        /*
        * Compile a filter to sniff 802.11 probe requests
        * wlan type mgt subtype probe-req
        */
        if(pcap_compile(handle, &(pktcap->fp), pktcap->filter_exp, 0, PCAP_NETMASK_UNKNOWN) == -1)
        {
                    fprintf(stderr, "pcap_compile() failed: %s\n", pcap_geterr(handle));
                    status = -EFAULT;
                    wifi_pcap_close_function();
                    return status;
        }

        /*
        * Set the compiled filter
        */
        if(pcap_setfilter(handle, &(pktcap->fp)) == -1)
        {
                    fprintf(stderr, "pcap_setfilter() failed: %s\n", pcap_geterr(handle));
                    status = -EFAULT;
                    pcap_freecode(&pktcap->fp);
                    wifi_pcap_close_function();
                    return status;
        }
        return status;
```

}

void start_pcap_capture_function(void)
{
            int32_t status = 0;

```
        /**
        * Setup a timer to strike every scanning interval
        *  to trigger WiFi channel switching.
        */

        status = set_channel_switcher_timer(&oneshotTimer, CHANNEL_SWITCH_SIG, pktcap->interval * 1000);
        if(status != 0)
                    return;

        /**
        * Start the pcap loop to capture and process the WiFi packets
        * loop is broken in the channel_switching_handler before
        * before switching channel
        */
        while((status = pcap_loop(handle, -1, wifi_pcap_process_pkt, NULL)) > 0 );

        timer_delete(oneshotTimer);
```

}

librarymain()
{
            while(run == 1)
            {
                        pcap_setup_function();
                        start_capture();
            }
} 

The issue is that, the application that links to this library, calls this librarymain() as thread startup function.
int32_t main()
{
            pthread_t hWifi;

```
        signal(SIGINT, thread_exit);

        if(pthread_create(&hWifi, NULL, librarymain, NULL)) {

                    fprintf(stderr, "Error creating thread\n");
                    return 1;
        }

        /* wait for the second thread to finish */
        if(pthread_join(hWifi, NULL)) {

                    fprintf(stderr, "Error joining thread\n");
                    return 2;

        }
        return 0;
```

}

After a long run for around 12 hours, I hit a segmentation fault in pcap_compile.
Just wanted to know if I am missing something.

Thanks

**Comment by mcr** [comment]
Abhijeet Bhatikar <notifications@github.com> wrote:
    > I have written an shared library that uses pcap library to capture 802.11
    > probe requests across different channels and later extract the mac addresses
    > and rssi from the captured packets.

    > The application links to this library and creates a pthread to call the entry
    > point of the library which setups the capture handle and starts pcap loop to
    > capture the packets

okay, pcap is not thread safe, but you are sticking to a single thread, so I
think you are okay.

    > /**
    > * Start the pcap loop to capture and process the WiFi packets
    > * loop is broken in the channel_switching_handler before
    > * before switching channel
    > */
    > while((status = pcap_loop(handle, -1, wifi_pcap_process_pkt, NULL)) > 0 );

Does status every return > 0?

    > timer_delete(oneshotTimer);

    > }

    > librarymain()
    > {
    > while(run == 1)
    > {
    > pcap_setup_function();
    > start_capture();
    > }
    > }

...

    > After a long run for around 12 hours, I hit a segmentation fault in
    > pcap_compile.
    > Just wanted to know if I am missing something.

You only call pcap_compile once.  If you are getting a seg fault in that
routine, it could be that your stack was smashed and it just looks that way.

Or, somehow you are calling it multiple times, and something is broken.


--
]               Never tell me the odds!                 | ipv6 mesh networks [
]   Michael Richardson, Sandelman Software Works        | network architect  [
]     mcr@sandelman.ca  http://www.sandelman.ca/        |   ruby on rails    [

**Comment by infrastation** [comment]
Closing due to lack of feedback.
