### ISSUE TITLE
pcap-filter vlan option does not filter vlan packets

### ISSUE THREAD

**Issue by pwp333** [the-tcpdump-group/libpcap#529]
pcap-filter vlan option does not filter vlan packets. No vlan packet shows up after adding this parameter.
Platform: ubuntu 14.04
Package: libpcap0.8:amd64  
Version 1.7.4-2
Tcpdump: version 4.7.4-1ubuntu1

    # tcpdump  -nei eth3 | grep vlan
    tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
    listening on eth3, link-type EN10MB (Ethernet), capture size 262144 bytes
    20:50:29.476296 00:0c:29:fc:5b:18 > 00:0c:29:aa:71:6f, ethertype 802.1Q (0x8100), length 102: vlan 8, p 0, ethertype IPv4, 192.168.1.2 > 192.168.1.1: ICMP echo request, id 2530, seq 453, length 64
    20:50:29.476333 00:0c:29:aa:71:6f > 00:0c:29:fc:5b:18, ethertype 802.1Q (0x8100), length 102: vlan 8, p 0, ethertype IPv4, 192.168.1.1 > 192.168.1.2: ICMP echo reply, id 2530, seq 453, length 64
    ^C134 packets captured
    135 packets received by filter
    0 packets dropped by kernel

    # tcpdump  -nei eth3 vlan
    tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
    listening on eth3, link-type EN10MB (Ethernet), capture size 262144 bytes
    ^C
    0 packets captured
    0 packets received by filter
    0 packets dropped by kernel

    # tcpdump  -nei eth3 vlan 8
    tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
    listening on eth3, link-type EN10MB (Ethernet), capture size 262144 bytes
    ^C
    0 packets captured
    0 packets received by filter
    0 packets dropped by kernel

**Comment by guyharris** [comment]
What happens if you try building libpcap and tcpdump from source, using the libpcap 1.8.1 from www.tcpdump.org?
