### ISSUE TITLE
Cross compiles fail using the wrong archiver

### ISSUE THREAD

**Issue by MoonbaseOtago** [the-tcpdump-group/libpcap#536]
Makefile.in hard codes the host ar  which causes some cross builds to fail, here's a patch

    --- libpcap-1.1.1/Makefile.in   2016-11-02 08:07:04.066533792 +1300
    +++ libpcap-1.1.1.new/Makefile.in       2016-11-02 08:12:25.885667352 +1300
    @@ -73,6 +73,7 @@
    INSTALL_PROGRAM = @INSTALL_PROGRAM@
    INSTALL_DATA = @INSTALL_DATA@
    RANLIB = @RANLIB@
    +AR = @AR@
    
     #
     # Flex and bison allow you to specify the prefixes of the global symbols
    @@ -342,7 +343,7 @@
    
    libpcap.a: $(OBJ)
           @rm -f $@
    -      ar rc $@ $(OBJ) $(ADDLARCHIVEOBJS)
    +      $(AR) rc $@ $(OBJ) $(ADDLARCHIVEOBJS)
           $(RANLIB) $@
    
     shared: $(SHAREDLIB)

**Comment by guyharris** [comment]
Fixed in e25ea10a1327ba928d5fcaa4b28adbe6802e6d4d.
