### ISSUE TITLE
aclocal.m4 should be called acinclude.m4

### ISSUE THREAD

**Issue by rossburton** [the-tcpdump-group/libpcap#537]
aclocal.m4 is reserved for use by aclocal and if the user runs autoreconf on a libpcap clone the aclocal.m4 will be replaced.

As aclocal.m4 is maintained by you and not generated, it should be renamed to acinclude.m4.

**Comment by guyharris** [comment]
[The Autoconf manual, section 3.4 "Using autoconf to Create configure"](https://www.gnu.org/software/autoconf/manual/autoconf.html#autoconf-Invocation) says

> Then it looks for the optional file `acsite.m4` in the directory that contains the distributed Autoconf macro files, and for the optional file `aclocal.m4` in the current directory. Those files can contain your site's or the package's own Autoconf macro definitions (see [Writing Autoconf Macros](https://www.gnu.org/software/autoconf/manual/autoconf.html#Writing-Autoconf-Macros), for more information).

In addition, [section 28 "Expanded before Required"](https://www.gnu.org/software/autoconf/manual/autoconf.html#Expanded-Before-Required) gives an example "trimmed down from an actual package" where "the author wanted to offload some of the text into a new macro in another file included via `aclocal.m4`", which seems to imply that `aclocal.m4` is intended to be used for local macros.

Where in the *autoconf* documentation (not the automake documentation, as we don't use automake) is `acinclude.m4` documented (again, without reference to automake)?

**Comment by rossburton** [comment]
Ah if you don't use automake then I'm mistaken.
