### ISSUE TITLE
How to access the change in global variables in pcap-linux.c file (mmap functions)

### ISSUE THREAD

**Issue by mehul-m-prajapati** [the-tcpdump-group/libpcap#543]
Hi,

I am making some change in gencode.c file. I am calling one API which changes global variable value in pcap-linux.c file.

When I access that variable in function pcap_handle_packet_mmap, I get the default set value and not he value which I changed from an API.

Can you tell me, why this is happening ?

**Comment by mehul-m-prajapati** [comment]
There is a separate process called dumpcap which captures the packet. So, I am using IPC to communicate between processes.

**Comment by guyharris** [comment]
> There is a separate process called dumpcap which captures the packet.

You didn't bother telling us that you were working with Wireshark/TShark, so we had no reason to think dumpcap was involved.

**Comment by mehul-m-prajapati** [comment]
Hi @guyharris ,

It was my mistake not to mention dumpcap and wireshark. I will surely note issues in detail now onwards.

Thanks
