### ISSUE TITLE
Stop capturing after writing N bytes

### ISSUE THREAD

**Issue by kirawrath** [the-tcpdump-group/libpcap#544]
I would like a way to read `n` bytes with `tcpdump` and then exit.
Today we can use `-c` option, but it only counts packets, not bytes.
With the `-C` option I almost have what I want, the problem is that it does not exit after writing the specified size, but instead close that file and start to write a new one.
If I use it in conjunction with the option `-W 1` I still don't get what I need because it will then overwrite the beginning of my file.

This feature does not seem to be complex at all, and I feel many others felt frustrated like I did when I realized I could not accomplish this with `tcpdump` alone (I wrote a wrapper in c++ to overcome this).
I can write this feature myself, I just need to know if there is anything preventing it to be created.

**Comment by guyharris** [comment]
1) This is a tcpdump issue, not a libpcap issue; you should open an issue on the [the tcpdump issue tracker](https://github.com/the-tcpdump-group/tcpdump/issues).

2) The tcpdump command line doesn't handle "stop after X" and "switch files after X" and "rotate files after X" in a very orthogonal fashion, so the interface doesn't extend well.  Wireshark has a better way of handling this, and perhaps tcpdump should adopt something like it.

**Comment by kirawrath** [comment]
Wow, I was in a hurry and ended up writing this feature request on the wrong project ¬¬
Can I (or someone else) delete this issue?

**Comment by guyharris** [comment]
Delete, I'm not sure.  Close, definitely.
