### ISSUE TITLE
pcap_lookupnet() on Windows

### ISSUE THREAD

**Issue by gvanem** [the-tcpdump-group/libpcap#566]
`pcap_lookupnet()` seems buggy for WinPcap/NPcap. E.g. in the `findalldevstest`, it can report bogus
network and mask for an `\\.\airpcap00` device:
```
Preferred device name: \\.\airpcap00
Preferred device is on network: 128.48.162.0/136.49.242.0
```
In `pcap_lookupnet()`, if the `if_addr_size == 0` from `PacketGetNetInfoEx()` (since AirPcap doesn't have a network address), the code regardless will iterate over all `MAX_NETWORK_ADDRESSES` to find an address in the `AF_INET` family. 

AFAICS, it could be written as:
```c
	for (i = 0; i < if_addr_size && i < MAX_NETWORK_ADDRESSES; i++)
	{
		if(if_addrs[i].IPAddress.ss_family == AF_INET)
		{
    ...
```
Or perhaps `memset (&if_addrs, '\0', sizeof(if_addrs));` prior to calling `PacketGetNetInfoEx()`?

**Comment by guyharris** [comment]
Fixed in ae7523298aec2ad4ad54cba40e62ab88b652ac62.
