### ISSUE TITLE
pcap_close() segfaul after first use of library if pcap_dispatch() has not been called

### ISSUE THREAD

**Issue by thomaslloyd82** [the-tcpdump-group/libpcap#584]
To report a security issue please send an e-mail to security@tcpdump.org.

To report bugs and other problems, contribute patches, request a
feature, provide generic feedback etc please see the file
CONTRIBUTING in the libpcap source tree root.

Libpcap:
tcpdump --version
tcpdump version 4.9.0
libpcap version 1.7.4
OpenSSL 1.0.2g  1 Mar 2016

Operating System:
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

Linux tom-VirtualBox 4.4.0-57-generic #78-Ubuntu SMP Fri Dec 9 23:50:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Problem Statement:
Attempting to close the pcap handle immediately after activation produces a malloc double deallocation segfault. 

Important Note: If you can used the pcap_dispatch() call at any point before running this test you will not see the segfaul. It is recommended to restart your machine / OS before attempting to produce this bug.  
This bug is repeatable when you have it in a fault condition. 

Steps to reproduce:
1. pcap_create();
2 set options (see below)
2. pcap_activate();
3 pcap_close()
4 segfault occurs. 

Steps to stop the segfault:

Steps to reproduce:
1. pcap_create();
2 set options (see below)
2. pcap_activate();
3 pcap_dispatch(handle, 0, NULL, NULL );
4 pcap_close()
5. handle is closed as expected. 

options used:
    262144U,                        /* Buffer Size in Bytes         */
    PACKET_CAP_DLT_EN10MB,          /* Data Layer Header Type       */
    FALSE,                          /* Immediate Mode Active        */
    FALSE,                          /* Promiscious Mode Active      */
    TRUE,                           /* Non-Blocking Mode Active     */
    FALSE,                          /* RFMON Mode Active            */
    150U,                           /* Snapshot Length              */
    0U,                             /* Read Timeout In Ms           */
    PACKET_CAP_TSTAMP_PREC_MICRO,   /* Timestamp Precision          */

**Comment by guyharris** [comment]
I was unable to reproduce this problem on my Ubuntu VM:

	tcpdump version 4.9.0
	libpcap version 1.7.4
	OpenSSL 1.0.2g  1 Mar 2016

	No LSB modules are available.
	Distributor ID:	Ubuntu
	Description:	Ubuntu 16.04.2 LTS
	Release:	16.04
	Codename:	xenial

	Linux ubu16-04 4.4.0-78-generic #99-Ubuntu SMP Thu Apr 27 15:29:09 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

with my test program, built with the system version of libpcap.

> options used:
> 
> ...
> PACKET_CAP_DLT_EN10MB, / Data Layer Header Type /

That's *not* an option you can set before pcap_activate() (and there's no such value as `PACKET_CAP_DLT_EN10MB` in libpcap, there's just `DLT_EN10MB`).  It's also the default on an Ethernet interface.

> FALSE, / Immediate Mode Active /

Presumably meaning "you *didn't* turn immediate mode on " - immediate mode off is the default.

> FALSE, / Promiscious Mode Active /

Presumably meaning "you *didn't* turn promiscuous mode on" - promiscuous mode off is the default.

> TRUE, / Non-Blocking Mode Active /

Presumably set *after* pcap_activate(); setting it before it's activated isn't supported in libpcap 1.7.4.

> FALSE, / RFMON Mode Active /

Presumably meaning "you *didn't* turn monitor mode on" - monitor mode off is the default.

> PACKET_CAP_TSTAMP_PREC_MICRO, / Timestamp Precision */

Presumably meaning `PCAP_TSTAMP_PRECISION_MICRO` - there's no such value as `PACKET_CAP_TSTAMP_PREC_MICRO` in libpcap.  Microsecond resolution is the default.

The test program, when not run as root, prints

    libpcap version 1.7.4
    pcap_activate() failed: You don't have permission to capture on that device
    (socket: Operation not permitted)

and, when run as root, prints

    libpcap version 1.7.4
    Opened successfully

It doesn't crash in either case.

**Comment by guyharris** [comment]
Test program:

    #include <stdio.h>
    #include <pcap.h>
    
    int
    main(int argc, char **argv)
    {
    	pcap_t *handle;
    	char errbuf[PCAP_ERRBUF_SIZE];
    	int status;
    
    	if (argc != 2) {
    		fprintf(stderr, "Usage: testme <iface>\n");
    		return 1;
    	}
    	fprintf(stderr, "%s\n", pcap_lib_version());
    	handle = pcap_create(argv[1], errbuf);
    	if (handle == NULL) {
    		fprintf(stderr, "pcap_create(\"%s\") failed: %s\n",
    		    argv[1], errbuf);
    		return 2;
    	}
    
    	pcap_set_buffer_size(handle, 262144);
    	pcap_set_snaplen(handle, 150);
    	pcap_set_timeout(handle, 0);
    	status = pcap_activate(handle);
    	if (status < 0) {
    		/*
    		 * pcap_activate() failed.
    		 */
    		fprintf(stderr, "pcap_activate() failed: %s\n(%s)\n",
    		    pcap_statustostr(status), pcap_geterr(handle));
    		return 2;
    	} else if (status > 0) {
    		/*
    		 * pcap_activate() succeeded, but it's warning us
    		 * of a problem it had.
    		 */
    		fprintf(stderr, "pcap_activate() got a warning: %s\n(%s)\n",
    		    pcap_statustostr(status), pcap_geterr(handle));
    	} else
    		fprintf(stderr, "Opened successfully\n");
    	pcap_setnonblock(handle, 1, errbuf);
    	pcap_close(handle);
    	return 0;
    }

**Comment by guyharris** [comment]
And if I add

    pcap_set_datalink(handle, DLT_EN10MB);

after the `pcap_setnonblock()` call, it still doesn't crash.

**Comment by guyharris** [comment]
Not reproducible - closing.  Reopen if you can reproduce it with the test program, or if you can reproduce it with a modified test program; in the latter case, post the changes or the changed version.
