### ISSUE TITLE
libpcap.so file not always using OBJ_PIC during a make install

### ISSUE THREAD

**Issue by KevinGuthrie** [the-tcpdump-group/libpcap#589]
I have been seeing a random build issue when building libpcap. Occasionally, the libpcap.so.1.8.1 is not being built as a shared object with the PIC option. When tcpdump attempts to load the library, it is reporting
"Can't modify /usr/lib/libpcap.so.1.8.1's text section. Use GCC option -fPIC for shared objects, please."

In reviewing the Makefile.in file, I have seen something I believe is the issue. From the Makefile.in,

libpcap.so: $(OBJ)
        @rm -f $@
        VER=`cat $(srcdir)/VERSION`; \
        MAJOR_VER=`sed 's/\([0-9][0-9]*\)\..*/\1/' $(srcdir)/VERSION`; \
        @V_SHLIB_CMD@ @V_SHLIB_OPT@ @V_SONAME_OPT@$@.$$MAJOR_VER $(LDFLAGS) \
            -o $@.$$VER $(OBJ) $(ADDLOBJS) $(LIBS)

$(SHAREDLIB): $(OBJ_PIC)
        -@rm -f $@
        -@rm -f $(SOLIBRARY) $(SOLIBRARY).$(MAJ)
        $(CC) $(CFLAGS_SHARED) -o $(SHAREDLIB) $(OBJ_PIC) -lc
        ln -s $(SHAREDLIB) $(SOLIBRARY).$(MAJ)
        ln -s $(SOLIBRARY).$(MAJ) $(SOLIBRARY)

install-shared-so: libpcap.so

For our build environment (Linux), the SOLIBRARY will be set to libpcap.so. Occasionally, the libpcap.so target is building when doing a "make install". I can see from the make output that the wrong target is being built sometimes. Other times, the $(SHAREDLIB) target runs first, which creates the $(SOLIBRARY) symlink, which resolves to libpcap.so. That causes the existence of the link and therefore the Makefile does not try to create based off $(OBJ).

I have not been able to determine why this randomly fails. I do know that we are supporting multiple jobs when running make, so that might be part of the issue. I'm wondering if the install-shared-so is supposed to be dependent on the libpcap.so or should it be dependent on $(SHAREDLIB). I'm also unfamiliar with your needs for the libpcap.so target, especially with other OS options.

libpcap version: 1.8.1
OS: Linux
Compiler: GCC 5.3
Make: 3.8.1 or 4.0

**Comment by mcr** [comment]
KevinGuthrie <notifications@github.com> wrote:
    > I have not been able to determine why this randomly fails. I do know
    > that we are supporting multiple jobs when running make, so that might
    > be part of the issue. I'm wondering if the install-shared-so is
    > supposed to be dependent on the libpcap.so or should it be dependent on
    > $(SHAREDLIB). I'm also unfamiliar with your needs for the libpcap.so
    > target, especially with other OS options.

I'm not a fan of the install target causing compilations, because the install
target often runs as root, and may even be installing from a "/usr/src" that
is NFS mounted or something.

On the other hand, when developing, it's really a PITA if the object files do
not get rebuilt when you expect them to be...

-- 
]               Never tell me the odds!                 | ipv6 mesh networks [ 
]   Michael Richardson, Sandelman Software Works        | network architect  [ 
]     mcr@sandelman.ca  http://www.sandelman.ca/        |   ruby on rails    [

**Comment by KevinGuthrie** [comment]
I have realized the issue is from another patch I had applied and not from the original libpcap source.
