### ISSUE TITLE
pcap-dag.c failed to compile

### ISSUE THREAD

**Issue by xendav** [the-tcpdump-group/libpcap#599]
Error using the current git master branch.

Error after ./configure and make:
gcc -fvisibility=hidden -fpic -I.  -I/usr/local/include -DBUILDING_PCAP -DHAVE_CONFIG_H  -D_U_="\_\_attribute__((unused))" -g -O2    -c ./pcap-dag.c
./pcap-dag.c: In function ‘dag_activate’:
./pcap-dag.c:804:6: error: ‘p’ undeclared (first use in this function)
  if (p->snapshot <= 0 || p->snapshot > MAXIMUM_SNAPLEN)
      ^
./pcap-dag.c:804:6: note: each undeclared identifier is reported only once for each function it appears in
make: *** [pcap-dag.o] Error 1

LInes: 804 and 805 **p->snapshot** should probably be changed to **handle->snapshot**

804	if (p->snapshot <= 0 || p->snapshot > MAXIMUM_SNAPLEN)
805	p->snapshot = MAXIMUM_SNAPLEN;

Compiled correctly after change

**Comment by guyharris** [comment]
Instead, I've changed `handle` to `p`, and `handlep` to `pd`, in `dag_activate()`, for consistency with all the other routines in `pcap_dag.c`, in change c358ef5103c205c3f7aa55d42be089e3ab894bae.

**Comment by xendav** [comment]
pcap_dag.c compiles correctly with change.
