### ISSUE TITLE
'bogus savefile header' error

### ISSUE THREAD

**Issue by guyharris** [the-tcpdump-group/libpcap#62]
Converted from [SourceForge issue 1216043](http://sourceforge.net/support/tracker.php?aid=1216043), submitted by artur_barashev

I'm using tcpdump version 3.7.2-1 in one of the Perl 
scripts and occasionally having "tcpdump: pcap_loop: 
bogus savefile header" error reported by script users. 
The script first runs tcpdump for 5 sec to capture all the 
traffic in the file (tcpdump -i any -w tmp_file) and then 
kills it with SIGTERM. After that script runs tcpdump 
again passing to it the file with saved packets with -r 
option and that's when the error happens. I can't 
reproduce the problem myself but several script users 
reported it, I got those files with saved traffic and they 
are corrupted indeed. Script runs on Linux RedHat9, 
2.6.7-11 kernel.
I've built debugging version of tcpdump and ran it under 
gdb passing to it 2 corrupted tcpdump savefiles provided 
by script users. The corruption happens in generic 
tcpdump header, hdr->caplen and hdr->len at 
savefile.c:513 are both corrupted.
I can't provide corrupted files at this point since they 
contain private user data.

**Comment by infrastation** [comment]
"Created: 2005-06-06" (at SourceForge). Closing, as it is not practicable to debug this issue now given the amount of information about the bug.

**Comment by guyharris** [comment]
Yes, libpcap-using programs such as tcpdump printing  "pcap_loop: bogus savefile header" errors if they're reading a corrupted file is correct behavior.

So the problem is with whatever process *wrote* that file.  And, as noted, we have insufficient information to debug *that* process.
