### ISSUE TITLE
capture len vs packet len

### ISSUE THREAD

**Issue by joewilliams** [the-tcpdump-group/libpcap#626]
I am running into a rare segfault when running my libpcap program against `afl`. It seems like I am overwriting some memory I previously used. The conditions seem to be where the capture length is large, in this case 9310, and the packet length are more normal sized, 54. In the real world is this possible? Should I just be guarding against large differences between capture and packet length?

My code does something like:

```
u_char *copy_pkt = (u_char *)malloc(pkthdr->caplen);
memcpy(copy_pkt, pkt, pkthdr->caplen);
```

And then later attempts to access some memory containing some configuration data, which triggers the segfault:
```
if (table_id >= ctx->raw_config->num_tables) {
```

```
(gdb) print ctx->raw_config->num_tables
Cannot access memory at address 0x7ffff74d020b
```

Thanks for any help you can provide!

System details:
```
root@jessie:/vagrant# tcpdump --version
tcpdump version 4.9.2
libpcap version 1.6.2
OpenSSL 1.0.1t  3 May 2016

root@jessie:/vagrant# uname -a
Linux jessie 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u2 (2017-06-26) x86_64 GNU/Linux

root@jessie:/vagrant# cat /etc/issue
Debian GNU/Linux 8 \n \l
```

**Comment by guyharris** [comment]
> The conditions seem to be where the capture length is large, in this case 9310, and the packet length are more normal sized, 54. In the real world is this possible?

It's possible if either 1) there's a bug in the underlying capture mechanism that libpcap is using, 2) there's a bug in libpcap that gets the lengths wrong, or 3) you're reading from a file, rather than doing a live capture, and the file has packets with the captured length > the actual length (either due to it being captured on a system with one of those bugs or due to somebody - or some*thing*, such as AFL - deliberately writing that file to try to trigger bugs in programs reading the file).

> My code does something like:
> 
>     u_char *copy_pkt = (u_char *)malloc(pkthdr->caplen);
>     memcpy(copy_pkt, pkt, pkthdr->caplen);

That shouldn't overwrite any memory, unless *`malloc()`* is buggy.

> And then later attempts to access some memory containing some configuration data, which triggers the segfault:

Make sure it's not something unrelated to libpcap that's doing the overwriting.

**Comment by joewilliams** [comment]
Thanks for the quick response. 

> 3) you're reading from a file, rather than doing a live capture, and the file has packets with the captured length > the actual length (either due to it being captured on a system with one of those bugs or due to somebody - or something, such as AFL - deliberately writing that file to try to trigger bugs in programs reading the file).

Sorry for not being more clear, this is the case. I am reading a bad pcap that `afl` produced.

**Comment by joewilliams** [comment]
Is it appropriate to skip packets that meet where `pkthdr->caplen != pkthdr->len` since it's likely something went wrong?

**Comment by guyharris** [comment]
That's one thing you could do with those packets, although you might want to report that as an error, not just silently skip them.

You could also:

- use the captured length as the on-the-wire length if it's greater than the reported on-the-wire length;

- use the on-the-wire length as the captured length if it's less than the reported captured length.

But if you're not actually *using* the on-the-wire length, this is just revealing a bug in your program, as the exact same crash would happen if, for the offending packet, its on-the-wire length were 9310.

Note also that if AFL is changing the captured length field in the packet header, without actually changing the number of bytes of packet payload follow, libpcap will act as if that captured length field contains the amount of packet data, and will either not read enough data or will read too much data, and treat something that's probably in the middle of packet data as a packet record header.

**Comment by joewilliams** [comment]
> Note also that if AFL is changing the captured length field in the packet header, without actually changing the number of bytes of packet payload follow, libpcap will act as if that captured length field contains the amount of packet data, and will either not read enough data or will read too much data, and treat something that's probably in the middle of packet data as a packet record header.

I think I got this fixed up now, it looks like my code was assuming full packets and wasn't dealing with the truncated packets `afl` was producing properly. I am now making sure the capture length is at least as long as the sum of the headers in the packets I am looking at.

**Comment by guyharris** [comment]
> it looks like my code was assuming full packets and wasn't dealing with the truncated packets

Yes, that can happen with normal un-fuzzed captures, such as a capture done with older versions of tcpdump and the default 68/96-byte snapshot length, or done with newer versions of tcpdump and a `-s` flag setting the snapshot length less than the maximum packet length, so any program that reads pcap or pcapng files *must not* assume full packets.

> I am now making sure the capture length is at least as long as the sum of the headers in the packets I am looking at.

Yes, all programs that read capture files must do those checks.

**Comment by joewilliams** [comment]
Thanks for all the help @guyharris!
