### ISSUE TITLE
Documentation for pcap_lib_version does not suggest freeing the returned string

### ISSUE THREAD

**Issue by dmiller-nmap** [the-tcpdump-group/libpcap#635]
The string pointer returned from `pcap_lib_version` is allocated with `malloc`, so it must be `free`d to avoid leaking memory. It would be helpful if the `pcap_lib_version.3pcap` man page noted that it is the responsibility of the caller to `free` the pointer.

**Comment by gvanem** [comment]
> so it must be freed to avoid leaking memory. 

And when mixing CRTs and all that, `free()` cannot safely be used. A public `pcap_free()` perhaps?
(and rename the one in `scanner.c` to something else).

**Comment by guyharris** [comment]
> The string pointer returned from `pcap_lib_version` is allocated with `malloc`

In the current master branch, it's *not* allocated with `malloc` on most platforms.

And even when it is, it's allocated only the first time the function is called, and subsequent calls just return the string allocated and constructed by the first call.

In current releases, it's also allocated once and memoized in that fashion.

So if you try to free the string you get from a `pcap_lib_version()` call, bad things will happen.

**Comment by guyharris** [comment]
Note also that the `pcap_lib_version()` returns a `const char *`, which should suggest that it is *not* intended that it ever be handed to `free()`.

**Comment by gvanem** [comment]
> *not* allocated with malloc on most platforms.

But on *some*. Would it be possible to return a `static char buf[]` of a suitable large enough buffer instead?

**Comment by guyharris** [comment]
> But on *some*. Would it be possible to return a `static char buf[]` of a suitable large enough buffer instead?

It might, but what would the advantage be?  "Large enough", computed at compile time, might, on systems where you're using *Pcap and packet32 from the same release, waste more memory (for the space reserved for, but unused for, "with packet32.dll XXX") than would the malloc overhead for a precise-length string.

**Comment by guyharris** [comment]
And in the current master branch, `pcap_lib_version()` *will* return a pointer to a statically-allocated string, unless you're running with a packet32.dll with a different version number from the {Win,N}Pcap version number.
