### ISSUE TITLE
pcap-config not marked executable when built using cmake

### ISSUE THREAD

**Issue by antcodd** [the-tcpdump-group/libpcap#643]
On git master (as of gf1de55b) when compiling with cmake pcap-config does not have the execute bit set. This causes tcpdump to not find local libpcap pcap-config and fail to configure. Manually setting the execute bit with chmod +x appears to resolve the issue.

OS: CentOS 7.3 x86-64, with DAG RPMs installed.

```
$ stat -c "%A" pcap-config
-rw-r--r--
```
When building with ./configure the execute bit is set correctly.
```
$ stat -c "%A" pcap-config
-rwxr-xr-x
```
Unlike with ./configure, pcap-config appears to be built at generate time.

**Comment by antcodd** [comment]
Here is the relevant part of tcpdump config.log. I think it is just falling back to trying to use the static library with no dependency information and roughly expected behaviour. If not I can report a bug at tcpdump. It works successfully when pcap-config is marked executable (not sure if using the static library then though).

```
configure:5363: checking for local pcap library
configure:5591: result: ../libpcap/libpcap.a
configure:5595: checking for pcap-config
configure:5628: result: no
configure:5687: checking for pcap_loop
configure:5687: gcc -o conftest -g -O2   conftest.c ../libpcap/libpcap.a -lsmi  >&5
../libpcap/libpcap.a(pcap-dbus.c.o): In function `dbus_read':
pcap-dbus.c:(.text+0x36): undefined reference to `dbus_connection_pop_message'
pcap-dbus.c:(.text+0x53): undefined reference to `dbus_connection_read_write'
pcap-dbus.c:(.text+0xbb): undefined reference to `dbus_connection_pop_message'
pcap-dbus.c:(.text+0xe0): undefined reference to `dbus_message_is_signal'
pcap-dbus.c:(.text+0x127): undefined reference to `dbus_message_marshal'
pcap-dbus.c:(.text+0x1b3): undefined reference to `dbus_free'
../libpcap/libpcap.a(pcap-dbus.c.o): In function `dbus_write':
pcap-dbus.c:(.text+0x21f): undefined reference to `dbus_message_demarshal'
pcap-dbus.c:(.text+0x25c): undefined reference to `dbus_error_free'
pcap-dbus.c:(.text+0x27e): undefined reference to `dbus_connection_send'
pcap-dbus.c:(.text+0x28d): undefined reference to `dbus_connection_flush'
pcap-dbus.c:(.text+0x299): undefined reference to `dbus_message_unref'
../libpcap/libpcap.a(pcap-dbus.c.o): In function `dbus_cleanup':
pcap-dbus.c:(.text+0x309): undefined reference to `dbus_connection_unref'
../libpcap/libpcap.a(pcap-dbus.c.o): In function `dbus_activate':
pcap-dbus.c:(.text+0x491): undefined reference to `dbus_bus_get'
pcap-dbus.c:(.text+0x4da): undefined reference to `dbus_error_free'
pcap-dbus.c:(.text+0x50a): undefined reference to `dbus_bus_get'
pcap-dbus.c:(.text+0x553): undefined reference to `dbus_error_free'
pcap-dbus.c:(.text+0x59a): undefined reference to `dbus_connection_open'
pcap-dbus.c:(.text+0x5e6): undefined reference to `dbus_error_free'
pcap-dbus.c:(.text+0x606): undefined reference to `dbus_bus_register'
pcap-dbus.c:(.text+0x643): undefined reference to `dbus_error_free'
pcap-dbus.c:(.text+0x7b7): undefined reference to `dbus_connection_set_max_received_size'
pcap-dbus.c:(.text+0x7e4): undefined reference to `dbus_bus_add_match'
pcap-dbus.c:(.text+0x7f0): undefined reference to `dbus_error_is_set'
pcap-dbus.c:(.text+0x804): undefined reference to `dbus_error_free'
pcap-dbus.c:(.text+0x829): undefined reference to `dbus_bus_add_match'
pcap-dbus.c:(.text+0x835): undefined reference to `dbus_error_is_set'
pcap-dbus.c:(.text+0x86b): undefined reference to `dbus_error_free'
../libpcap/libpcap.a(pcap-dag.c.o): In function `dag_platform_cleanup':
pcap-dag.c:(.text+0xbc): undefined reference to `dag_stop_stream'
pcap-dag.c:(.text+0x101): undefined reference to `dag_detach_stream'
pcap-dag.c:(.text+0x149): undefined reference to `dag_close'
../libpcap/libpcap.a(pcap-dag.c.o): In function `dag_read':
pcap-dag.c:(.text+0x39a): undefined reference to `dag_advance_stream'
../libpcap/libpcap.a(pcap-dag.c.o): In function `dag_activate':
pcap-dag.c:(.text+0xe49): undefined reference to `dag_parse_name'
pcap-dag.c:(.text+0xf31): undefined reference to `dag_open'
pcap-dag.c:(.text+0xfa1): undefined reference to `dag_attach_stream64'
pcap-dag.c:(.text+0xffe): undefined reference to `dag_get_stream_poll64'
pcap-dag.c:(.text+0x10f9): undefined reference to `dag_set_stream_poll64'
pcap-dag.c:(.text+0x1149): undefined reference to `dag_start_stream'
pcap-dag.c:(.text+0x11b2): undefined reference to `dag_info'
pcap-dag.c:(.text+0x141b): undefined reference to `dag_stop_stream'
pcap-dag.c:(.text+0x1460): undefined reference to `dag_detach_stream'
pcap-dag.c:(.text+0x149c): undefined reference to `dag_close'
../libpcap/libpcap.a(pcap-dag.c.o): In function `dag_findalldevs':
pcap-dag.c:(.text+0x17b7): undefined reference to `dag_parse_name'
pcap-dag.c:(.text+0x17fa): undefined reference to `dag_open'
pcap-dag.c:(.text+0x1819): undefined reference to `dag_pciinfo'
pcap-dag.c:(.text+0x183b): undefined reference to `dag_device_name'
pcap-dag.c:(.text+0x187e): undefined reference to `dag_rx_get_stream_count'
pcap-dag.c:(.text+0x18a4): undefined reference to `dag_attach_stream'
pcap-dag.c:(.text+0x18b7): undefined reference to `dag_detach_stream'
pcap-dag.c:(.text+0x1939): undefined reference to `dag_close'
../libpcap/libpcap.a(pcap-dag.c.o): In function `dag_setnonblock':
pcap-dag.c:(.text+0x1a33): undefined reference to `dag_get_stream_poll64'
pcap-dag.c:(.text+0x1aad): undefined reference to `dag_set_stream_poll64'
../libpcap/libpcap.a(pcap-dag.c.o): In function `dag_get_datalink':
pcap-dag.c:(.text+0x1c15): undefined reference to `dag_get_stream_erf_types'
collect2: error: ld returned 1 exit status
configure:5687: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME ""
| #define PACKAGE_TARNAME ""
| #define PACKAGE_VERSION ""
| #define PACKAGE_STRING ""
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL ""
| #define inline inline
| #define HAVE___ATTRIBUTE__ 1
| #define STDC_HEADERS 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_MEMORY_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_UNISTD_H 1
| #define HAVE_FCNTL_H 1
| #define HAVE_RPC_RPC_H 1
| #define HAVE_NETINET_IF_ETHER_H 1
| #define TIME_WITH_SYS_TIME 1
| #define USE_LIBSMI 1
| #define ENABLE_SMB 1
| #define HAVE_OPENAT 1
| #define HAVE_OS_IPV6_SUPPORT 1
| #define HAVE_VFPRINTF 1
| #define HAVE_STRDUP 1
| #define HAVE_STRSEP 1
| #define HAVE_GETOPT_LONG 1
| #define HAVE_FORK 1
| #define HAVE_VFORK 1
| #define HAVE_STRFTIME 1
| #define HAVE_SETLINEBUF 1
| #define HAVE_ALARM 1
| #define HAVE_VSNPRINTF 1
| #define HAVE_SNPRINTF 1
| #define RETSIGTYPE void
| #define RETSIGVAL /**/
| #define HAVE_SIGACTION 1
| #define HAVE_GETRPCBYNUMBER 1
| /* end confdefs.h.  */
| /* Define pcap_loop to an innocuous variant, in case <limits.h> declares pcap_loop.
|    For example, HP-UX 11i <limits.h> declares gettimeofday.  */
| #define pcap_loop innocuous_pcap_loop
| 
| /* System header to define __stub macros and hopefully few prototypes,
|     which can conflict with char pcap_loop (); below.
|     Prefer <limits.h> to <assert.h> if __STDC__ is defined, since
|     <limits.h> exists even on freestanding compilers.  */
| 
| #ifdef __STDC__
| # include <limits.h>
| #else
| # include <assert.h>
| #endif
| 
| #undef pcap_loop
| 
| /* Override any GCC internal prototype to avoid an error.
|    Use char because int might match the return type of a GCC
|    builtin and then its argument prototype would still apply.  */
| #ifdef __cplusplus
| extern "C"
| #endif
| char pcap_loop ();
| /* The GNU C library defines this for functions which it implements
|     to always fail with ENOSYS.  Some functions are actually named
|     something starting with __ and the normal name is an alias.  */
| #if defined __stub_pcap_loop || defined __stub___pcap_loop
| choke me
| #endif
| 
| int
| main ()
| {
| return pcap_loop ();
|   ;
|   return 0;
| }
configure:5687: result: no
configure:5692: error: This is a bug, please follow the guidelines in CONTRIBUTING and include the
config.log file in your report.  If you have downloaded libpcap from
tcpdump.org, and built it yourself, please also include the config.log
file from the libpcap source directory, the Makefile from the libpcap
source directory, and the output of the make process for libpcap, as
this could be a problem with the libpcap that was built, and we will
not be able to determine why this is happening, and thus will not be
able to fix it, without that information, as we have not been able to
reproduce this problem ourselves.
```

**Comment by antcodd** [comment]
re-tested against 14a097, just in case #642 fixed the problem but still present.

**Comment by sgeto** [comment]
![screenshot 50](https://user-images.githubusercontent.com/8343121/31106826-dccbdda6-a7f6-11e7-9cec-62356af8b593.png)

With cmake, the execute bit is set when installing pcap-config.
I never thought of using that file from within pcap source dir...

**Comment by antcodd** [comment]
tcpdump seems to look for libpcap in ../libpcap by default and only uses system libpcap pcap-common if that directory is not found. Oddly I'm not sure there is an option to give it a different path. This also causes some issues in that you can't run cmake with a different build directory which is common or tcpdump will try to use the system one.

**Comment by sgeto** [comment]
Hehe I never build tcpdump...

A quick look shows that there is a `$PCAP_CONFIG` variable that can be overidden during `configure`:
https://github.com/the-tcpdump-group/tcpdump/blob/master/configure#L5405

try:
`PCAP_CONFIG=path/to/pcap-config ./configure`
or the other way around:
`./configure PCAP_CONFIG=path/to/pcap-config`

**Comment by guyharris** [comment]
> tcpdump seems to look for libpcap in ../libpcap by default and only uses system libpcap pcap-common if that directory is not found.

This is an ancient part of tcpdump's configuration, added so that you could download libpcap and tcpdump, unpack them into subdirectories of some directory, build libpcap, *not* install it, and them build tcpdump and link it with the libpcap you've built.

As far as I know, it dates back to when

1. libpcap was shipped with few, if any, OSes;

1. libpcap was mainly used by tcpdump;

to let you get tcpdump running without having to install libpcap.

It wasn't really built around the notion of out-of-tree builds; it'd take some more thought to figure out how it should work in that case.

It's probably *less* useful now, given that Linux, macOS, \*BSD, Solaris, and AIX ship with libpcap, and that tcpdump is no longer requires a particular version of libpcap or a newer version (it does autoconf checks for various APIs), so you only need to build and install libpcap if:

1. you're on an OS that doesn't have it (and even HP-UX has a HP-UX Porting and Archive Centre port of libpcap, so that probably means "obsolete flavor of UN\*X");

1. your OS doesn't have the latest shiniest version of libpcap, and you want that version for some reason.

But it can still be useful for development and testing purposes if you're doing development and testing of libpcap and tcpdump.

**Comment by sgeto** [comment]
> try:
> PCAP_CONFIG=path/to/pcap-config ./configure
> or the other way around:
> ./configure PCAP_CONFIG=path/to/pcap-config

both combinations work.

**Comment by antcodd** [comment]
If that is the case then perhaps it should default to using the system version? For some reason I thought using the system libpcap was not recommended but I might be getting my projects confused.

Anyway, in this case I was just using tcpdump as a mule to test the DAG changes @guyharris  introduced a few days ago to make sure they actually worked.

PCAP_CONFIG with an absolute path to pcap-config seems to work, but requires installing to a prefix to get the execute bit set.

Personally I think it makes sense to set the execute bit on pcap-config cmake builds at configure or make time for consistency with using ./configure. It seems to be only thing preventing this from working when run with ```cmake .``` and the default configuration.

**Comment by guyharris** [comment]
> If that is the case then perhaps it should default to using the system version?

If there is no "adjacent" libpcap directory, that's what it does.

> For some reason I thought using the system libpcap was not recommended

If that's for tcpdump, that's probably a remnant of the days when you had libpcap 0.x and tcpdump 3.x, or libpcap 1.x and tcpdump 4.x, being somewhat tied together, with the expectation that you'd use tcpdump {3,4}.x with libpcap {0,1}.x.

> Personally I think it makes sense to set the execute bit on pcap-config cmake builds at configure or make time for consistency with using ./configure.

Probably.  It's a bit of a pain, as CMake doesn't seem to have an explicit "set the permissions on this file" operation, and the `configure_file()` command doesn't have an option to set the permissions on the output file, so it'd mean giving `pcap-config.in` execute permission so that `configure_file()` will give the output file execute permission.  (`pcap-config` is supposed to work on Windows with MinGW, as well as on UN\*X.)

**Comment by sgeto** [comment]
even more painful than giving executable permission to pcap-config is to swap all the paths during installation.
For pcap-config to work from the build directory the --cflag and --libs output must point to local files.
When installed, the same commands must point to files in the your install prefix.

I think it's a better idea to turn the $PCAP_CONFIG variable into an option (--with-pcap-config=...) in tcpdump's configure script then to engage in this maze.

**Comment by antcodd** [comment]
> even more painful than giving executable permission to pcap-config is to swap all the paths during installation.
For pcap-config to work from the build directory the --cflag and --libs output must point to local files.
When installed, the same commands must point to files in the your install prefix.

Oh ouch, I hadn't noticed that. So my libpcap after pcap-config is pointing at a /usr/local libpcap which isn't actually installed and then somehow still manages to work (perhaps tcpdump manually pulling in the one from ../libpcap ignoring that part of pcap-config):

From tcpdump linker output:
```
../libpcap/libpcap.a  -ldbus-1 -ldag -lpthread -lsmi
```

tcpdump also seems to statically link libpcap when using ```../libpcap/``` as well which should be orthogonal to where the library was picked up from. Automatic major changes in behaviour based on whether ```../libpcap``` is present seems like a bad idea.

**Comment by sgeto** [comment]
AC_LBL_LIBPCAP in tcpdump's aclocal.m4 looks for ../libpcap if the pcap-config way failed. So yeah, your pcap-config is kinda useless right now.

**Comment by fxlb** [comment]
>This is an ancient part of tcpdump's configuration, added so that you could download libpcap and tcpdump, unpack them into subdirectories of some directory, build libpcap, not install it, and them build tcpdump and link it with the libpcap you've built.
> [...]
> But it can still be useful for development and testing purposes if you're doing development and testing of libpcap and tcpdump.

Useful, yes.

**Comment by antcodd** [comment]
Even with PCAP_CONFIG set and installing libpcap to a prefix, I still get tcpdump linked to the system libpcap.

**Comment by antcodd** [comment]
Come to think of it that might actually be ld finding the system version at run time rather than a problem with the build? My knowledge of dynamic linking specific paths is a bit hazy.

**Comment by sgeto** [comment]
Does the final linking stage look a bit like this:

```
gcc -ffloat-store -DHAVE_CONFIG_H   -D_U_="__attribute__((unused))" -I. 
-IC:/Users/Ali/projects/libpcap/build/mingw64/include  -g -O2  -o tcpdump setsignal.o [...] 
-lcrypto -LC:/Users/Ali/projects/libpcap/build/mingw64/lib  -lwpcap
```

notice the `-L`
It should be present an point to the location of recent pcap installation.

**Comment by sgeto** [comment]
you can force that too:

make LDFLAGS='-lcrypto -L/path/pcap/lib/folder -lpcap'

**Comment by antcodd** [comment]
Ah, the problem is I specified a relative path for the cmake install prefix. This makes pcap-config give out ```-Lbin/lib -Wl,-rpath,bin/lib -lpcap``` which is a directory that doesn't exist in tcpdump/ so it probably falls back to the system one.

**Comment by sgeto** [comment]
> I specified a relative path for the cmake install prefix

that's nuts 😆

**Comment by mcr** [comment]
I think that this issue is closed?
I think that leaving pcap-config without +x in the source directory probably is better as it won't get found by mistake.

**Comment by guyharris** [comment]
> I think that this issue is closed?
> I think that leaving pcap-config without +x in the source directory probably is better as it won't get found by mistake.

If so, we should change it for autotools as well:

    $ ls -l pcap-config
    -rwxr-xr-x  1 gharris  admin  1892 Mar 26 17:48 pcap-config

and that would break tcpdump's "check for a libpcap with the same parent directory" support - even for a local libpcap, it tries to run its pcap-config script to find out what additional libraries libpcap requires.
