### ISSUE TITLE
Winpcap Capture Filter does not Work on Fragmented IPv6 Packets

### ISSUE THREAD

**Issue by Peterdoo** [the-tcpdump-group/libpcap#659]
Under Windows 2016 inside an ESXi VM I execute the following:

ping -6 -l 2006 www.google.com

With Wireshark on the same PC using capture filter "ip6" (Winpcap 4.1.3), all ICMPv6 packets are captured even though the requests and replies are fragmented in two packets each. When using capture filter "icmp6", these ICMPv6 packets are not captured at all.

Also the following ICMPv6 packet that includes the too large fragment is not captured. This ICMPv6 packet itself is not fragmented but also not captured when using capture filter "icmp6":

    Internet Protocol Version 6, Src: xxxx::xxxx, Dst: xxxx::xxxx
0110 .... = Version: 6
.... 0000 0000 .... .... .... .... .... = Traffic Class: 0x00 (DSCP: CS0, ECN: Not-ECT)
.... .... .... 0000 0000 0000 0000 0000 = Flow Label: 0x00000
Payload Length: 1240
Next Header: ICMPv6 (58)
Hop Limit: 64
Source: xxxx::xxxx
Destination: xxxx::xxxx
Internet Control Message Protocol v6
Type: Packet Too Big (2)
Code: 0
Checksum: 0xd597 [correct]
[Checksum Status: Good]
MTU: 1406
Internet Protocol Version 6, Src: xxxx::xxxx, Dst: xxxx::xxxx
    0110 .... = Version: 6
    .... 0000 0000 .... .... .... .... .... = Traffic Class: 0x00 (DSCP: CS0, ECN: Not-ECT)
    .... .... .... 0000 0000 0000 0000 0000 = Flow Label: 0x00000
    Payload Length: 1456
    Next Header: Fragment Header for IPv6 (44)
    Hop Limit: 128
    Source: xxxx::xxxx
    Destination: xxxx::xxxx
    [Destination SA MAC: Avm_xx:xx:xx (xx:xx:xx:xx:xx:xx)]
    [Source GeoIP: Unknown]
    [Destination GeoIP: Unknown]
    Fragment Header for IPv6
        Next header: ICMPv6 (58)
        Reserved octet: 0x00
        0000 0000 0000 0... = Offset: 0 (0 bytes)
        .... .... .... .00. = Reserved bits: 0
        .... .... .... ...1 = More Fragments: Yes
        Identification: 0x316a3334
Data (1184 bytes)

As in IPv6 there is no way to avoid fragmenting and it is done automatically when necessary because of the MTUs, this behavior causes that many IPv6 packets can be lost when capturing specifying the protocol. In my opinion Winpcap should capture also fragmented IPv6 packets when a protocol is used in capture filter. And also non-fragmented ICMPv6 packets that are a reply to fragmented ICMP/UDP/TCP packet.

**Comment by guyharris** [comment]
We'd need to see the BPF code generated for the filter "icmp6". As this is Wireshark, you would do that by:

- selecting Capture > Options;
- in the Capture Options dialog, selecting the interface on which you're capturing;
- typing the filter into the capture filter field;
- clicking the "Compile BPFs" button.

Copy and paste the filter code from there.

Also, please copy and paste the raw hex dump field for a packet that should have been captured but wasn't, so we can see what that BPF code would have as input.  Sadly, you can't copy and paste the hex dump pane, so you'd have to use Export Packet Dissections > As Plain Text..., with "Summary line" and "Details" un-checked and "Bytes" checked, and with "Selected packets only" with the packet in question selected.  Then you'd need to copy-and-paste from the file.

**Comment by Peterdoo** [comment]
This is the BPF code from Wireshark:
(000) ldh      [12]
(001) jeq      #0x86dd          jt 2	jf 5
(002) ldb      [20]
(003) jeq      #0x3a            jt 4	jf 5
(004) ret      #262144
(005) ret      #0

I can already see that this BPF does not check for IPv6 fragmentation header. The correct BPF for icmp6 would be:
(000) ldh      [12]
(001) jeq      #0x86dd          jt 2	jf 8
(002) ldb      [20]
(003) jeq      #0x3a            jt 7	jf 4
(004) jeq      #0x2c            jt 5	jf 8
(005) ldb      [56]
(006) jeq      #0x3a            jt 7	jf 8
(007) ret      #262144
(008) ret      #0

Similar would have to be added for tcp and udp BPFs.

Is the BPF generated by Wireshark or by Winpcap?

**Comment by guyharris** [comment]
> Is the BPF generated by Wireshark or by Winpcap?

To quote what I said in [the Wireshark bug you filed on this](https://bugs.wireshark.org/bugzilla/show_bug.cgi?id=14154l):

> This is a libpcap issue; capture filters are implemented by libpcap (and the OS kernel in most UN*Xes and the NPF driver in Windows with {WinPcap,Npcap} - Wireshark has no part in the process other than calling pcap_compile() and pcap_setfilter().

which is why I said "File an issue with libpcap".

Current versions of libpcap generate

    (000) ldh      [12]
    (001) jeq      #0x86dd          jt 2    jf 8
    (002) ldb      [20]
    (003) jeq      #0x3a            jt 7    jf 4
    (004) jeq      #0x2c            jt 5    jf 8
    (005) ldb      [54]
    (006) jeq      #0x3a            jt 7    jf 8
    (007) ret      #68
    (008) ret      #0

so the problem is that current versions of WinPcap are based on an older version of libpcap that doesn't have commit 58275c05a5cf9c3512bcbb1192ff351d32ccccbd.

You might try un-installing WinPcap and installing [Npcap](http://www.npcap.org) instead; it should be based on a newer version of libpcap.

**Comment by Peterdoo** [comment]
OK, thank you. I see that it was you that corrected that about 6 years ago for libpcap.

I will try Npcap. But for the rest of the users, will there be an updated version of WinPcap or Npcap bundled with Wireshark? For now it comes with WinPcap 4.1.3 which does not handle capture filters correctly for IPv6.

**Comment by guyharris** [comment]
> But for the rest of the users, will there be an updated version of WinPcap or Npcap bundled with Wireshark?

That's a Wireshark issue.

**Comment by guyharris** [comment]
So, for example, reopen the Wireshark bug, but make it say "Wireshark should bundle a version of WinPcap or Npcap based on an up-to-date version of libpcap".  Currently, WinPcap isn't being actively maintained, so there would need to *be* such a version of WinPcap, and Npcap is under [a license](https://github.com/nmap/npcap/blob/master/LICENSE) that's not an open-source license and not as free as the Wireshark developers might like.

**Comment by guyharris** [comment]
Dup of #259.
