### ISSUE TITLE
pcap_next_ex hangs forever

### ISSUE THREAD

**Issue by snoopspy** [the-tcpdump-group/libpcap#667]
pcap_next_ex function does not wake up when not only read_timeout elapsed, but also pcap_close is called in other thread. See the following result. pcap_next_ex function wakes up when only filtering packet is sniffed. Here is the sample code.  

https://github.com/snoopspy/pcap_close_test  

Thanks in advance.  

tcpdump version 4.9.2  
libpcap version 1.8.1

**Comment by guyharris** [comment]
> pcap_next_ex function does not wake up when not only read_timeout elapsed

The timeout isn't a timeout that guarantees that a read will not block any longer than the specified timeout; it's a timeout that guarantees that, if packets are not being immediately delivered to the code reading them, they will be delivered within the specified amount of time.

The original name used for this, the "read timeout", is misleading, so we have renamed it the "packet buffer timeout".  Here is the description of that timeout, from the pcap(3pcap) man page in the tip of the master branch:

       packet buffer timeout
	      If,  when  capturing,  packets  are  delivered  as  soon as they
	      arrive, the application capturing the packets will be  woken  up
	      for  each  packet  as  it arrives, and might have to make one or
	      more calls to the operating system to fetch each packet.

	      If, instead, packets are not delivered as soon as  they  arrive,
	      but  are	delivered after a short delay (called a "packet buffer
	      timeout"), more than one packet can be  accumulated  before  the
	      packets are delivered, so that a single wakeup would be done for
	      multiple packets, and each set of calls made  to	the  operating
	      system  would  supply  multiple  packets,  rather  than a single
	      packet.  This reduces the per‐packet CPU overhead if packets are
	      arriving	at  a  high rate, increasing the number of packets per
	      second that can be captured.

	      The packet buffer timeout is required  so  that  an  application
	      won’t  wait for the operating system’s capture buffer to fill up
	      before packets are delivered; if packets	are  arriving  slowly,
	      that wait could take an arbitrarily long period of time.

	      Not  all platforms support a packet buffer timeout; on platforms
	      that don’t, the packet buffer timeout is ignored.  A zero  value
	      for the timeout, on platforms that support a packet buffer time‐
	      out, will cause a read to wait forever to allow  enough  packets
	      to arrive, with no timeout.

	      NOTE:  the  packet  buffer timeout cannot be used to cause calls
	      that read packets to return within a  limited  period  of  time,
	      because, on some platforms, the packet buffer timeout isn’t sup‐
	      ported, and, on other platforms, the timer doesn’t  start  until
	      at  least one packet arrives.  This means that the packet buffer
	      timeout should NOT be  used,  for  example,  in  an  interactive
	      application  to  allow  the  packet capture loop to ‘‘poll’’ for
	      user input periodically, as there’s no  guarantee  that  a  call
	      reading packets will return after the timeout expires even if no
	      packets have arrived.

	      The packet buffer timeout is set with pcap_set_timeout().

Code using libpcap should *not* use it as a way of ensuring that, for example, a loop does not block indefinitely.

> pcap_close is called in other thread

We do *not* support simultaneous access to the same `pcap_t` in multiple threads, with one exception.  Once you've obtained a `pcap_t *` by calling `pcap_create()`, `pcap_open_live()`, `pcap_open_offline()`, etc., all subsequent references to it must either be done solely within one thread or must be wrapped with a lock of some sort to ensure that only one thread accesses it at a time.

The exception is that you may call `pcap_breakloop()` in another thread and, on Windows, you may call `pcap_getevent()` on an activated `pcap_t * in another thread.

**Comment by snoopspy** [comment]
Ok, I see. Thank you for your reply.
