### ISSUE TITLE
How to get it working on lower version of linux like 2.6.32?

### ISSUE THREAD

**Issue by beyondhong** [the-tcpdump-group/libpcap#668]
My device is running 2.6.32 kernel , and when I port libpcap-1.8.1 to it ,it's not working.
Because the header files are old and some libraries are not exist. How should I deal this kind of issue? Use a lower version of libpcap?

**Comment by guyharris** [comment]
> My device is running 2.6.32 kernel , and when I port libpcap-1.8.1 to it ,it's not working.

What does "not working" mean?  Does it mean "you can't compile it" or "you can compile it but it can't capture traffic"?

> Because the header files are old and some libraries are not exist.

So it sounds as if you can't compile it.

What are the compile errors?

It *should* compile, even if it can't use features present on newer kernels - and the only library it should *always* depend on is the C library; the lack of some libraries should only disable certain additional features.

**Comment by infrastation** [comment]
Original reporter, could you follow the bug reporting guidelines from the `CONTRIBUTING` file please?

**Comment by beyondhong** [comment]
the version of my gcc & kernel are too old
