### ISSUE TITLE
broken gitignore, needed files are not versioned

### ISSUE THREAD

**Issue by lipner** [the-tcpdump-group/libpcap#670]
bpf_filter.c is autogenerated, and thus ignored in .gitignore
net/bpf_filter.c is also ignored, but it shouldn't be.

Consider changing gitignore:
1. remove 'net' from the file
2. change bpf_filter.c to /bpf_filter.c in the file

**Comment by mcr** [comment]
Fixed in 3bb4fc19

**Comment by lipner** [comment]
On my machine, have to remove ‘net’ as well from gitignore

**Comment by mcr** [comment]
I did "echo >>net/bpf_filter.c" and "git status" and it showed up as changed.
Can you show me how things worked for you?

--
]               Never tell me the odds!                 | ipv6 mesh networks [
]   Michael Richardson, Sandelman Software Works        | network architect  [
]     mcr@sandelman.ca  http://www.sandelman.ca/        |   ruby on rails    [
