### ISSUE TITLE
When will be new release of libpcap

### ISSUE THREAD

**Issue by paravmellanox** [the-tcpdump-group/libpcap#675]
This is really not a code issue but a release question.

Last libpcap release was in Oct-2016.

We and users are looking for a new libpcap release which contains #652 and #585 into libpcap.
Can someone let us know about plan to release libpcap containing this patches?

**Comment by mcr** [comment]
Soon. We are in the midset of a deluge of fuzzing-based CVEs, which of which
affect libpcap as well as tcpdump.  We can see the light at the end of the
tunnel.  I'm hoping that by end of March, we'll have a release.

--
]               Never tell me the odds!                 | ipv6 mesh networks [
]   Michael Richardson, Sandelman Software Works        | network architect  [
]     mcr@sandelman.ca  http://www.sandelman.ca/        |   ruby on rails    [

**Comment by paravmellanox** [comment]
Thanks @mcr for the update. Look forward to have a release in March end.

**Comment by paravmellanox** [comment]
Hi @mcr, Any progress with the release of libpcap?

**Comment by paravmellanox** [comment]
Hi @mcr, @guyharris, Can you please update when do you plan to release which contains #652 and #585?
Several users are blocked due to unavailability of release. If you could please update the plan, it helps to plan out when it is usable.

**Comment by infrastation** [comment]
Apparently people are busy doing other work, please have patience.

**Comment by paravmellanox** [comment]
Hi @infrastation, thanks for the update. We just like to know the roadmap/plan of the release so that we can align other activities around, which depends on it.

**Comment by paravmellanox** [comment]
@guyharris. @mcr @infrastation, sorry to bother you again on this topic.
Any progress on this libpcap release?

**Comment by dbarrosop** [comment]
+1 on this one. Any plans for anytime release soon?

**Comment by aron-silverton** [comment]
I see that there are v1.9.0 release candidates now. Thanks. Looking forward to the final version.

**Comment by infrastation** [comment]
libpcap 1.9.0 is available for download.

**Comment by paravmellanox** [comment]
Awesome. Thanks.
