### ISSUE TITLE
Solaris latency 

### ISSUE THREAD

**Issue by guyharris** [the-tcpdump-group/libpcap#68]
Converted from [SourceForge issue 1457168](http://sourceforge.net/support/tracker.php?aid=1457168), submitted by hstenzel

Greetings--

On Solaris, bufmod increases latency as well as
efficiency.  My requirement is low latency; I'm willing
to trade efficiency for low latency.

When calling pcap_live_open() in libpcap 0.9.4 on
Solaris (multiple versions), and setting the timeout, I
discovered through trial and error that setting it to
anything below 10 resulted in libpcap not receiving any
packets.

I found I was able to work around the problem by
disabling bufmod.  Perhaps this should be handled under
the covers by libpcap itself.

The code snippet follows.

Thanks.

{
        /\* from man bufmod -- "STREAMS Buffer Module"
           emiminate latency on Solaris
       SBIOCSTIME
         Set the read timeout value to the value
referred to by
         the  struct timeval pointer given as argument.
Setting
         the timeout value to zero has the side-effect
of forc-
         ing the chunk size to zero as well, so that
the module
         will pass all  incoming  messages  upward 
immediately
         upon  arrival.   Negative  values are rejected
with an
         EINVAL error.
         */
        struct timeval tv;
        struct strioctl str;

```
    tv.tv_sec = 0;
    tv.tv_usec = 0;

    str.ic_cmd = SBIOCSTIME;
    str.ic_timout = -1;
    str.ic_len = sizeof(tv);
    str.ic_dp = (char *)&tv;

    printf("setting Solaris-specific SBIOCSTIME to
```

improve latency\n");
        if ( ioctl(pcap_get_selectable_fd(pcap), I_STR,
&str) != 0) {
          perror("SBIOCSTIME set");
          fprintf(stderr,"setting SBIOCSTIME failed\n");
          exit(1);
        }
      }

**Comment by infrastation** [comment]
The last conversation in this bug report on SF took place in 2006, and in 2013 this issue was copied to GH. In 2021 it is a different Solaris and a different libpcap, so if there is still any problem to solve, it would need to be stated from scratch. Closing this request after 15 years.

**Comment by guyharris** [comment]
> In 2021 it is a different Solaris

Especially if it's Solaris 11, which offers BPF as a capture mechanism, so it works the same as \*BSD and macOS.

> and a different libpcap

...which has `pcap_set_immediate_mode()`; immediate mode trades efficiency for low latency, and is implemented for bufmod.  Code that wants immediate packet delivery should use `pcap_set_immediate_mode()`.
