### ISSUE TITLE
v4tunnel support on Linux

### ISSUE THREAD

**Issue by shawnl** [the-tcpdump-group/libpcap#725]
iftop cannot report data on v4tunnel IPv6 tunnels (like Hurricane Electric[1]). I presume this is due to lack of support for v4tunnel in libpcap.

I might be interested in doing some work on this if I can get pointed in the right place. `net/ipv4/ip_tunnel.c` ?

[1] https://www.tunnelbroker.net/

**Comment by infrastation** [comment]
If you run tcpdump on that interface and it displays what you expect, this would mean libpcap handles it fine.

**Comment by shawnl** [comment]
tcpdump works
