### ISSUE TITLE
calling pcap_compile() with invalid const char* str leads to runtime exception in Visual Studio

### ISSUE THREAD

**Issue by lasgel** [the-tcpdump-group/libpcap#731]
When calling pcap_compile with const char *str "ether dst 0:0:0:0:0:ffff:7f00:1" for example the program crashes. 
The expected behaviour is that pcap_compile returns -1 because the string is not valid and we are passing an IPv6 address instead of an exptected MAC address.

**Comment by guyharris** [comment]
Fixed in c513a4781f33985be01fa6999a9ad21e1e7a0f1b.
