### ISSUE TITLE
How to get device name from pcap_t

### ISSUE THREAD

**Issue by tianchao-haohan** [the-tcpdump-group/libpcap#736]
libpcap version: 1.8.1
OS: Centos 7.5 x64

Error happened when I tried to get the device name via "pcapDesc->opt.device", in which, pcapDesc is the type of pcap_t *.
And the error message is " error: request for member ‘opt’ in something not a structure or union".

How to get the device name from pcap descriptor?
Thanks!

**Comment by guyharris** [comment]
> I guess that's because the user programs are not supposed to reach into `struct pcap`.

Correct - we do not guarantee that this structure won't change in source-incompatible or binary-incompatible ways from release to release.  A program that wants to keep track of the device name must keep its *own* copy of the name.

**Comment by tianchao-haohan** [comment]
@guyharris Is there any API could be used to get the device name from the pcap descriptor?
We need to check the status of device periodically. The status check API pcap_lookupnet and the parameter is the type of char*. But we just keep the pcap descriptor after pcap_open_live and original device name isn't saved. 
So, we want to get the device name from pcap_t and then call pcap_lookupnet to check the status of the corresponding device.
Is there any other method to do this?

**Comment by guyharris** [comment]
> Is there any API could be used to get the device name from the pcap descriptor?

No.

> We need to check the status of device periodically. The status check API pcap_lookupnet 

The only "status" that `pcap_lookupnet()` returns is an IPv4 address and netmask for the interface.  Is that what you mean by "status"?

> Is there any other method to do this?

Yes.  You could save the original device name.

**Comment by guyharris** [comment]
> Need to check whether the device is keeping online. Is there any API could be used for this?

That depends on what you mean by "online".

**Comment by tianchao-haohan** [comment]
Take "ifconfig ethx up/down" for example, up means the device is online and down means the device offline.

**Comment by guyharris** [comment]
There's no libpcap API that will indicate whether the device is up or down in that sense.

So, again, *save the name of the device* (as we've said at least twice), and then, for example, do an `SIOCGIFFLAGS` ioctl to get the flags, and check whether `IFF_UP` is set.

**Comment by tianchao-haohan** [comment]
Got that, Thanks a lot!
