### ISSUE TITLE
Document backwards compatibility and version introduced for various functions

### ISSUE THREAD

**Issue by dmiller-nmap** [the-tcpdump-group/libpcap#745]
As discussed in [this issue on Nmap](https://github.com/nmap/nmap/pull/1291#issuecomment-414461132), it is helpful to know in what version a particular function was introduced. The `pcap(3pcap)` manpage does have a "BACKWARDS COMPATIBILITY" section, but it only discusses the location of the `pcap.h` header and the addition of the `pcap_create` and `pcap_activate` functions in libpcap 1.0.0. An example of a function that does not have backwards compatibility documentation is `pcap_set_immediate_mode()`.

I would like to either see the "BACKWARDS COMPATIBILITY" section of the `pcap(3pcap)` manpage updated to include API changes (function additions/deletions primarily), or have a similar section in the manpage of each function. Realizing that this could be a substantial effort, I would suggest that API changes prior to 1.0.0 probably do not have to be documented.

**Comment by infrastation** [comment]
It would help if you suggested particular changes to the man pages, at least for some functions at first.

**Comment by dmiller-nmap** [comment]
Examples:

* `PCAP_NETMASK_UNKNOWN` constant used for `pcap_compile` added in libpcap 1.1.0
* `pcap_set_tstamp_type` and related functions added in libpcap 1.2.1
* `pcap_set_immediate_mode` added in libpcap 1.5.0
* `PCAP_IF_UP` and `PCAP_IF_RUNNING` constants added in libpcap 1.6.1
* `pcap_dump_open_append` added in libpcap 1.7.2?

**Comment by infrastation** [comment]
Thank you, I have confirmed the releases for the changes above are correct and updated respective man pages to contain these notes under a new "BACKWARD COMPATIBILITY" section. If you would like to extend the coverage feel free to open a pull request using the commit 756ff0a as an example. Closing as resolved.

**Comment by infrastation** [comment]
These updates have been propagated to the plain-text and HTML files at [the web-site](http://www.tcpdump.org/manpages).

**Comment by guyharris** [comment]
I've added some additional "BACKWARD COMPATIBILITY" sections and expanded some of them either to say "with older versions of libpcap you can't get this" or "with older versions of libpcap here's what you have to do to get this"; the pcap_set_immediate_mode man page has the latter.

They should show up on the Web site within 24 hours.

**Comment by infrastation** [comment]
Published (this process is not completely automatic).
