### ISSUE TITLE
Can I capture packet from multiple NIC's in two threads?

### ISSUE THREAD

**Issue by astrojhgu** [the-tcpdump-group/libpcap#746]
I'm trying to receive UDP packet streams from (not to be confused, the data are sent by UDP protocol one by one to form a data stream) from two NICs. Each packet has an increasing id. For example:
From NIC1
pkt1-1, pkt1-2, pkt1-3...
will be received
From NIC2
pkt2-1, pkt2-2, pkt2-3
will be received.

Then I will perform some computation between pkt1-i and pkt2-i (with i in 1, 2, 3...).

In order to implement above algorithm, I plan to run two threads, inside each thread, one NIC will be captured and fill into their own ring buffers. A third thread will do the computation.

So my question is that does libpcap allow one to capture NICs from two independent threads? For me the only requirement is that in each ring buffer, the order of packets should be kept.

**Comment by agnosticdev** [comment]
In regards to capturing NICs from two independent threads, as long as your program can see the interface you are wanting to capture from and you have access to capture from this interface on this particular NIC, then I do not see why this would be a issue.
As an example:
```bash
# To be run in one thread in your program capturing wireless packets
$ tcpdump -i wan0 -nn -s 0 -w wireless.dump
# To be run in another thread in your program capturing Ethernet packets
$ tcpdump -i lan0 -nn -s 0 -w ethernet.dump
```

The order of the packets I cannot comment on.

**Comment by astrojhgu** [comment]
Thanks @guyharris and @agnosticdev , I have succeeded to use pcap to capture two interfaces.

**Comment by agnosticdev** [comment]
Great!  Glad to hear you had success @astrojhgu !
