### ISSUE TITLE
pcap_compile() is almost thread safe

### ISSUE THREAD

**Issue by guyharris** [the-tcpdump-group/libpcap#75]
Converted from [SourceForge issue 1534711](http://sourceforge.net/support/tracker.php?aid=1534711), submitted by elliots

Since I help develop a mult-threaded application that uses libpcap I'm interested in the thread safeness of libpcap.  After looking through the libpcap code a bit I've tentatively concluded:
    1) A few APIs that do not take a PCAP handle as an argument, such as pcap_compile(), are not thread safe in any sense.
    2) APIs that take a PCAP handles, such as pcap_dispatch(), are probably thread safe in the sense that they different PCAP handles may be accessed concurrently.  And this type of API may be thread safe in general.

As to 1) instances of APIs not being thread safe include the "setjmp(top_ctx)" done at the beginning of pcap_compile() (used for exception handling).  "top_ctx" is global, so there is a risk of thread later doing a longjmp() back to another threads stack pointer and stack frame.  It's not clear to me if flex and bison are thread in the way they are being used in libpcap, but that may be an issue.

As to 2) it looks like APIs such as pcap_dispatch() aren't concerned with global variables.  Instead they mostly work with data in the PCAP handle.  So it is probably sufficient to have one mutex per PCAP handle.

Any movement toward making APIs closer to being thread safe and or a statement about how thread safe they are would be great.

**Comment by FirefighterBlu3** [comment]
i'm pretty sure it wasn't fixed. libpcap is still intolerant of threading.

**Comment by guyharris** [comment]
libpcap now requires Flex and either Bison or Berkeley YACC, and, as of fb20696441656c36961e92e3ddf074d770e81c55, has no global state in the BPF compiler other than a single array that's present only if you've configured libpcap with `--enable-optimizer-dbg`, which is not, should not be, and will never be the default.

So, as long as you don't try to use a given `pcap_t` in more than one thread, all the APIs should be thread-safe *in the current master branch version* (not yet in any released version), unless I've missed a global variable.
