### ISSUE TITLE
iterate over the list in the pcap_close_all function

### ISSUE THREAD

**Issue by msehnout** [the-tcpdump-group/libpcap#759]
https://github.com/the-tcpdump-group/libpcap/blob/master/pcap.c#L3545

The handle is assigned from `pcaps_to_close` but the `next` field is not used. Shouldn't we iterate over the list and call `pcap_close` on each `pcap`?

**Comment by guyharris** [comment]
> Shouldn't we iterate over the list and call `pcap_close` on each pcap?

If a `pcap_t` is added to the `pcaps_to_close` list, the close operation pointer for the `pcap_t` must point to a routine that calls `pcap_remove_from_pcaps_to_close()`, which removes it from the list.

So the list is being mutated out from under `pcap_close_all()`, and, once you close the `pcap_t` that's at the head of the list, the next `pcap_t` in the list becomes the head of the list, so there's no need to iterate over the list - instead, you iterate until the list is empty, which has the same effect.

(The goal isn't to close *every* `pcap_t` on exit, the goal is to close those for which cleanup operations must be done in userland.  We rely on the OS kernel to close open file descriptors and to release the entire process address space on exit.)
