### ISSUE TITLE
Unable to start application (on Ubuntu platform) built with libpcap on CentOS platform.

### ISSUE THREAD

**Issue by AlexeyABureev** [the-tcpdump-group/libpcap#763]
Hello,

I've got issue while testing application built with usage of libpcap. Application was built on CentOS platform, attempt to start was performed on Ubuntu platform.

CentOS version: CentOS Linux release 7.3.1611 (Core)
Ubuntu version: Ubuntu 18.04 LTS (Bionic Beaver)

tcpdump/libpcap version (CentOS): tcpdump version 4.5.1, libpcap version 1.5.3
tcpdump/libpcap version (Ubuntu): tcpdump version 4.9.2, libpcap version 1.8.1

Application depends on specified libpcap version (built with -lpcap) picked from CentOS.
Output of ldd from CentOS: libpcap.so.1 => /lib64/libpcap.so.1 (0x00007fed295f4000)
Output of ldd from Ubuntu: libpcap.so.1 => not found

Is it possible to make common build for CentOS and Ubuntu platforms (with different versions of tcpdump/libpcap)? Or I need to care about same tcpdump/libpcap versions on target systems?

Application was successfully started on Ubuntu platform after rebuild it on Ubuntu.
Thanks for help.

**Comment by guyharris** [comment]
> Application was built on CentOS platform, attempt to start was performed on Ubuntu platform.

[Welcome to the wonderful world of Linux binary compatibility!](https://askubuntu.com/questions/23818/is-linux-binary-universal-to-all-kinds-of-distributions)

If your program is linked with a dynamic shared library, there is no guarantee that it will work on distributions other than the one for which it's built.  The same library might have different version numbers on different distributions, for example.

It *might* work if you can *statically* link with libpcap, if libc doesn't have a similar problem.
