### ISSUE TITLE
Problem with network adapter _ Hardware config.

### ISSUE THREAD

**Issue by hminh2201** [the-tcpdump-group/libpcap#768]
Hello everyone!! I am new to pcap library. And I have some problem with the hardware. First, I get source code references from GitHub to sniff the packet from networks so as to get the vallue of RSS. Everything is going to be ok until I want to change it into another network adapter (wlan0mon and wlan1mon). But the RSS is not getting the correct value, keep -256 and unchange. 
[5] devices connected to P0807 is: 
  B0:70:2D:x:x:x               Estimated Distance: 1026516727220.913	RSS: -256
  44:78:3E:69:CD:C8	Estimated Distance: 1026516727220.913	RSS: -256
  E4:A7:A0:57:42:C6	Estimated Distance: 1026516727220.913	RSS: -256
  D0:92:9E:E4:FA:D8	Estimated Distance: 1026516727220.913	RSS: -256
  E0:C7:67:70:A8:91	Estimated Distance: 1026516727220.913	RSS: -256

I was thinking about the device config. Is it right? Please help me !!
Here is what they config in global_variable:
char *channel[ NUMBER_CHANNEL ]

char *device;
unsigned int channelValue = 0;
struct itimerval newValue;
AccessPoint *startAP = NULL;
Station *startStation = NULL;
Node *startNode = NULL;
Undevice *startUndevice = NULL;

**Comment by guyharris** [comment]
Sounds like a bug in your program.  It's not *our* program (I don't know where you got a program to get the "RSS" value - did you mean "RSSI value"? - but you didn't get it from our GitHub repository); I suggest you ask for support from whoever you got the code from.
