### ISSUE TITLE
i386 deprecated in mojave

### ISSUE THREAD

**Issue by snafu123** [the-tcpdump-group/libpcap#781]
i386 appears deprecated with mojave (darwin 18.2.0). i think this is the patch:

    diff --git a/configure b/configure
    index 885bc85b..b9a9e77f 100755
    --- a/configure
    +++ b/configure
    @@ -8182,6 +8182,13 @@ fi
     			V_PROG_LDFLAGS_FAT="-arch x86_64 -arch i386"
     			;;
    
    +		darwin18.2*)
    +			# Mojave.  Build libraries for x86-64 only
    +			# 32-bit x86 deprecated
    +			V_LIB_CCOPT_FAT="-arch x86_64"
    +			V_LIB_LDFLAGS_FAT="-arch x86_64"
    +			;;
    +
     		darwin*)
     			#
     			# Post-Snow Leopard.  Build libraries for x86-64
    diff --git a/configure.ac b/configure.ac
    index 604de849..eb72c184 100644
    --- a/configure.ac
    +++ b/configure.ac
    @@ -1704,6 +1704,13 @@ darwin*)
     			V_PROG_LDFLAGS_FAT="-arch x86_64 -arch i386"
     			;;
    
    +		darwin18.2*)
    +			# Mojave.  Build libraries for x86-64 only
    +			# 32-bit x86 deprecated
    +			V_LIB_CCOPT_FAT="-arch x86_64"
    +			V_LIB_LDFLAGS_FAT="-arch x86_64"
    +			;;
    +
     		darwin*)
     			#
     			# Post-Snow Leopard.  Build libraries for x86-64

**Comment by guyharris** [comment]
Yes, it's a duplicate.
