### ISSUE TITLE
--disable-rdma does not disable rdmasniff

### ISSUE THREAD

**Issue by ckb42** [the-tcpdump-group/libpcap#782]
1.9.0 

With configure, using --disable-rdma or --enable-rdma=no leaves the rdmasniff option enabled, when available.  Therefore libverbs is still required to link with libpcap.

Workaround is to pass --disable-rdmasniff to configure.

**Comment by guyharris** [comment]
Fixed in 8879aa1b58496ed4af3eb581c92d34fd80e4c6ae.
