### ISSUE TITLE
pcap-snf's read_op returns >=1 even if pcap_filter rejects the packet

### ISSUE THREAD

**Issue by jandos** [the-tcpdump-group/libpcap#783]
Looking at the code in pcap-snf.c(master branch), I noticed that function snf_read returns a value greater than or equal to 1, even if the packet gets rejected by pcap_filter:
https://github.com/the-tcpdump-group/libpcap/blob/cf7c3f5b17a33cff1e9ffd9b17377f857d017c7f/pcap-snf.c#L186

While other implementations like pcap-linux, return zero:
https://github.com/the-tcpdump-group/libpcap/blob/cf7c3f5b17a33cff1e9ffd9b17377f857d017c7f/pcap-linux.c#L2088

Are there any definitions of what read_op should return when pcap filter rejects the packet ?
I only managed to find this comment:
https://github.com/the-tcpdump-group/libpcap/blob/cf7c3f5b17a33cff1e9ffd9b17377f857d017c7f/pcap.c#L395

Thanks.

**Comment by guyharris** [comment]
Fixed in 8b40ffd344971073013aabe3c9c4a2db47ca7b43.
