### ISSUE TITLE
parallel make bug with 1.8.1. release

### ISSUE THREAD

**Issue by rofl0r** [the-tcpdump-group/libpcap#788]
using the following cpu, and more than one process (e.g. make -j2 or higher) the build breaks.
it seems the files generated by flex and bison are being consumed before they are written completely:

```
bison -y -p pcap_ -o grammar.c -d grammar.y
conflicts: 38 shift/reduce
flex -P pcap_ --header-file=scanner.h --nounput -o scanner.c scanner.l
...
./gen_version_c.sh ./VERSION version.c
./config.status --file=pcap-config.tmp:./pcap-config.in
In file included from grammar.y:78:0:
scanner.h:1:0: error: unterminated #ifndef
 #ifndef pcap_HEADER_H
 
gcc -fvisibility=hidden -fpic -D_GNU_SOURCE -D_BSD_SOURCE -DIPPROTO_HOPOPTS=0 -I/include/libnl-tiny -fdata-sections -ffunction-sections -Os -g0 -fno-unwind-tables -fno-asynchronous-unwind-tables -Wa,--noexecstack -mtune=generic -I.  -DBUILDING_PCAP -DHAVE_CONFIG_H  -D_U_="__attribute__((unused))" -D_GNU_SOURCE -D_BSD_SOURCE -DIPPROTO_HOPOPTS=0 -I/include/libnl-tiny -fdata-sections -ffunction-sections -Os -g0 -fno-unwind-tables -fno-asynchronous-unwind-tables -Wa,--noexecstack -mtune=generic    -c ./pcap.c
grammar.c: In function 'pcap_parse':
grammar.c:67:25: warning: implicit declaration of function 'pcap_lex' [-Wimplicit-function-declaration]
 #define yylex           pcap_lex
                         ^
grammar.c:1536:16: note: in expansion of macro 'yylex'
 # define YYLEX yylex (&yylval, yyscanner)
                ^~~~~
grammar.c:2193:16: note: in expansion of macro 'YYLEX'
       yychar = YYLEX;
                ^~~~~
make: *** [grammar.o] Error 1
```
full log: http://termbin.com/1tta http://termbin.com/ojtj

i've built this libpcap version dozens of times with 8 or more parallel processes and never had any issue, but it fails reproducibly on a PC using the following CPU:
`Intel(R) Core(TM) i5-3340M CPU @ 2.70GHz`

it's very likely that some makefile targets depend on scanner.c, scanner.h, grammar.c, but the dependencies are not properly documented (or the makefile target that produces them).

**Comment by guyharris** [comment]
We will not be updating the 1.8.x releases; does this still happen with 1.9.0, the current release?

**Comment by rofl0r** [comment]
i tried to compile 1.9.0 about 15x, worked every time (but the issue could still be lurking and just happen to work due to luck). i filed this only because the changelog of 1.9.0 doesn't indicate any related issues have been fixed.
