### ISSUE TITLE
neither pcap_close nor pcap_breakloop are predictable

### ISSUE THREAD

**Issue by guyharris** [the-tcpdump-group/libpcap#79]
Converted from [SourceForge issue 1575387](http://sourceforge.net/support/tracker.php?aid=1575387), submitted by frederich

pcap_close and pcap_breakloop wait for a packet to be 
received to effectively close or break the loop, if 
no packet arrives, pcap_dispatch will block forever

**Comment by infrastation** [comment]
(This comment is mainly for historic consistency.) As far as I understand, this behaviour had been improved in more modern versions of libpcap (around 1.5.x and onwards), in that setting the packet buffer timeout to a non-zero value allows to avoid blocking forever.

Closing.

**Comment by guyharris** [comment]
That's not necessarily the case for all operating systems, but 1) a signal should break out of the loop, so calling `pcap_dispatch()` in a signal handler should suffice and 2) if you want to call `pcap_dispatch()` from another thread, sending a signal to the capturing thread on UN*X should suffice.
