### ISSUE TITLE
Trying to cross compile libpcap for arping: multiple definition errors

### ISSUE THREAD

**Issue by JesusOsuna** [the-tcpdump-group/libpcap#811]
Hello, 

I am in the task of cross compiling Arping for host arm-none-linux-gnueabi, when trying to do that libnet and libpcap were required as dependencies so I did the follow: 

I download libpcap-1.9.0 and configure as follow:

./configure --build=x86_64-pc-linux-gnu --host=arm-none-linux-gnueabi --prefix=/home/uid32119/arping/libpcap-1.9.0/outp --disable-shared --enable-static

then make.

Now, when trying to cross compile arping again, I am receiving multiple declarations errors as:

arm-none-linux-gnueabi-gcc -DHAVE_CONFIG_H -I. -I..   -I/home/uid32119/arping/libnet-master/libnet/include -I/home/uid32119/arping/libpcap-1.9.0/pcap -D_DEFAULT_SOURCE=1  -g -O2 -MT arping.o -MD -MP -MF .deps/arping.Tpo -c -o arping.o arping.c
In file included from arping.c:111:0:
/home/uid32119/arping/libpcap-1.9.0/pcap/pcap.h:523:18: error: conflicting types for 'bpf_filter'
   PCAP_API u_int bpf_filter(const struct bpf_insn *, const u_char *, u_int, u_int);
                  ^
In file included from /home/uid32119/arping/libpcap-1.9.0/pcap/pcap.h:88:0,
                 from arping.c:111:
/home/uid32119/arping/libnet-master/libnet/include/bpf.h:260:14: note: previous declaration of 'bpf_filter' was here
 extern u_int bpf_filter(struct bpf_insn *, u_char *, u_int, u_int);
              ^
Makefile:613: recipe for target 'arping.o' failed

So I decided to comment /home/uid32119/arping/libpcap-1.9.0/pcap/pcap.h:523 as:
#if !defined(__NetBSD__) && !defined(__QNX__)
  // PCAP_API u_int        bpf_filter(const struct bpf_insn *, const u_char *, u_int, u_int);
#endif
 
But again, multiple declaration errors arrives: 

/home/uid32119/arping/libpcap-1.9.0/.libs/libpcap.a(pcap.o): In function `pcap_lookupdev':
/home/uid32119/arping/libpcap-1.9.0/./pcap.c:1258: multiple definition of `pcap_lookupdev'
mock_libpcap.o:/home/uid32119/arping/arping-arping-2.x/src/mock_libpcap.c:67: first defined here
/home/uid32119/arping/libpcap-1.9.0/.libs/libpcap.a(pcap.o): In function `pcap_dispatch':
/home/uid32119/arping/libpcap-1.9.0/./pcap.c:2564: multiple definition of `pcap_dispatch'
mock_libpcap.o:/home/uid32119/arping/arping-arping-2.x/src/mock_libpcap.c:21: first defined here
/
.
.
.
This is how I configured for Arping:
 ./configure --build=x86_64-pc-linux-gnu --host=arm-none-linux-gnueabi --prefix=/home/uid32119/arping/arping-arping-2.x/ LDFLAGS="-L/home/uid32119/arping/libnet-master/libnet/src/.libs -L/home/uid32119/arping/libpcap-1.9.0/.libs" CPPFLAGS="-I/home/uid32119/arping/libnet-master/libnet/include -I/home/uid32119/arping/libpcap-1.9.0"

/home/uid32119/arping/libpcap-1.9.0/.libs is just a folder I create to have libpcap.a by itself.

I feel like I am doing something wrong in configure step, maybe you are able to tell me if I am using wrong your library ? 

Best Regards!

PD: config.log from arping added
[config.log](https://github.com/the-tcpdump-group/libpcap/files/3009230/config.log)

**Comment by guyharris** [comment]
It appears that the only programs in arping that use `mock_libpcap.c` are `fuzz_pingip` and `arping_test`.

If arping's configuration script causes those programs to be linked with `mock_libpcap.o` *and* `-lpcap`, that's a bug in arping's configuration script, and you should report it to them.
