### ISSUE TITLE
pcap_sendpacket can not work

### ISSUE THREAD

**Issue by linj170309** [the-tcpdump-group/libpcap#812]
Hi guys,

I use the api pcap_sendpacket and pcap_open_live in my code, it can be work under centos, but not in ubuntu 16.04, which result as "send: Invalid argument",  thanks for advinac.

Here is my demo code:

#include <pcap.h>
#include <errno.h>
#include <string.h>

int main()
{
   int ret = 0;
   pcap_t *p; 
   char err[1024];

   p = pcap_open_live("eth4", 64 * 1024, 1, 5000, err);
   if(p == NULL)
   {
     printf("open error\n");
     return -1;
   }
   
   char d[] = "hello";
   
   ret = pcap_sendpacket(p, (const u_char *)d, sizeof(d));
 
  printf("result: %d, %d, %s, %s\n", ret, errno, strerror(errno), pcap_geterr(p)); 
   pcap_close(p);  
  return 0;
}

**Comment by gvanem** [comment]
I assume you get an `Invalid argument` because `sizeof(d)` is too small (for Ethernet).

**Comment by linj170309** [comment]
Thank you for your reply.   What is the length range of Ethernet ?

**Comment by gvanem** [comment]
60 - 1514 (except for jumbo-frames I think).

**Comment by linj170309** [comment]
Thanks for your replay,  I will close this issuse.

**Comment by guyharris** [comment]
And, as you're doing a pcap transmission on an Ethernet network, you have to transmit an Ethernet packet, which means you need to begin your packet with:

- a 6-octet Ethernet destination address (the Ethernet host to which you're transmitting the packet, or a multicast or broadcast address);
- a 6-octet Ethernet source address, which is the Ethernet address of the adapter on which you're transmitting the packet;
- a 2-octet type/length field.

You can't just stick "Hello" at the beginning of an Ethernet packet.

**Comment by linj170309** [comment]
Thank you very much , I understand. @guyharris
