### ISSUE TITLE
Any filter prevents packet capture

### ISSUE THREAD

**Issue by guyharris** [the-tcpdump-group/libpcap#82]
Converted from [SourceForge issue 1607214](http://sourceforge.net/support/tracker.php?aid=1607214), submitted by jdaily

This behavior is exhibited when using tcpdump (either locally or on another box after capturing data) and snort (locally), so I'm inclined to blame libpcap.

I've reproduced it with libpcap-0.8.3-10.RHEL4 (CentOS 4.3) and with tcpdump 3.9.5/libpcap 0.9.5 downloaded from tcpdump.org.

It only manifests itself on one of my three network interfaces, a PCI-E network card with no IP address (adding an IP address doesn't change the observed behavior) plugged into a switch port to which 2 other ports are mirrored.

Here's the dmesg output when the card is discovered on boot:
divert: allocating divert_blk for eth0
eth0: Tigon3 [partno(BCM95721A211F) rev 4101 PHY(5750)](PCI Express) 10/100/1000BaseT Ethernet 00:10:18:10:f8:91
eth0: RXcsums[1] LinkChgREG[0] MIirq[0] ASF[0] Split[0] WireSpeed[1] TSOcap[1] 
eth0: dma_rwctrl[76180000]

(The interface is later renamed to eth2.)
## The behavior itself

tcpdump runs fine, viewing all traffic, when no filter is applied.

When any filter is applied, no packets are displayed or reported as captured when tcpdump exits.

When snort runs, it also runs fine with no filters.  If run with a filter, it locks up and has to be killed with -9 to terminate.

If a file captured with the -w argument to tcpdump (3.8.2-10.RHEL4) and no filters is pulled down to another Linux box, tcpdump with any filter will result in no output.  ethereal has no problem applying its display filters.

I'd be happy to assist with identifying the cause of this in any way I can.

I regret that uploading a dump file is problematic, due to the sensitive nature of the environment.  If I could filter out specific traffic to upload...well, I wouldn't be reporting this in the first place.

**Comment by infrastation** [comment]
Closing as impossible to troubleshoot anymore.
