### ISSUE TITLE
Any plans to make new release?

### ISSUE THREAD

**Issue by kloczek** [the-tcpdump-group/libpcap#821]
I think that after almost year it would be good to make new release with new code base :)

**Comment by Oppen** [comment]
Not only the time (which now has surpassed the year), but there are several improvements.
I'd like it very much to have something 'approved' by upstream that includes DPDK support.
Are there any plans? Any way to help that happen?

**Comment by mcr** [comment]
A release went out last fall, and we are prepping for 1.10 now.

**Comment by guyharris** [comment]
[1.10.0 is now available](https://www.tcpdump.org/index.html#latest-releases).
