### ISSUE TITLE
Support mapping NdisMediumWirelessWan to DLT_RAW

### ISSUE THREAD

**Issue by bitbanditorg** [the-tcpdump-group/libpcap#824]
In Windows, if capturing on a Mobile Broadband interface the LinkType is reported as DLT_EN10MB (Ethernet) which is wrong since there is no ethernet header, packets show up as raw IP frames. This capture cannot be analyzed later since LinkType is wrong, packets appear as ethernet frames, although they are IP frames. It seems there is no support for NdisMediumWirelessWan in pcap_activate_npf(), the switch statement sets the linktype to default DLT_EN10MB. The fix for this issue could be the following:
 
case NdisMediumWirelessWan:
	p->linktype = DLT_RAW;
	break;

If the LinkType is changed in a capture file to DLT_RAW then it is possible to analyze that file. That proves linktype should be set to DLT_RAW in the first place.

According to this document, this is a new media type since Windows 7:
https://docs.microsoft.com/en-us/previous-versions/windows/hardware/design/dn642105(v=vs.85)

Quote from the document: "Windows 7 defines a new media type: NdisMediumWirelessWan. For this media type, NDIS sends raw IP frames directly to the miniport driver and expects the miniport driver to return raw IP frames. Raw IP frames are the same as Ethernet 802.3 frames except that the raw IP frame omits the Ethernet header and starts with the IP header."

Unfortunately, I cannot override the linktype when opening a live capture. pcap_set_datalink() refuses to set it to DLT_RAW, pcap_list_datalinks() reports only DLT_EN10MB. I suppose this falls into the "platform doesn't support changing the DLT for an interface" category.

**Comment by guyharris** [comment]
Platform *shouldn't* support changing the DLT for an interface; it should support giving the right DLT for the interface.  The way to support that is the change you indicate, with `#ifdef`s added to allow this to compile if `NdisMediumWirelessWan` isn't defined.

Fixed in 0209202888b596c807b63f6a45ba4e181fa8af02.
