### ISSUE TITLE
Missing libpcap.so (libpcap.a present)

### ISSUE THREAD

**Issue by porscheme** [the-tcpdump-group/libpcap#827]
To report a security issue please send an e-mail to security@tcpdump.org.

To report bugs and other problems, contribute patches, request a
feature, provide generic feedback etc please see the file
CONTRIBUTING in the libpcap source tree root.

**Comment by guyharris** [comment]
"Missing" in what circumstances?  Did you build from source either downloaded from the tcpdump.org Web site or checked out from GitHub?  If so, on what version of what OS did you do the build, and did you use autotools or CMake?

**Comment by porscheme** [comment]
I'm trying to compile the latest git repo code in a Debian linux docker container.
Compile seems to have finished successfully but I do not see libpcap.so file although libpcap.a

Below are my commands for compiling...

# update apt-get
apt-get update

# Enable sudo mode
su -

# install sudo
apt-get install sudo -y

# install various packages
sudo apt-get install build-essential -y
sudo apt-get install git -y
sudo apt-get install flex -y
sudo apt-get install bison -y

# go to src
cd /usr/src

# get latest from git
git clone https://github.com/the-tcpdump-group/libpcap

cd libpcap

# configure
./configure --prefix=/usr/local --disable-shared --disable-dbus --disable-bluetooth --disable-canusb

# make
make

**Comment by porscheme** [comment]
> "Missing" in what circumstances? Did you build from source either downloaded from the tcpdump.org Web site or checked out from GitHub? If so, on what version of what OS did you do the build, and did you use autotools or CMake?

I downloaded the code from Github
Used CMake (make) to compile.

See my previous POST for entire list of commands.

**Comment by guyharris** [comment]
> Used CMake (make) to compile.
> 
> See my previous POST for entire list of commands.

...which don't include [CMake](https://cmake.org), so you're not using CMake, but *do* include `./configure`, so you're using autotools (autoconf, etc.).

**Comment by porscheme** [comment]
Thanks for the explanation.
Does autotools (autoconf) produce libpcap.so ?

**Comment by guyharris** [comment]
Both the configure script and CMake produce Makefiles, not libpcap (.so or .a); CMake can also produce build files for other build tools, such as [Ninja](https://ninja-build.org).

The build tool runs commands, as specified by the build files; those commands produce the build output.  The Makefile produced by the autotools script should, on platforms where shared libraries have ".so" names (not all do - it's ".dylib" on macOS, for example), produce a file named "libpcap.so.{VER}", where "{VER}" is the contents of the `VERSION` file, so you won't get a file whose name is "libpcap.so", you'll get a file whose name is "libpcap.so.{VER}" for the appropriate value of "{VER}", e.g. "libpcap.so.1.10.0-PRE-GIT".

**Comment by fxlb** [comment]
`./configure` [...] `--disable-shared` ?

**Comment by porscheme** [comment]
Thanks again for the detailed explanation.


> `./configure` [...] `--disable-shared` ?

Yes, this fixed it.
Thanks

**Comment by guyharris** [comment]
> `./configure` [...] `--disable-shared` ?

That configuration option should *ensure* that there's no libpcap.so or libpcap.so.1 or libpcap.so.1.10.0-PRE-GIT - and, as long as there weren't any such files in the directory beforehand, it should, in fact, do so.

**Comment by guyharris** [comment]
> Thanks again for the detailed explanation.
> 
> > `./configure` [...] `--disable-shared` ?
> 
> Yes, this produced libpcap.so

I.e., when you *stopped* using `--disable-shared`, you got a libpcap.so file?

`--disable-shared` should ***NOT*** cause a libpcap.so to be built; it should *prevent* it from being built.  If it doesn't do so, that's a bug.

> But there are other files such as libpcap.so, libpcap.so.1, libpcap.so.1.10.0-PRE-GIT

The only one that the build process should put in the current directory is libpcap.so.1.10.0-PRE-GIT.

"make install" should install libpcap.so.1.10.0-PRE-GIT, and then make *symbolic links* named libpcap.so.1, pointing to libpcap.so.1.10.0-PRE-GIT, and libpcap.so, pointing to libpcap.so.1.  As those are all, in effect, the same library, as a result of the others being symbolic links that end up referring to libpcap.so.1.10.0-PRE-GIT, it shouldn't matter which one you "use" - you'd probably "use" them by linking with "-lpcap", in which case the linker will use whichever of the three names for the same file are appropriate.

> 
> Which of the above files I should use?

**Comment by fxlb** [comment]
> Are you asking whether they used that option?

Yes.

**Comment by Oppen** [comment]
> ./configure --prefix=/usr/local **--disable-shared** --disable-dbus --disable-bluetooth --disable-canusb
> 

> > Are you asking whether they used that option?
> 
> I ask why they use it (see a previous message).

So, @porscheme, what @fxlb points out is that it's the use of `--disable-shared` that causes the `libpcap.so` file to be missing.
Try running the same without it.

**Comment by infrastation** [comment]
Answers provided, no subsequent feedback, closing.
