### ISSUE TITLE
Some packets counted both as dropped and as read on Linux

### ISSUE THREAD

**Issue by Oppen** [the-tcpdump-group/libpcap#828]
`/proc/net/dev:rx_dropped` reflects **both** drops at L1/2 and drops at L3.
However, raw sockets see everything that make it to L2.
As a consequence, packets dropped because of congestion control or (in a case I stumbled upon on the wild) protocols unknown to the kernel, get counted both as received by the socket and as lost by ps_ifdrop.
There's a statistic more relevant, `rx_missed_errors`, accounting for packets the driver was unable to either read or pass on to the OS, but not all drivers implement it.
Luckily, we can use it through `SIOCETHTOOL` when supported, and fall back to `/proc/net/dev` otherwise.

I have half an implementation in my mind, but I wouldn't like to put the effort if it will be rejected in principle.
This doesn't mean I won't accept much needed criticism, but if the feature is not wanted at all it doesn't make much sense to implement it.

**Comment by guyharris** [comment]
Getting the driver's drop statistics, if the driver keeps them, is the right thing to do.

I'm not sure falling back on getting a drop count that includes network-layer drops is worth the effort; better to just provide 0 for now (and if we later add an API that uses [pcapng ISB option codes](http://xml2rfc.tools.ietf.org/cgi-bin/xml2rfc.cgi?url=https://raw.githubusercontent.com/pcapng/pcapng/master/draft-tuexen-opsawg-pcapng.xml&modeAsFormat=html/ascii&type=ascii#rfc.section.4.6) as keys, so that a program can ask for a set of statistics and may only get back some of them, not provide it at all).

Is `rx_missed_errors` available from sysfs as well?  There's a comment in `pcap-linux.c` that says

     * Grabs the number of dropped packets by the interface from /proc/net/dev.
     *
     * XXX - what about /sys/class/net/{interface name}/rx_*?  There are
     * individual devices giving, in ASCII, various rx_ and tx_ statistics.
     *                  
     * Or can we get them in binary form from netlink?

**Comment by Oppen** [comment]
The `ioctl` is to check for the feature.
You pass the command `ETHTOOL_GSSET_INFO` to get a set of strings, and `ETH_SS_STATS` as an argument to get the supported statistics.
If the string `"rx_missed_errors"` is present, then the statistic is available.
I think we should do this at context initialization time, and then read from `sysfs` if available.
The pseudo-file is always present regardless of support, so we can't rely on that for detection.
The [ethtool source code](https://kernel.googlesource.com/pub/scm/network/ethtool/ethtool/+/ethtool-3.4.y/ethtool.c#2746) can be used as a reference.

**Comment by Oppen** [comment]
Otherwise, the kernel initializes the stat to 0, so if it isn't supported reading from the will just return 0 due to the driver not updating it.

**Comment by sla89** [comment]
There is already an `ioctl` call to get timestamp capabilities using command `ETHTOOL_GET_TS_INFO`.
https://github.com/the-tcpdump-group/libpcap/blob/master/pcap-linux.c#L6747-L6749

**Comment by Oppen** [comment]
Any updates on this? Shall I proceed?

**Comment by guyharris** [comment]
> Any updates on this? Shall I proceed?

Go ahead!

**Comment by Oppen** [comment]
[Here's a preliminary commit.](https://github.com/Oppen/libpcap/commit/72248ffe93bae6978ba0db6b274a5aa4e909eb73)
There may be minor changes, since I haven't tested it yet, but not big, unless there are objections, of course.

**Comment by guyharris** [comment]
Fixed by #854.
