### ISSUE TITLE
Code cleanup

### ISSUE THREAD

**Issue by ValZapod** [the-tcpdump-group/libpcap#831]
https://github.com/the-tcpdump-group/libpcap/blob/dd0edaf7eb97c05aff6502056c1e5de9944eb209/pcap-linux.c#L1191
I suppose one does not need to check dropped_pkts, because dropped_pkts changes only once in this while (line 1220) and then immediately we have a `break` from this while.

https://github.com/the-tcpdump-group/libpcap/blob/dd0edaf7eb97c05aff6502056c1e5de9944eb209/pcap-linux.c#L1217
Wow. `while (*bufptr == ' ')` is enough I think

https://github.com/the-tcpdump-group/libpcap/blob/dd0edaf7eb97c05aff6502056c1e5de9944eb209/optimize.c#L2409
Nope. This is always false. As well as line 2430

https://github.com/the-tcpdump-group/libpcap/blob/dd0edaf7eb97c05aff6502056c1e5de9944eb209/optimize.c#L1986-L1989
What is this? I mean you can write just `return 0` insteed of return x == 0...

https://github.com/the-tcpdump-group/libpcap/blob/dd0edaf7eb97c05aff6502056c1e5de9944eb209/pcap-netfilter-linux.c#L217
Just `} else {` is enough, because type is enum which have only 3 possible values.

https://github.com/the-tcpdump-group/libpcap/blob/f61f8781a1fe29670886f30537adf85b0928330c/gencode.c#L2491
Why gen_load_radiotap_llprefixlen() is the same as gen_load_ppi_llprefixlen()?

https://github.com/the-tcpdump-group/libpcap/blob/dd0edaf7eb97c05aff6502056c1e5de9944eb209/pcap-usb-linux.c#L866
Can you do smth about this? I mean %x %d, so unsigned and than signed, while tag is signed and timestamp unsigned.

**Comment by guyharris** [comment]
> https://github.com/the-tcpdump-group/libpcap/blob/dd0edaf7eb97c05aff6502056c1e5de9944eb209/pcap-linux.c#L2723
> 
> 
> Do you really need this INSIDE the loop??

Given that `p` is advanced over the line in the inner loop, and thus is no longer guaranteed to point to the beginning of the line after the inner loop, yes, we really *do* need it inside the loop.

**Comment by guyharris** [comment]
> https://github.com/the-tcpdump-group/libpcap/blob/dd0edaf7eb97c05aff6502056c1e5de9944eb209/optimize.c#L2475
> 
> Why do you free a NULL?

Because 1) there's no guarantee that it's a null (it gets there from a `longjmp()` from code that might set it to a non-null value) and 2) `free()` is specified by the C standard as doing nothing if passed a null pointer, so there's no point in checking for a null pointer.

**Comment by ValZapod** [comment]
> checking for a null pointer.
Yeah, I know that at least.))

**Comment by ValZapod** [comment]
@guyharris Can you also check this one from tcpdump? https://github.com/the-tcpdump-group/tcpdump/issues/786
Thanks))

**Comment by guyharris** [comment]
> https://github.com/the-tcpdump-group/libpcap/blob/dd0edaf7eb97c05aff6502056c1e5de9944eb209/pcap-linux.c#L1191
> 
> I suppose one does not need to check dropped_pkts, because dropped_pkts changes only once in this while (line 1220) and then immediately we have a `break` from this while.
> https://github.com/the-tcpdump-group/libpcap/blob/dd0edaf7eb97c05aff6502056c1e5de9944eb209/pcap-linux.c#L1217
> 
> Wow. `while (*bufptr == ' ')` is enough I think

Those were addressed, along with some other issues, in 7d97bb23a7ecd40bde41385236b9dd5db167afc4.

But, given issue #828, perhaps that routine should simply be removed, and we should get the statistics from netlink instead.

**Comment by guyharris** [comment]
> https://github.com/the-tcpdump-group/libpcap/blob/dd0edaf7eb97c05aff6502056c1e5de9944eb209/optimize.c#L1986-L1989
> 
> What is this? I mean you can write just `return 0` insteed of return x == 0...

No, you can't.  `x` is not guaranteed to be 0 if `y` is 0, and *vice versa*.

**Comment by ValZapod** [comment]
> No, you can't. `x` is not guaranteed to be 0 if `y` is 0, and _vice versa_.
@guyharris But we already checked for x == 0. Were it 0, we would already returned from the function, no?

**Comment by ValZapod** [comment]
@guyharris Okay, I will close this... Though I still think that (see prev. comment). Also, maybe somebody can look into much bigger https://github.com/the-tcpdump-group/tcpdump/issues/786 
Thank you))
