### ISSUE TITLE
sparc64-unknown-linux-gnu needs -fPIC instead of -fpic

### ISSUE THREAD

**Issue by benkohler** [the-tcpdump-group/libpcap#837]
Hi,

I believe this sparc64 chost needs to be one that gets -fPIC instead of -fpic.  There is already a check in aclocal.m4 which sets fPIC for "sparc64*) freebsd*|openbsd*)", I think this should also apply on linux.

With -fpic as it is now, I get a lot of build errors like:

pcap-linux.c:(.text+0x3088): relocation truncated to fit: R_SPARC_GOT13 against symbol `pcap_setnonblock_fd' defined in .text section in pcap.o

What clued me in on the problem was this rather old ML thread where the same issue was reported & fixed for openbsd sparc64: https://seclists.org/tcpdump/2012/q4/112

**Comment by benkohler** [comment]
Debian seems to already be indirectly patching around the problem:

https://sources.debian.org/patches/libpcap/1.9.0-2/shared-lib.diff/

**Comment by benkohler** [comment]
--- a/aclocal.m4
+++ b/aclocal.m4
@@ -501,7 +501,7 @@ AC_DEFUN(AC_LBL_SHLIBS_INIT,
                    sparc64*)
                        case "$host_os" in

-                       freebsd*|openbsd*)
+                       freebsd*|linux*|openbsd*)
                            PIC_OPT=-fPIC
                            ;;
                        esac

**Comment by guyharris** [comment]
Fixed in 28c5f5a3271df15684b495554d465414dc2d02f9.
