### ISSUE TITLE
Legacy code for Linux

### ISSUE THREAD

**Issue by Oppen** [the-tcpdump-group/libpcap#853]
Reading through `pcap-linux.c` I found a lot of code is for handling ancient versions of Linux, as far back as 2.0.
I think a cleanup is due.
I suggest supporting only upstream supported versions, i.e., no older than [3.16](https://www.kernel.org/).
This means, for example, that we can assume TPACKET_V3 to be present.
I'd also like to prioritize run time feature checks over build time ones, and make them sooner (instance creation or activation) rather than later.
I'm stepping up for this task, unless the community opposes.

@guyharris should I ask this in the mail list instead?

**Comment by fenner** [comment]
Isn't TPACKET_V3 still subtly broken in 3.16?  da413eec729dae5dcb150e2eb34c5e7e5e4e1b49 didn't go in until 3.19
```
Subject: [PATCH] packet: Fixed TPACKET V3 to signal poll when block is closed
 rather than every packet
```
which would cause packet loss if packets arrive at very low rates.

**Comment by Oppen** [comment]
That doesn't mean it isn't present, so we can expect it at build time.
We can fall back to TPACKET V2 on those cases, but still have only one build.
We can also stop supporting the legacy SOCK_PACKET socket.

**Comment by Oppen** [comment]
I'll go further and check if that was backported, too, just in case.

**Comment by guyharris** [comment]
> @guyharris should I ask this in the mail list instead?

Possibly, for the same reasons that applied for the new buffer-size setting API.

**Comment by Oppen** [comment]
OK, I made sure it isn't ported.

**Comment by guyharris** [comment]
> Isn't TPACKET_V3 still subtly broken in 3.16?

Yes, but libpcap has code to work around that, so we can still use it.

**Comment by guyharris** [comment]
@Oppen Is there anything left to remove?

**Comment by infrastation** [comment]
Linux kernel version requirement was bumped to 2.6.17 in February 2020 (commit 7c78bcb via pull request #904) with a few follow-up changes. If this does not address this request sufficiently, please explain. Otherwise this request will be closed in 7 days.

**Comment by Oppen** [comment]
Long term is already far past 3.19 (the release that fixes the subtle break). Would it make sense to:
1. Require TPACKET_V3 now, and drop TPACKET_V2?
2. Remove the workaround from mainline?

Sorry for not answering before. I no longer had access to a Linux box due to a switch of jobs (I was using the work laptop back then) and I simply didn't remember to check on this when I bought my own.
I'm not 100% I'll be able to put time into this soon, but we can close the issue and I'll just send a PR whenever I can :)

**Comment by guyharris** [comment]
> Require TPACKET_V3 now, and drop TPACKET_V2?

Is there a way to configure a TPACKET_V3 buffer so that a wakeup occurs as soon as the *first* packet arrives?

If not, we continue to need to the TPACKET_V2 code to implement "immediate mode", as we do now.

**Comment by Oppen** [comment]
Ohhh, we did have that talk and the answer was not (as far as I could see). I forgot, sorry.

**Comment by infrastation** [comment]
It is time.
