### ISSUE TITLE
Enhancement: BPF code should show negative offsets symbolically

### ISSUE THREAD

**Issue by cjmaynard** [the-tcpdump-group/libpcap#861]
Recently a [Wireshark bug report](https://bugs.wireshark.org/bugzilla/show_bug.cgi?id=16116) was filed having to do with vlan capture filters where I learned about the special negative offsets such as -4048 and -4052 to represent the skbuff fields, vlan_present and vlan_tci, respectively.

In an attempt to learn more about these fields, I came across [bpfc](http://man7.org/linux/man-pages/man8/bpfc.8.html) and noticed that instead of using negative offsets, they use symbolic names for these fields instead.  For example: #vlanp, vlanp, #vlant, vlant, #vlan_tci, vlan_tci.

I suggested that it might be nice if libpcap also used symbolic names for the vlan-related offsets, and it was suggested to open a bug report here for this, not only for the vlan-related fields, but for all fields with negative offsets (#len, len, #pktlen, pktlen ...).  This bug is therefore being opened as suggested.

**Comment by guyharris** [comment]
- SKF_AD_PROTOCOL -> "proto"
- SKF_AD_PKTTYPE  -> "type"
- SKF_AD_IFINDEX -> "ifidx"
- SKF_AD_NLATTR -> "nla"
- SKF_AD_NLATTR_NEST -> "nlan"
- SKF_AD_MARK -> "mark"
- SKF_AD_QUEUE -> "queue"
- SKF_AD_HATYPE -> "hatype"
- SKF_AD_RXHASH -> "rxhash"
- SKF_AD_CPU -> "cpu"
- SKF_AD_ALU_XOR_X -> ???
- SKF_AD_VLAN_TAG -> "vlan_tci" or "vlant"
- SKF_AD_VLAN_TAG_PRESENT -> "vlanp"
- SKF_AD_PAY_OFFSET -> "poff"
- SKF_AD_RANDOM -> ???
- SKF_AD_VLAN_TPID -> ???

The above are the ones supported by bpfc, with ??? being ones that aren't.

**Comment by guyharris** [comment]
OK, so those would be used for:

- offsets in loads with the [k] address mode;
- perhaps immediate loads into the X register.

**Comment by guyharris** [comment]
> OK, so those would be used for:
> 
> * offsets in loads with the [k] address mode;
> * perhaps immediate loads into the X register.

No, just the first of those, as absolute loads into the A register are the only ones where the offsets are magic.

**Comment by guyharris** [comment]
OK, that should handle it; it's in the master branch, but not the 1.9.x branch.
