### ISSUE TITLE
corrupt files

### ISSUE THREAD

**Issue by guyharris** [the-tcpdump-group/libpcap#87]
Converted from [SourceForge issue 1655481](http://sourceforge.net/support/tracker.php?aid=1655481), submitted by cviecco

As part of a research project we have collected GBs of pcap data. This data is collected from TCPdump and is collected via tens of hosts. We have seen errors on the files generated from many of those hosts and in older historic data. Checking that we noticed that libpcap does not check the return value for fwrite when writing packets.

It is our impression that that is one of the core reasons for our corrupted pcap data. We also notice that you have explicitly marked above the code (line 1231 on savefile.c):
  /\* XXX we should check the return status */

Are you plannig to add such check or that lack of checking is a design decision/tradeoff?

Camilo Viecco

**Comment by pspacek** [comment]
Is there a new API which addresses this problem? I was just bitten by this (again) and I wonder how to proceed.

If the new API is not available, would it be possible to leave this issue open, possibly renamed to something like "write errors are not reported" to make people more aware of this?

Thank you.
