### ISSUE TITLE
Tcpdump on macOS -Qout / pcap_setdirection() failed: Setting direction to PCAP_D_OUT

### ISSUE THREAD

**Issue by ghost** [the-tcpdump-group/libpcap#875]
I need the to filter for only outgoing packages of a specific port. Apparently Apple removed it in its own version of Tcpdump/libpcap.

```
tcpdump -Qout -nnSX -c 10 -w packet.pcap port XXXX
tcpdump: cannot parse term at: 
tcpdump: invalid expression "out"
```

I successfully compiled Tcpdump 4.9.3 on macOS but im getting another error:

```
tcpdump --version
tcpdump version 4.9.3
libpcap version 1.8.1 -- Apple version 79.250.1
tcpdump --direction=out -nnSX -c 10 -w packet.pcap port XXXX
tcpdump: en0: pcap_setdirection() failed: Setting direction to PCAP_D_OUT is not supported on BPF
```

When trying to build libpcap 1.9.0 im getting this:

```
clang: error: linker command failed with exit code 1 (use -v to see     
invocation)
make: *** [libpcap.dylib] Error 1
```

**Comment by infrastation** [comment]
I do not know whether packet direction setting works in macOS at all (regardless of what software tries to set it), but on Linux `tcpdump outbound` gives the same results as `tcpdump -Q out`. Does that solve your problem?

**Comment by infrastation** [comment]
Closing do to the lack of feedback.
