### ISSUE TITLE
DLT_RAW returns no packets on macOS

### ISSUE THREAD

**Issue by ghazel** [the-tcpdump-group/libpcap#890]
Using datalink `DLT_RAW` on macOS does not return any packets. The default mode, `DLT_EN10MB`, does. Example:

output:
```
using en0 (libpcap version 1.8.1 -- Apple version 89.40.2)
Jacked a packet 0x0 with length of [1,124293120]
```

```c
#include <pcap.h>
#include <stdio.h>

int main(int argc, char *argv[])
{
    pcap_t *handle;            /* Session handle */
    char *dev;            /* The device to sniff on */
    char errbuf[PCAP_ERRBUF_SIZE];    /* Error string */
    struct pcap_pkthdr header;    /* The header that pcap gives us */
    const u_char *packet;        /* The actual packet */

    /* Define the device */
    dev = pcap_lookupdev(errbuf);
    if (dev == NULL) {
        fprintf(stderr, "Couldn't find default device: %s\n", errbuf);
        return(2);
    }
    printf("using %s (%s)\n", dev, pcap_lib_version());
    /* Open the session in promiscuous mode */
    handle = pcap_open_live(dev, BUFSIZ, 1, 1000, errbuf);
    if (handle == NULL) {
        fprintf(stderr, "Couldn't open device %s: %s\n", dev, errbuf);
        return(2);
    }
    if (pcap_set_datalink(handle, DLT_RAW)) {
        fprintf(stderr, "Couldn't set datalink on %s to DLT_RAW\n", dev);
        return(2);
    }
    /* Grab a packet */
    packet = pcap_next(handle, &header);
    /* Print its length */
    printf("Jacked a packet %p with length of [%d,%d]\n", packet, header.len, header.caplen);
    /* And close the session */
    pcap_close(handle);
    return(0);
}
```

**Comment by guyharris** [comment]
That's a macOS bug, not a libpcap bug; I can reproduce it with a program that directly opens a BPF device, binds it to an interface, optionally sets the link-layer header type to DLT_RAW, and starts capturing; if I capture on en0, and leave the link-layer header type alone, it shows packets, but if I set the link-layer header type to DLT_RAW, it shows no packets.

**Comment by guyharris** [comment]
I've filed a bug on this with Apple.  You may want to do so as well; the more bug reports on a problem, the higher priority it gets.

**Comment by ghazel** [comment]
https://openradar.appspot.com/7479566

**Comment by fxlb** [comment]
@ghazel 
"There is no information in Open Radar for issue number 7479566"

**Comment by ghazel** [comment]
Link typo. Fixed: https://openradar.appspot.com/57479566

**Comment by guyharris** [comment]
So how did you get the Radar number?  Did you submit this through Feedback Assistant or did you use the old --RadarWeb--bugreport.apple.com?

**Comment by ghazel** [comment]
bugreport.apple.com

**Comment by guyharris** [comment]
> bugreport.apple.com

As in "the old Apple Bug Reporter" or as in "it now redirects to https://feedbackassistant.apple.com/welcome, so I used Feedback Assistant"?

If the former, how did you manage to get there?

**Comment by ghazel** [comment]
> > bugreport.apple.com
> 
> As in "the old Apple Bug Reporter" or as in "it now redirects to https://feedbackassistant.apple.com/welcome, so I used Feedback Assistant"?

It now redirects.
