### ISSUE TITLE
Libpcap compilation issue on xcode11

### ISSUE THREAD

**Issue by aouinizied** [the-tcpdump-group/libpcap#892]
There is an issue with xcode11.x.
Seems to compile to 32 bits and generate a lot of misalignment issues.

BR

**Comment by guyharris** [comment]
> There is an issue with xcode11.x.
> Seems to compile to 32 bits

32-bits *only*, or 32-bit/64-bit fat?

On what version of macOS are you compiling?

Did you use autotools or CMake?

> and generate a lot of misalignment issues.

"Misalignment issues" in what sense?

**Comment by infrastation** [comment]
Closing due to no feedback.
