### ISSUE TITLE
Invalid IPv4 addresses are not an error and are accepted

### ISSUE THREAD

**Issue by cschuber** [the-tcpdump-group/libpcap#893]
The following should produce an error:

tcpdump -i lagg0 net 999.999.999.999

It does not. Verified with the same result on FreeBSD 13 (base and ports) and on RHEL 7.7. This was discovered at $JOB on a RHEL 7.7 server yesterday. I tested this on my FreeBSD laptop, which behaves the same as on RHEL.

**Comment by guyharris** [comment]
Should be fixed in 907070918d5e81a515315b395f334e52589fe0fb.
