### ISSUE TITLE
DLT_SUNATM_UNTRUNCATED

### ISSUE THREAD

**Issue by guyharris** [the-tcpdump-group/libpcap#90]
Converted from [SourceForge issue 1680573](http://sourceforge.net/support/tracker.php?aid=1680573), submitted by joao_fonseca

I'm working on a project using an Endace ATM capture card, and Wireshark to process the captured data.

Endace has a proprietary capture file format - ERF - and Wireshark is able to read it directly. However, when using some of its tools - mergecap, editcap or using pipes to feed the captures into tshark and
wireshark - they automatically convert the ERF stream to libpcap format.

These tools convert to libpcap using DLT_SUNATM, because it's the only available format for ATM that retains some header information. But, as I understand, DLT_SUNATM truncates AAL5 reassembled frames, leaving out the AAL5 trailer. The ATM dissector is not working properly because of this.

Wireshark has its own encapsulation types and maps DLT_SUNATM to WTAP_ENCAP_ATM_PDUS. It also has a WTAP_ENCAP_ATM_PDUS_UNTRUNCATED encapsulation type, which is the same format but leaving in the AAL5 trailer, however there is no available equivalent DLT_\* type in libpcap.

Could you please create a DLT_SUNATM_UNTRUNCATED network type? This would enable Wireshark to fix their ERF->libpcap functions, retaining all AAL5 information in the converted file.

**Comment by infrastation** [comment]
As far as the problem description goes, `DLT_SUNATM` does not include as much information as the original requestor wanted, The request to design a better suited DLT was made on 2007-03-14. I am going to close this issue in 7 days unless there is a volunteer to revive it.
