### ISSUE TITLE
CMake generate libpcap.pc miss ${exec_prefix}/lib64 for libdir field on CentOS

### ISSUE THREAD

**Issue by JackLiar** [the-tcpdump-group/libpcap#902]
libpcap version: 1.9.1
operating system: CentOS7
configure flags:
```cmake
-D CMAKE_BUILD_TYPE=Release
-D BUILD_SHARED_LIBS=ON
-D DISABLE_DAG=ON
-D DISABLE_SNF=ON
-D DISABLE_TC=ON
-D CMAKE_POSITION_INDEPENDENT_CODE=ON
-D CMAKE_INSTALL_PREFIX=/home/user/code/project/build/install
```

using these cmake parameters, we get a libpcap.pc file likse this:
```pkg-config
#
# pkg-config file for libpcap.
#
# These variables come from the configure script, so includedir and
# libdir may be defined in terms of prefix and exec_prefix, so the
# latter must be defined as well.
#
prefix="/home/user/code/project/build/install"
exec_prefix="${prefix}"
includedir="${prefix}/include"
libdir="${exec_prefix}/lib"

Name: libpcap
Description: Platform-independent network traffic capture library
Version: 1.9.1
Libs: -L${libdir} -lpcap
Libs.private:
Cflags: -I${includedir}
```

But on RedHat/CentOS/Fedora system, all the libpcap.so library files are installed into a **lib64** directory, that is because the **GNUInstallDirs** CMake internal module automatically sets **CMAKE_INSTALL_FULL_LIBDIR** as lib64 ended

So it would be good to change the CMakeLists.txt file's 2603 line to:
```cmake
set(libdir "\${exec_prefix}/${CMAKE_INSTALL_LIBDIR}")
```

For a more robust build config, maybe we should replace all the lib/lib64 in linux config with ${CMAKE_INSTALL_LIBDIR}

**Comment by guyharris** [comment]
Should be fixed by 042466f905bac363f6ceeb4e09e3383a77027d3b.
