### ISSUE TITLE
[Generic Support] Sniff sensitivity on different WLAN type "data", "ctl" and "mgt"

### ISSUE THREAD

**Issue by Texas-C** [the-tcpdump-group/libpcap#909]
Hi~ 

I find that pcap's senstivity "seems" different on type `data`, `ctl` and `mgt`. (Ubuntu + RTL8812AU, I don't know is it just a exception cause my enviroment?)

For example: There is a device keep uploading & downloading data through WiFi. I'd like to find it.

When set filter as `wlan type ctl` or `wlan type mgt`. Sniffer seems coud catch more package than sniff with filter `wlan type data`.

So, I have a little question: is it a feature that "data" package is "hard" to catch than other type of packages? So sniffer is more sensitive on "control" and "management" pack?

**Comment by guyharris** [comment]
What happens when you sniff *without* a `wlan type` filter?  Do you see any data packets?  If so, do you see more control or management frames than data frames?

**Comment by Texas-C** [comment]
Thx for your reply

Yes, sniffing without `wlan type` would see more `control` or `management` frames.

**Comment by guyharris** [comment]
> Thx for your reply
> 
> Yes, sniffing without `wlan type` would see more `control` or `management` frames.

But you are seeing *some* data frames, right?  Do you see them with `wlan type data` as well?

**Comment by Texas-C** [comment]
Yes, I could see some data frames in both situations. It just seems less than `control` and `management`.

**Comment by guyharris** [comment]
I just did a capture here, and it got 108 data frames, 391 management frames, and 79 control frames; there are, for example, a *LOT* of beacon frames, many from our own access point.

For control frames, there aren't as many as there are data frames, but there *are* a lot of acknowledgment and RTS frames.

So, at least for management frames, it may just be that you're getting flooded with beacons, so that there are more management frames than data frames.

**Comment by Texas-C** [comment]
Thx

I did a 10mintues capture. Got 179 data frames, 7194 management frames, 2904 control frames.
Em.. control frames seems much more than data frames. I don't know why.

And I find another things that data packets seems hard to catch. I mean when device is sending data, sniffer couldn't detect the data frames on time.

**Comment by guyharris** [comment]
> I did a 10mintues capture. Got 179 data frames, 7194 management frames, 2904 control frames.
> Em.. control frames seems much more than data frames. I don't know why.

Are most of the management frames beacons?  If so, then you're in an area with noisy networks (as in "the AP sends out lots of beacons"), and perhaps lots of noisy networks.

What are the numbers of various types of control frames?

> And I find another things that data packets seems hard to catch. I mean when device is sending data, sniffer couldn't detect the data frames on time.

So the sniffer *does* detect them, it just detects them after the fact?

**Comment by Texas-C** [comment]
> Are most of the management frames beacons? If so, then you're in an area with noisy networks (as in "the AP sends out lots of beacons"), and perhaps lots of noisy networks.

Yep, most of them are beacons.

> What are the numbers of various types of control frames?

Most of control frames are RTS/CTS.

> So the sniffer does detect them, it just detects them after the fact?

Sometimes sniffer could't detect them. most of times sniffer detects them with latency (after the fact).

Thx

**Comment by guyharris** [comment]
> > Are most of the management frames beacons? If so, then you're in an area with noisy networks (as in "the AP sends out lots of beacons"), and perhaps lots of noisy networks.
> 
> Yep, most of them are beacons.

So probably just a lot of "hi, I'm a Wi-Fi network!" announcements.  Nothing peculiar here.

> > What are the numbers of various types of control frames?
> 
> Most of control frames are RTS/CTS.

See, for example, [Troubleshooting RTS/CTS](https://community.arubanetworks.com/t5/Wireless-Access/Troubleshooting-RTS-CTS/td-p/151092) on Aruba Networks' community site.

> > So the sniffer does detect them, it just detects them after the fact?
> 
> Sometimes sniffer could't detect them. most of times sniffer detects them with latency (after the fact).

So where are you getting the "when they're sent" time stamps to determine that they're captured after they're sent?

**Comment by Texas-C** [comment]
Thx~

> So where are you getting the "when they're sent" time stamps to determine that they're captured after they're sent?

Em.. I used a crude way to test it: turn on/off a deivce's plane mode while the device is transimiting data(device's MAC address already knowed), and check it with `wireshark` or `tcpdump`.

**Comment by guyharris** [comment]
> Em.. I used a crude way to test it: turn on/off a deivce's plane mode while the device is transimiting data(device's MAC address already knowed), and check it with `wireshark` or `tcpdump`.

You're not assuming that the packet is transmitted the instant after you turn airplane mode off, are you?  That's not necessarily the case.

(And if the sniffer doesn't detect the packet at all, perhaps it wasn't sent in the first place....)

**Comment by Texas-C** [comment]
Thx so much! xD
