### ISSUE TITLE
More frequent releases please

### ISSUE THREAD

**Issue by kloczek** [the-tcpdump-group/libpcap#911]
Since 1.9.1 already in git is committed more than 760 patches.

With quite high flow of new changes probably it would be way better to make a bit more frequent releases to have better regression about which change caused some issues.

Please consider change current release methodology :)

Thx

**Comment by chmorgan** [comment]
@guyharris anything we as users and non-libpcap devs but interested parties can do to help ease the release of a newer version?

There are a number of users of sharppcap that are moving to .net core implementations that lack the ability to send signals (the hacky way that I'm interrupting the pcap dispatch loop today) that would be impacted positively by the breakloop improvements.

**Comment by mcr** [comment]
Chris Morgan <notifications@github.com> wrote:
    > @guyharris anything we as users and non-libpcap devs but interested
    > parties can do to help ease the release of a newer version?

    > There are a number of users of sharppcap that are moving to .net core
    > implementations that lack the ability to send signals (the hacky way
    > that I'm interrupting the pcap dispatch loop today) that would be
    > impacted positively by the breakloop improvements.

Hi, a release was planned for March.
I failed to get it started this week, but it's still on Thursday at 11pm.
I anticipate starting RSN.

**Comment by guyharris** [comment]
[1.10.0 is now available](https://www.tcpdump.org/index.html#latest-releases).

**Comment by chmorgan** [comment]
This is great news! It means we can remove a bunch of code from sharppcap :-)

**Comment by guyharris** [comment]
> This is great news! It means we can remove a bunch of code from sharppcap :-)

Note that Npcap hasn't yet picked up libpcap 1.10; I filed issue nmap/npcap#276 to let them know it's available.
