### ISSUE TITLE
heap-buffer-overflow in find_dom()

### ISSUE THREAD

**Issue by ltx2018** [the-tcpdump-group/libpcap#929]
found by fuzzing libpcap-master
![image](https://user-images.githubusercontent.com/50396812/81268117-1b7fed80-907a-11ea-8f95-9d4d3d998394.png)

it was caused by integer overflow in opt_init:
![image](https://user-images.githubusercontent.com/50396812/81268922-2be49800-907b-11ea-9300-e38fce0e5923.png)
opt_state->space size here is less than (opt_state->n_blocks * opt_state->nodewords)

maybe #930  can fix it

**Comment by guyharris** [comment]
Should be addressed by 119b90af867f3073c571ee333fd47dcd0dbccd3a, which incorporates the changes from #930, as well as some other overflow checks.

So what was the filter expression that caused the control flow graph to be *that* large?
