### ISSUE TITLE
CMake configuration with BUILD_SHARED_LIBS=OFF creates a malformed pkg-config file

### ISSUE THREAD

**Issue by traversaro** [the-tcpdump-group/libpcap#931]
In particular, the `libpcap.pc` contains the following malformed line:
~~~
Libs: -L${libdir} -l
~~~

To reproduce the issue: 
~~~
git clone https://github.com/the-tcpdump-group/libpcap
cd libpcap
mkdir build
cd build
cmake -DBUILD_SHARED_LIBS:BOOL=OFF ..
cat libpcap.pc
~~~

**Comment by traversaro** [comment]
The problem seems to be due to https://github.com/the-tcpdump-group/libpcap/blob/libpcap-1.9.1/CMakeLists.txt#L2309 .

**Comment by guyharris** [comment]
Not Linux-specific - I reproduced it on macOS.

**Comment by guyharris** [comment]
Removing the `unset()` gives

    CMake Error at CMakeLists.txt:2608 (install):
      install TARGETS given target "pcap" which does not exist in this directory.

so more work is needed.

**Comment by guyharris** [comment]
Doesn't seem to happen on 1.10.

**Comment by guyharris** [comment]
Duplicate of #1009
