### ISSUE TITLE
configure option --with-dag-includes does not work

### ISSUE THREAD

**Issue by nilsrennebarth** [the-tcpdump-group/libpcap#932]
What happens is, that during the configure run the corresponding -I<directory> option is not passed to gcc when the autoconf testfile conftest.c is compiled. The "configure" thus fails, complaining that the header file dagapi.h can not be found in path given as argument to --with-dag-includes.

**Comment by guyharris** [comment]
That should be fixed by 83842505386fcb1b37308c8508f0078ca7c6081f.

So:

1. Is there a need to separately set the include and library path, or would `--with-dag=`''top_level_directory'' suffice?

1. Does configuring with CMake also find the DAG software?

1. On what platform are you building this?

**Comment by nilsrennebarth** [comment]
Thanks. I actually worked out a similar fix but that took a great deal of
time, having almost no autoconf knowledge.
To answer your questions:
 1. --with-dag would not suffice in my case: My build process unpacks
debian debs of the dag libs into a temporary location. It runs in a
container so it can't install to the system location. So the libs go to
/some/path/usr/lib/x86_64-linux-gnu and the includes to
/some/path/usr/include
2. Sorry, I didn't try cmake
3. Debian buster


Am Fr., 15. Mai 2020 um 02:15 Uhr schrieb Guy Harris <
notifications@github.com>:

**Comment by guyharris** [comment]
Change f95f189f4f45f3a96a4599610f183a6ea3720b65 tries to handle multiarch; see if it's sufficient to make `--with-dag=` work.

I think CMake *might* have some built-in understanding of multiarch.
