### ISSUE TITLE
Publish new release for libpcap

### ISSUE THREAD

**Issue by paramikoooo** [the-tcpdump-group/libpcap#939]
There are over than 1000 commits from las release (1.19.1)
When I want to use libpcap in my system , should I need to take the last release or take the master?

When will you publish new release?

**Comment by dvzrv** [comment]
@mcr is https://github.com/the-tcpdump-group/libpcap/releases/tag/libpcap-1.10.0-bp actually a stable release?

It would indeed be very great to have a new release.

**Comment by mcr** [comment]
David Runge <notifications@github.com> wrote:
    > @mcr is
    > https://github.com/the-tcpdump-group/libpcap/releases/tag/libpcap-1.10.0-bp
    > actually a stable release?

Not yet.

**Comment by guyharris** [comment]
[1.10.0 is now available](https://www.tcpdump.org/index.html#latest-releases).
