### ISSUE TITLE
Call PacketSetSnapLen() in pcap-npf.c for non-DAG cards

### ISSUE THREAD

**Issue by dmiller-nmap** [the-tcpdump-group/libpcap#947]
As described in [this bug on Npcap](https://github.com/nmap/npcap/issues/201), Npcap/WinPcap implementation of snaplen is currently dependent on libpcap functions being called in a particular order. We would like to fix this by actually implementing a native "snaplen" config functionality, but we need libpcap to call it in order for it to be useful. Right now, `PacketSetSnapLen()` does nothing on non-DAG cards, so libpcap does not call it. I have a PR incoming that will address this issue.

**Comment by guyharris** [comment]
That might not be necessary; see my comment on issue nmap/npcap/#201; we might just be able to set an "accept all" filter as we do in `pcap-bpf.c`.

**Comment by guyharris** [comment]
OK, so presumably this issue is fixed now.
