### ISSUE TITLE
pcap_dump_open() mode of operation

### ISSUE THREAD

**Issue by oneeyeman1** [the-tcpdump-group/libpcap#950]
Hi, ALL,

I have a small request.

Would it be possible to document whether pcap_open_offline() call opens the file in the "append" or overwrite" mode?

Thank you.

**Comment by guyharris** [comment]
OK, I've updated the documentation to indicate that `pcap_dump_open()` opens for *overwriting*.

`pcap_dump_open_append()` opens for appending.

**Comment by guyharris** [comment]
> Hi,
> 
> > `pcap_open_offline()` opens the file _for reading_, so it's _neither_ in append _nor_ overwrite mode, it's in _read-only_ mode.
> > Presumably you're thinking of `pcap_dump_open()`.
> 
> Oops - yes, sorry!
> But it looks like its documented as "open for appending:
> 
> [quote]
> pcap_dump_fopen() is called to write data to an existing open stream fp;
> [/quote]
> 
> Am I right?

No.

"Existing open stream" means an existing open `FILE *`; that's something that would already have been opened with, for example, `fopen()`.  The documentation now clarifies that it is expected to be a `FILE *` for a file that has been newly created, or truncated, by, for example, `fopen("file.pcap", "w")`.
