### ISSUE TITLE
Configuring --with-libnl=path doesn't work as expected

### ISSUE THREAD

**Issue by m00k12** [the-tcpdump-group/libpcap#952]
The configure script can helpfully take `--with-libnl=yes|no|<path>`.

When a path is specified, it is used as a basis for include and library paths (if pkgconfig is not being used).

Unfortunately the path that is added for -L library search at [configure.ac:899](https://github.com/the-tcpdump-group/libpcap/blob/master/configure.ac#L899) has .libs on the end:

`libnldir=-L${withval}/lib/.libs`

I'm not sure where the `.libs` comes from, but I can't find any libnl versions that install to such a place - it looks erroneous to me, and stops libpcap being successfully configured with libnl in this way.

Also later at [configure.ac:918](https://github.com/the-tcpdump-group/libpcap/blob/master/configure.ac#L918) there is a test to see if  `x$with_libnl = xyes` to then produce an error if libnl was not found.  I think it would be more useful to convert the test to ` x$with_libnl != xno` so that the configure will additionally fail if an explicit path for libnl was given, but libnl was not found or could not be used.

Thanks for the recent changes to use pkgconfig - that will help many people too.

**Comment by guyharris** [comment]
> The configure script can helpfully take `--with-libnl=yes|no|<path>`.
> 
> When a path is specified, it is used as a basis for include and library paths (if pkgconfig is not being used).
> 
> Unfortunately the path that is added for -L library search at [configure.ac:899](https://github.com/the-tcpdump-group/libpcap/blob/master/configure.ac#L899) has .libs on the end:
> 
> `libnldir=-L${withval}/lib/.libs`
> 
> I'm not sure where the `.libs` comes from, but I can't find any libnl versions that install to such a place - it looks erroneous to me, and stops libpcap being successfully configured with libnl in this way.

As per my comment in commit 1b5e454310d1de44bc985d62290bf72af17a62b8, I think that's some sort of libtool thing; I remember it from ages ago, when Wireshark used autotools including libtool, and Wireshark's shared libraries were getting built into .libs subdirectories.  They didn't get *installed* there, however, so the .libs at the end only works if you're pointing the configure script at a build directory.

**Comment by guyharris** [comment]
Both issues addressed.
