### ISSUE TITLE
getting ip source/address from packet and sending it to nDPI

### ISSUE THREAD

**Issue by Tomasz158** [the-tcpdump-group/libpcap#956]
Good Evening,
can anyone guide me (tutorial is not helping me much) how can I read the source ip address, destination ip address from a live capture and send it for processing to ndpi?

**Comment by infrastation** [comment]
Should be something along these lines:
1. Figure out the DLT number of the capture with [pcap_datalink()](http://www.tcpdump.org/manpages/pcap_datalink.3pcap.html).
2. Figure out the DLT structure for the number using [this](http://www.tcpdump.org/linktypes.html) as the starting point.
3. Figure out the DLT-specific offset(s) to skip to get to the beginning of the IPv4/IPv6 header.
4. Access the source and the destination address according to the IPv4/IPv6 header.

**Comment by guyharris** [comment]
> Should be something along these lines:
> 
> 1. Figure out the DLT number of the capture with [pcap_datalink()](http://www.tcpdump.org/manpages/pcap_datalink.3pcap.html).
> 2. Figure out the DLT structure for the number using [this](http://www.tcpdump.org/linktypes.html) as the starting point.
> 3. Figure out the DLT-specific offset(s) to skip to get to the beginning of the IPv4/IPv6 header.

And the DLT-specific field to determine whether the packet is IPv4, IPv6, or something else (for example, the Ethernet type/length field for DLT_EN10MB).

**Comment by guyharris** [comment]
> > Should be something along these lines:
> > 
> > 1. Figure out the DLT number of the capture with [pcap_datalink()](http://www.tcpdump.org/manpages/pcap_datalink.3pcap.html).
> > 2. Figure out the DLT structure for the number using [this](http://www.tcpdump.org/linktypes.html) as the starting point.
> > 3. Figure out the DLT-specific offset(s) to skip to get to the beginning of the IPv4/IPv6 header.
> 
> And the DLT-specific field to determine whether the packet is IPv4, IPv6, or something else.  For example, for DLT_EN10MB, which mean "Ethernet" (independent of the speed; the name is historical), the Ethernet type/length field is the field in question - 0x0800 means IPv4, 0x86DD means IPv6, and other values mean other things.  (Don't forget to take [VLANs](https://en.wikipedia.org/wiki/Virtual_LAN) into account on Ethernet, too.)
