### ISSUE TITLE
Issue with libnl-genl-3.0 package

### ISSUE THREAD

**Issue by uchiit** [the-tcpdump-group/libpcap#957]
**libpcap version:** configure file from master branch
**operating system name and version:** Ubuntu 18.04.4 LTS (Bionic Beaver)
**configure flags if any were used:** --enable-remote
**statement of the problem:**
./configure checks for "libnl-genl-3.0" package but current package name is "libnl-genl-3-200"

as a result unable to produce the make file

**steps to reproduce:**
install current version of Flex
run "./configure --enable-remote" in libpcap directory

**Comment by infrastation** [comment]
The `dpkg` or `rpm` package name varies between distributions, but that is not important because what the script wants to test is the `pkg-config` package name, which is a fixed string because it comes from the `libnl` source tree. And the problem is, it fails to test because there is a typo, I am looking to fix it right away if the fix is simple. For reference:

**Ubuntu 18.04**
```text
checking for libnl-genl-3.0 with pkg-config... not found
checking for nl_socket_alloc in -lnl-3... yes

ii  libnl-3-200:amd64                      3.2.29-0ubuntu3
ii  libnl-3-dev:amd64                      3.2.29-0ubuntu3
ii  libnl-genl-3-200:amd64                 3.2.29-0ubuntu3
ii  libnl-genl-3-dev:amd64                 3.2.29-0ubuntu3
ii  libnl-route-3-200:amd64                3.2.29-0ubuntu3

$ pkg-config --list-all | grep libnl
libnl-genl-3.0                 libnl-genl - Generic Netlink Library
libnl-3.0                      libnl - Convenience library for netlink sockets
```
**Fedora 32**
```text
checking for libnl-genl-3.0 with pkg-config... not found
checking for nl_socket_alloc in -lnl-3... yes

libnl3-cli-3.5.0-2.fc32.x86_64
libnl3-devel-3.5.0-2.fc32.x86_64
libnl3-3.5.0-2.fc32.x86_64

$ pkg-config --list-all | grep libnl
libnl-3.0                      libnl - Convenience library for netlink sockets
libnl-cli-3.0                  libnl-cli - Command Line Interface library for netlink sockets
libnl-genl-3.0                 libnl-genl - Generic Netlink Library
libnl-idiag-3.0                libnl-idiag - Netlink Inet Diag Family Library
libnl-nf-3.0                   libnl-nf - Netfilter Netlink Library
libnl-route-3.0                libnl-route - Netlink Routing Family Library
libnl-xfrm-3.0                 libnl-xfrm - Netlink Routing Family Library
```

**Comment by infrastation** [comment]
The master branch now has a commit that makes the `pkg-config` test work again, but in my Linux environments `configure` always managed to complete successfully even before this change, both with and without `--enable-remote`, so this may be not the problem in your environment. Could you tell what exactly was the error before the fixup, and if there is any change in behaviour after? Thank you.

**Comment by uchiit** [comment]
Here is the output from previous version:

```
./configure --enable-remote
……..
checking for libnl-genl-3.0 with pkg-config... not found
checking for nl_socket_alloc in -lnl-3... no
configure: error: libnl support requested but libnl not found

```

Same output after new release download…

```
rm -R libpcap
git clone https://github.com/the-tcpdump-group/libpcap.git
cd libpcap
./configure --enable-remote
…….
checking for libnl-genl-3.0 with pkg-config... not found
checking for nl_socket_alloc in -lnl-3... no
configure: error: libnl support requested but libnl not found

```
pkg-config --list-all | grep libnl
shows nothing

```
$apt list | grep libnl

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libnl-3-200/bionic 3.2.29-0ubuntu3 amd64
libnl-3-200-dbg/bionic 3.2.29-0ubuntu3 amd64
libnl-3-dev/bionic 3.2.29-0ubuntu3 amd64
libnl-cli-3-200/bionic 3.2.29-0ubuntu3 amd64
libnl-cli-3-dev/bionic 3.2.29-0ubuntu3 amd64
libnl-genl-3-200/bionic 3.2.29-0ubuntu3 amd64
libnl-genl-3-dev/bionic 3.2.29-0ubuntu3 amd64
libnl-idiag-3-200/bionic 3.2.29-0ubuntu3 amd64
libnl-idiag-3-dev/bionic 3.2.29-0ubuntu3 amd64
libnl-nf-3-200/bionic 3.2.29-0ubuntu3 amd64
libnl-nf-3-dev/bionic 3.2.29-0ubuntu3 amd64
libnl-route-3-200/bionic 3.2.29-0ubuntu3 amd64
libnl-route-3-dev/bionic 3.2.29-0ubuntu3 amd64
libnl-utils/bionic 3.2.29-0ubuntu3 amd64
libnl-xfrm-3-200/bionic 3.2.29-0ubuntu3 amd64
libnl-xfrm-3-dev/bionic 3.2.29-0ubuntu3 amd64
libnlopt-dev/bionic 2.4.2+dfsg-4 amd64
libnlopt-guile0/bionic 2.4.2+dfsg-4 amd64
libnlopt0/bionic 2.4.2+dfsg-4 amd64
ntrack-module-libnl-0/bionic 016-1.3 amd64
```

This packages was installed:
```
apt install gcc
apt-get install flex
apt-get install pkg-config
apt-get install bison
```

**Comment by uchiit** [comment]
I believe there is some issues not with libpcap` configure` file but with pkg-config due to it can see not so much...
```
$ pkg-config --list-all
systemd          systemd - systemd System and Service Manager
usbutils         usbutils - USB device database
xkeyboard-config XKeyboardConfig - X Keyboard configuration data
udev             udev - udev
bash-completion  bash-completion - programmable completion for the bash shell
libfl            libfl - Flex (the fast lexical analyzer) support library
libpcap          libpcap - Platform-independent network traffic capture library
iso-codes        iso-codes - ISO country, language, script and currency codes and translations
shared-mime-info shared-mime-info - Freedesktop common MIME database

```

**Comment by guyharris** [comment]
> Same output after new release download…
> 
> ```
> rm -R libpcap
> git clone https://github.com/the-tcpdump-group/libpcap.git
> cd libpcap
> ./configure --enable-remote
> …….
> checking for libnl-genl-3.0 with pkg-config... not found
> checking for nl_socket_alloc in -lnl-3... no
> configure: error: libnl support requested but libnl not found

But you *didn't* request libnl support - you didn't use `--with-libnl`, which says "build this with libnl"; the default is "build with libnl, *if you find it*", not "built with libnl, and fail if you don't find it".

That's *definitely* a bug in libpcap's configure script.

**Comment by guyharris** [comment]
Commit 4e31856aa1525a452218a447d7f4c8e8272ff1b3 should fix the configure script so that, if you haven't explicitly requested libnl with `--with-libnl`, and you don't have a libnl development package installed, it will just arrange to build without libnl, rather than failing.

Try that.

**Comment by guyharris** [comment]
> The master branch now has a commit that makes the `pkg-config` test work again, but in my Linux environments `configure` always managed to complete successfully even before this change, both with and without `--enable-remote`, so this may be not the problem in your environment. Could you tell what exactly was the error before the fixup, and if there is any change in behaviour after? Thank you.

`--enable-remote` makes no difference - the remote capture code doesn't require libnl, it just requires sockets, which are there by default in all the OSes on which we build.

What makes a difference here is whether you have a developer package for libnl installed; if you didn't have it installed, and you didn't explicitly specify `--with-libnl`, the configure script was *supposed* to arrange to build without libnl, but, instead, ti was failing.  Commit 4e31856aa1525a452218a447d7f4c8e8272ff1b3 should have fixed that.

**Comment by infrastation** [comment]
@guyharris, finally that explains why a while ago libpcap started to fail to configure in Linux demanding libnl headers. At that time I thought that was intended, so just installed the required package and didn't look closely. With the development package uninstalled on Ubuntu 18.04 the effect of commit 4e31856 is as expected:

Before:
```text
checking for libnl-genl-3.0 with pkg-config... not found
checking for nl_socket_alloc in -lnl-3... no
configure: error: libnl support requested but libnl not found
```

After:
```text
checking for libnl-genl-3.0 with pkg-config... not found
checking for nl_socket_alloc in -lnl-3... no
[...]
configure: creating ./config.status
```

@uchiit, the Ubuntu package name is `libnl-genl-3-dev`. From the output above it is clear it is not installed (`apt list` shows what is available in the repository, to see what is installed you need `dpkg-query --list`, in this specific case the output of `pkg-config` proves it). If you install that package before getting the latest master branch, it will work around the problem. If you take the latest master branch, it will build regardless if the package is installed.

**Comment by uchiit** [comment]
@infrastation @guyharris Thank you for all this explanations and fixes! And as I can understand without "libnl" there will be some issues while working with wlan interfaces, isnt so?

**Comment by guyharris** [comment]
> @infrastation @guyharris Thank you for all this explanations and fixes! And as I can understand without "libnl" there will be some issues while working with wlan interfaces, isnt so?

The APIs to turn on monitor mode from libpcap won't work without libnl.

If you *manually* create a monitor device, and capture on it, that should work.

Capturing in non-monitor mode should work either way.

**Comment by uchiit** [comment]
Great, becouse I do it manually through airmon-ng. But some amount of automation from libpcap will be helpful. Tomorrow will try this stuff. Thank you again!

**Comment by guyharris** [comment]
Sorry about getting the configure script wrong....
