### ISSUE TITLE
Shaping traffic

### ISSUE THREAD

**Issue by Tomasz158** [the-tcpdump-group/libpcap#958]
Is it possible to slow down or speed up (shape in general) certain packets using libpcap?

**Comment by guyharris** [comment]
No.  In "libpcap", "lib" stands for "library" (standard UN\*X convention for library names, as enforced by UN\*X linkers), "p" stands for "packet", and "cap" stands for capture; it's a library for capturing and injecting network traffic.

It uses mechanisms in OS kernels (on UN\*X) or added on to existing mechanisms in OS kernels (on Windows) to capture and inject traffic.

Traffic *shaping* is generally done by *other* mechanisms in the OS kernel, such as [network schedulers](https://en.wikipedia.org/wiki/Network_scheduler), or by traffic shaping devices.  One might be able to implement a traffic shaping device with a UN\*X or Windows box and libpcap/WinPcap/Npcap, having it read packets by capturing them and send packets by injecting them, but the only way that \*pcap would contribute to this would be to provide the mechanism used to capture and inject packets - it wouldn't do the shaping itself.
