### ISSUE TITLE
setting dscp for a packet

### ISSUE THREAD

**Issue by Tomasz158** [the-tcpdump-group/libpcap#959]
Is there a way to mark certain packets by setting dscp value?

**Comment by guyharris** [comment]
Libpcap does two things with packets:

1. captures them from devices and reads them from saved capture files;
1. injects them onto a network.

For the first of those functions, the DSCP value in an IPv4 packet is what was on the network or in the file; there's no mechanism for changing it.

For the second of those functions, the DSCP value in an IPv4 packet is what the program using libpcap to inject it put there; there's no mechanism for changing it once it's handed to libpcap.

The mechanisms libpcap used to capture and inject network packets do not plug into the operating system networking stack at a point where a program using libpcap can modify the DSCP value in an incoming packet before it's processed by the IPv4 code or in an out coming packet after the IPv4 code sets it but before it's transmitted on the network.

There may, in some operating systems, a mechanism, available to user-mode code, that would allow that, but I don't know of any library that provides an operating-system-independent API for doing that, the way libpcap provides an operating-system-independent API for capturing and injecting packets.

**Comment by Tomasz158** [comment]
I understand. I also thought of creating  virtual network interfaces (one for Skype, second for ICMP and so on) and push those packets through those interfaces (and redirect the replies back to original interfaces), so I can create traffic policies for each adapter seperately. Such a way is possible? If so, which functions can handle that?

**Comment by guyharris** [comment]
> I understand. I also thought of creating virtual network interfaces (one for Skype, second for ICMP and so on) and push those packets through those interfaces (and redirect the replies back to original interfaces), so I can create traffic policies for each adapter seperately. Such a way is possible?

Not with libpcap.  Perhaps whatever operating system you're using provides a way to do that.
