### ISSUE TITLE
packets per second

### ISSUE THREAD

**Issue by Tomasz158** [the-tcpdump-group/libpcap#963]
How can I calculate number of captured packets per second?

**Comment by guyharris** [comment]
1. Have the callback for `pcap_loop()` or `pcap_dispatch()`, or the code that calls `pcap_next()` or `pcap_next_ex()`, count each packet received.

1. Get the time when you start capturing and the time when you want to report the captured packets per second, and subtract the former from the latter, giving the number of seconds you've been capturing.

1. Divide the number of packets received by the number of seconds.

**Comment by infrastation** [comment]
Closing as resolved.
