### ISSUE TITLE
Autoconf and Automake

### ISSUE THREAD

**Issue by Tomasz158** [the-tcpdump-group/libpcap#967]
What should I write in makefile.am and config.am, to compile a program that uses libpcap?
Under Linux.

**Comment by infrastation** [comment]
You can use tcpdump and tcpslice as examples. If you look in the `aclocal.m4` file in these repositories, there is a macro called `AC_LBL_LIBPCAP`. If you do not need the "if there is libpcap in `../libpcap`, link with it statically" feature, then the branch that starts with `if test $using_local_libpcap = no ; then` should be a good starting point.

It is probably not the most accurate explanation, but you can see if it works.

**Comment by Tomasz158** [comment]
I will give it a try, thanks.

**Comment by Tomasz158** [comment]
It works for pthread and libpcap, but do not work for ndpi.
The problem I still get is
```
undefined reference to `ndpi_calloc'
```
./config states:
```
checking for main in -lndpi... no
checking for main in -lpcap... yes
checking for main in -lpthread... yes
```
and in the linker options I have all three of those. My configure.ac file:
```
AC_CHECK_LIB(ndpi, main)
AC_CHECK_LIB(pcap, main)
AC_CHECK_LIB(pthread, main)
```

**Comment by infrastation** [comment]
Alright, so that solves the original issue with libpcap, good. Regarding libndpi, the reason may be easier to see if you examine the end of `config.log`, as the configure script usually suggests on an error. If that does not help, it would be better if you ask libndpi developers.

**Comment by Tomasz158** [comment]
I guess I see the issue,
 ``
LIBS='-lpthread -lpcap '
```
should be one more there, -lndpi
I suppose the issue iss here:
```
**ac_cv_lib_ndpi_main=no**
ac_cv_lib_pcap_main=yes
ac_cv_lib_pthread_main=yes
```
I asked on nDPI github about it.

**Comment by infrastation** [comment]
Closing as resolved, good luck.
