### ISSUE TITLE
Use pcap_loop() and delay a lot in Jetson AGX Xavier

### ISSUE THREAD

**Issue by tenglike1997** [the-tcpdump-group/libpcap#969]
The following is my code,and I have tested in Jetson TX2 and the code can run normally.However,when the code transplant to Jetson AGX Xavier,we meet delay.The packet we sent is a udp packet with 2 bytes data.

```
#include <stdio.h>
#include <stdlib.h>
#include<iostream>
#include <pcap.h>
#include <string.h>
#include <vector>
#include <csignal>
using namespace std;
using namespace cv; 
void getPacket(u_char * arg, const struct pcap_pkthdr * pkthdr, const u_char * packet)
{
    pcap_t * device = (pcap_t *)arg;
    static int id = 0;
    printf("id: %d\n", ++(id));
    printf("Packet length: %d\n", pkthdr->len);
    printf("Number of bytes: %d\n", pkthdr->caplen);
    printf("Recieved time: %s", ctime((const time_t *)&pkthdr->ts.tv_sec));
    if((pkthdr->len==46)&&(*(packet+42)=='E')&&(*(packet+43)=='O')&&(*(packet+44)=='F')&&(*(packet+45)=='\0')){      
        pcap_breakloop(device);
    }
    else{
        cout<<(int)*(packet+42)<<endl;
        cout<<(int)*(packet+43)<<endl;
    }
    printf("\n\n");
}
int main(int argc, char *argv[])
{
    char errBuf[PCAP_ERRBUF_SIZE], * devStr;
    /* get a device */
    devStr = pcap_lookupdev(errBuf);
    if(devStr)
    {
      printf("success: device: %s\n", devStr);
    }
    else
    {
      printf("error: %s\n", errBuf);
      exit(1);
    }
    /* open a device, wait until a packet arrives */
    pcap_t * device = pcap_open_live(devStr, 65535, 1, 0, errBuf);
    if(!device)
    {
        printf("error: pcap_open_live(): %s\n", errBuf);
        exit(1);
    }
    struct bpf_program filter;
    pcap_compile(device, &filter, "src host 127.0.0.1", 1, 0);
    pcap_setfilter(device, &filter);
    /* wait loop forever */
    pcap_loop(device, -1, getPacket, (u_char*)device);
    pcap_close(device);
    return 0;
}
```

Could you tell me how to solve it?Thanks.

**Comment by guyharris** [comment]
You passed a value of 0 as the *to_ms* argument to `pcap_open_live()`.

To quote [the `pcap_open_live()` man page](https://www.tcpdump.org/manpages/pcap_open_live.3pcap.html):

> *to_ms* specifies the packet buffer timeout, as a non-negative value, in milliseconds. (See pcap(3PCAP) for an explanation of the packet buffer timeout.)

and to quote the "Packet buffer timeout" section of [the pcap(3PCAP) man page](https://www.tcpdump.org/manpages/pcap.3pcap.html):

> If, when capturing, packets are delivered as soon as they arrive, the application capturing the packets will be woken up for each packet as it arrives, and might have to make one or more calls to the operating system to fetch each packet.
> If, instead, packets are not delivered as soon as they arrive, but are delivered after a short delay (called a "packet buffer timeout"), more than one packet can be accumulated before the packets are delivered, so that a single wakeup would be done for multiple packets, and each set of calls made to the operating system would supply multiple packets, rather than a single packet. This reduces the per-packet CPU overhead if packets are arriving at a high rate, increasing the number of packets per second that can be captured.
> The packet buffer timeout is required so that an application won't wait for the operating system's capture buffer to fill up before packets are delivered; if packets are arriving slowly, that wait could take an arbitrarily long period of time.
> Not all platforms support a packet buffer timeout; on platforms that don't, the packet buffer timeout is ignored. A zero value for the timeout, on platforms that support a packet buffer timeout, will cause a read to wait forever to allow enough packets to arrive, with no timeout. A negative value is invalid; the result of setting the timeout to a negative value is unpredictable.
> **NOTE**: the packet buffer timeout cannot be used to cause calls that read packets to return within a limited period of time, because, on some platforms, the packet buffer timeout isn't supported, and, on other platforms, the timer doesn't start until at least one packet arrives. This means that the packet buffer timeout should **NOT** be used, for example, in an interactive application to allow the packet capture loop to ``poll'' for user input periodically, as there's no guarantee that a call reading packets will return after the timeout expires even if no packets have arrived.
> The packet buffer timeout is set with **pcap_set_timeout()**.

which applies to the *to_ms* argument to `pcap_open_live()` as well.

The value of 0 means that `pcap_loop()` could wait until the packet buffer fills up before calling the callback.  This will happen on platforms using BPF (\*BSD, macOS, Solaris, AIX) as well as on Linux (except with older versions of libpcap and *much* older versions of the kernel).  I'm guessing your code is running on Linux.

The fewer packets that arrive on the interface and pass whatever capture filter you have installed, the more time it will take to fill up the packet buffer.  Unless you are capturing on the loopback interface, you will probably receive *no* packets with a source IP address of 127.0.0.1; there is *no* guarantee that `pcap_lookupdev()` will return the name of the loopback device, so there is *no* guarantee, with your code, that you will receive *any* packets.

What is it you are trying to do here?

**Comment by tenglike1997** [comment]
> You passed a value of 0 as the _to_ms_ argument to `pcap_open_live()`.
> 
> To quote [the `pcap_open_live()` man page](https://www.tcpdump.org/manpages/pcap_open_live.3pcap.html):
> 
> > _to_ms_ specifies the packet buffer timeout, as a non-negative value, in milliseconds. (See pcap(3PCAP) for an explanation of the packet buffer timeout.)
> 
> and to quote the "Packet buffer timeout" section of [the pcap(3PCAP) man page](https://www.tcpdump.org/manpages/pcap.3pcap.html):
> 
> > If, when capturing, packets are delivered as soon as they arrive, the application capturing the packets will be woken up for each packet as it arrives, and might have to make one or more calls to the operating system to fetch each packet.
> > If, instead, packets are not delivered as soon as they arrive, but are delivered after a short delay (called a "packet buffer timeout"), more than one packet can be accumulated before the packets are delivered, so that a single wakeup would be done for multiple packets, and each set of calls made to the operating system would supply multiple packets, rather than a single packet. This reduces the per-packet CPU overhead if packets are arriving at a high rate, increasing the number of packets per second that can be captured.
> > The packet buffer timeout is required so that an application won't wait for the operating system's capture buffer to fill up before packets are delivered; if packets are arriving slowly, that wait could take an arbitrarily long period of time.
> > Not all platforms support a packet buffer timeout; on platforms that don't, the packet buffer timeout is ignored. A zero value for the timeout, on platforms that support a packet buffer timeout, will cause a read to wait forever to allow enough packets to arrive, with no timeout. A negative value is invalid; the result of setting the timeout to a negative value is unpredictable.
> > **NOTE**: the packet buffer timeout cannot be used to cause calls that read packets to return within a limited period of time, because, on some platforms, the packet buffer timeout isn't supported, and, on other platforms, the timer doesn't start until at least one packet arrives. This means that the packet buffer timeout should **NOT** be used, for example, in an interactive application to allow the packet capture loop to ``poll'' for user input periodically, as there's no guarantee that a call reading packets will return after the timeout expires even if no packets have arrived.
> > The packet buffer timeout is set with **pcap_set_timeout()**.
> 
> which applies to the _to_ms_ argument to `pcap_open_live()` as well.
> 
> The value of 0 means that `pcap_loop()` could wait until the packet buffer fills up before calling the callback. This will happen on platforms using BPF (*BSD, macOS, Solaris, AIX) as well as on Linux (except with older versions of libpcap and _much_ older versions of the kernel). I'm guessing your code is running on Linux.
> 
> The fewer packets that arrive on the interface and pass whatever capture filter you have installed, the more time it will take to fill up the packet buffer. Unless you are capturing on the loopback interface, you will probably receive _no_ packets with a source IP address of 127.0.0.1; there is _no_ guarantee that `pcap_lookupdev()` will return the name of the loopback device, so there is _no_ guarantee, with your code, that you will receive _any_ packets.
> 
> What is it you are trying to do here?

Thanks for your advice.Now I solve the problem successfully.
