### ISSUE TITLE
Tcpdump:  two problem, reading pcap file and capture  bgp update info

### ISSUE THREAD

**Issue by carboxste** [the-tcpdump-group/libpcap#973]
If I  need to capture some nets received by bgp remote speaker when bgp session starts.
I can create the pcap file:

tcpdump -S0 -i "interface" host "remote neighbor" -w file.pcap.

I open the pcap file with Wireshark and I can see all frames containing all 817000 downloaded nets (full routing table received from the remote carrier's speaker)
After the full routing, I can see  all following update bgp information (UPDATE AS-PATH, withdrawn and so on).

Perfect.

The first problem is that I am not able to use tcpdump like wireshark to read the pcap file.
There are no options with tcpdump to read the pcap file and capture one or more network of full routing table.

Wireshark wotks fine, tcpdump dont.

If I want to capture in real time bgp updates information it's not a problem.
Simply I can launch

 /usr/sbin/tcpdump -f -s 0 -i "interface" -nn -N -S -vvv -tttt port bgp and src host "remote speaker address"

and I obptain the information, for example these:

        Update Message (2), length: 74
          Origin (1), length: 1, Flags [T]: Incomplete
            0x0000:  02
          AS Path (2), length: 22, Flags [T]: 3269 6762 6453 4761 4795 
            0x0000:  0205 0000 0cc5 0000 1a6a 0000 1935 0000
            0x0010:  1299 0000 12bb
          Next Hop (3), length: 4, Flags [T]: 62.86.118.243
            0x0000:  3e56 76f3
          Community (8), length: 8, Flags [OT]: 6762:30, 6762:13300
            0x0000:  1a6a 001e 1a6a 33f4
          Updated routes:
            202.155.148.0/24

The second problem is that, if I shut down the ebgp session, I launch the tcpdump string and then I start the bgp session again,
the tcpdump does not capture the full routing tables net received.

Trust me the problem is true.
I work on ISP provider and manage a lot of ebgp session for customers.

Thank you
Regards
Stefano

**Comment by infrastation** [comment]
Are you saying `tcpdump -n -r file.pcap -vvvv` does not work?

**Comment by carboxste** [comment]
Exactly
I have created a pcap file that contain all dialogue between the two speakers during the ebgp session is going up

If I look for one net/prefix received with the full routing table download I am not able to findi it.
I can find only bgp updates received after the frt is downloaded. 

root@BGP-Telecom:~/carbo# tcpdump -n -r Tim.pcap -vvvv | grep "88.36.0.0"
reading from file Telecom.pcap, link-type EN10MB (Ethernet)
            188.36.0.0/16

If I open the same pcap file with wireshark I can find the frame with bgp update 88.36.0.0/15 and all the other 817000 prefix.

**Comment by carboxste** [comment]
For now I solved using tshark on linux.

Thank you
Regards
Stefano

**Comment by infrastation** [comment]
If you could use tshark to locate the prefix of interest and to tell the packet number in the .pcap file, and then `editcap -r file.pcap file2.pcap <packet_number>` to take just that packet, and then post it here, it would be easier to tell.

**Comment by carboxste** [comment]
Is there a way to send the pcap privatly? It's 844 kB
frame 27

**Comment by infrastation** [comment]
My profile lists an e-mail address you can use.
