### ISSUE TITLE
make: *** [libpcap.dylib] Error 1 

### ISSUE THREAD

**Issue by 282857484** [the-tcpdump-group/libpcap#981]
make fail, i delete  "-arch i386" in the file "Makefile" and then sucess
macOS 10.14.1 (18B75)

houbin:libpcap-1.9.1 1031248990qq.com$ ./configure
houbin:libpcap-1.9.1 1031248990qq.com$ make
rm -f libpcap*.dylib
VER=`cat ./VERSION`; \
	MAJOR_VER=A; \
	COMPAT_VER=1; \
	CURRENT_VER=`sed 's/[^0-9.].*$//' ./VERSION`; \
	gcc -dynamiclib -undefined error  -arch x86_64 -arch i386 \
	    -o libpcap.$VER.dylib pcap-bpf.o fad-getad.o pcap.o gencode.o optimize.o nametoaddr.o etherent.o fmtutils.o savefile.o sf-pcap.o sf-pcapng.o pcap-common.o bpf_image.o bpf_filter.o bpf_dump.o  scanner.o grammar.o    \
	    -install_name /usr/local/lib/libpcap.$MAJOR_VER.dylib \
	    -compatibility_version $COMPAT_VER \
	    -current_version $CURRENT_VER
ld: warning: The i386 architecture is deprecated for macOS (remove from the Xcode build setting: ARCHS)
ld: warning: ignoring file /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/libSystem.tbd, missing required architecture i386 in file /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/libSystem.tbd
Undefined symbols for architecture i386:
  "__DefaultRuneLocale", referenced from:
      _pcap_ether_aton in nametoaddr.o
      _pcap_next_etherent in etherent.o
      _pcap_lex in scanner.o
      _pcap_ether_aton in nametoaddr.o
      _pcap_next_etherent in etherent.o
      _pcap_lex in scanner.o
      _pcap_ether_aton in nametoaddr.o
      _pcap_next_etherent in etherent.o
      _pcap_lex in scanner.o
  "___bzero", referenced from:
      _pcap_create_common in pcap.o
      _pcap_open_offline_common in pcap.o
      _pcap_open_dead_with_tstamp_precision in pcap.o
      _pcap_open_dead in pcap.o
      _newchunk_nolongjmp in gencode.o
      _pcap_compile in gencode.o
      _gen_protochain in gencode.o
      ...
  "___error", referenced from:
      _pcap_activate_bpf in pcap-bpf.o
      _pcap_can_set_rfmon_bpf in pcap-bpf.o
      _check_bpf_bindable in pcap-bpf.o
      _get_if_flags in pcap-bpf.o
      _bpf_open in pcap-bpf.o
      _get_dlt_list in pcap-bpf.o
      _check_setif_failure in pcap-bpf.o
      ...
  "___maskrune", referenced from:
      _pcap_ether_aton in nametoaddr.o
      _pcap_next_etherent in etherent.o
      _pcap_lex in scanner.o
  "___memset_chk", referenced from:
      _gen_mcode6 in gencode.o
  "___snprintf_chk", referenced from:
      _pcap_activate_bpf in pcap-bpf.o
      _bpf_open in pcap-bpf.o
      _pcap_read_bpf in pcap-bpf.o
      _pcap_setdirection_bpf in pcap-bpf.o
      _pcap_lookupnet in pcap.o
      _pcap_check_activated in pcap.o
      _pcap_set_snaplen in pcap.o
      ...
  "___stack_chk_fail", referenced from:
      _pcap_activate_bpf in pcap-bpf.o
      _pcap_can_set_rfmon_bpf in pcap-bpf.o
      _check_bpf_bindable in pcap-bpf.o
      _get_if_flags in pcap-bpf.o
      _bpf_open in pcap-bpf.o
      _check_setif_failure in pcap-bpf.o
      _bpf_open_and_bind in pcap-bpf.o
      ...
  "___stack_chk_guard", referenced from:
      _pcap_activate_bpf in pcap-bpf.o
      _pcap_can_set_rfmon_bpf in pcap-bpf.o
      _check_bpf_bindable in pcap-bpf.o
      _get_if_flags in pcap-bpf.o
      _bpf_open in pcap-bpf.o
      _check_setif_failure in pcap-bpf.o
      _bpf_open_and_bind in pcap-bpf.o
      ...
      _pcap_activate_bpf in pcap-bpf.o
      _pcap_can_set_rfmon_bpf in pcap-bpf.o
      _check_bpf_bindable in pcap-bpf.o
      _get_if_flags in pcap-bpf.o
      _bpf_open in pcap-bpf.o
      _check_setif_failure in pcap-bpf.o
      _bpf_open_and_bind in pcap-bpf.o
      ...
      _pcap_activate_bpf in pcap-bpf.o
      _pcap_can_set_rfmon_bpf in pcap-bpf.o
      _check_bpf_bindable in pcap-bpf.o
      _get_if_flags in pcap-bpf.o
      _bpf_open in pcap-bpf.o
      _check_setif_failure in pcap-bpf.o
      _bpf_open_and_bind in pcap-bpf.o
      ...
      _pcap_activate_bpf in pcap-bpf.o
      _pcap_can_set_rfmon_bpf in pcap-bpf.o
      _check_bpf_bindable in pcap-bpf.o
      _get_if_flags in pcap-bpf.o
      _bpf_open in pcap-bpf.o
      _check_setif_failure in pcap-bpf.o
      _bpf_open_and_bind in pcap-bpf.o
      ...
      _pcap_activate_bpf in pcap-bpf.o
      _pcap_can_set_rfmon_bpf in pcap-bpf.o
      _check_bpf_bindable in pcap-bpf.o
      _get_if_flags in pcap-bpf.o
      _bpf_open in pcap-bpf.o
      _check_setif_failure in pcap-bpf.o
      _bpf_open_and_bind in pcap-bpf.o
      ...
      _pcap_activate_bpf in pcap-bpf.o
      _pcap_can_set_rfmon_bpf in pcap-bpf.o
      _check_bpf_bindable in pcap-bpf.o
      _get_if_flags in pcap-bpf.o
      _bpf_open in pcap-bpf.o
      _check_setif_failure in pcap-bpf.o
      _bpf_open_and_bind in pcap-bpf.o
      ...
      _pcap_activate_bpf in pcap-bpf.o
      _pcap_can_set_rfmon_bpf in pcap-bpf.o
      _check_bpf_bindable in pcap-bpf.o
      _get_if_flags in pcap-bpf.o
      _bpf_open in pcap-bpf.o
      _check_setif_failure in pcap-bpf.o
      _bpf_open_and_bind in pcap-bpf.o
      ...
      ...
  "___stderrp", referenced from:
      _pcap_perror in pcap.o
      _yy_fatal_error in scanner.o
      _pcap_perror in pcap.o
      _yy_fatal_error in scanner.o
  "___stdinp", referenced from:
      _sf_cleanup in savefile.o
      _pcap_open_offline_with_tstamp_precision in savefile.o
      _pcap_lex in scanner.o
      _sf_cleanup in savefile.o
      _pcap_open_offline_with_tstamp_precision in savefile.o
      _pcap_lex in scanner.o
  "___stdoutp", referenced from:
      _pcap_dump_open in sf-pcap.o
      _pcap_dump_fopen in sf-pcap.o
      _pcap_dump_open_append in sf-pcap.o
      _pcap_lex in scanner.o
      _pcap_dump_open in sf-pcap.o
      _pcap_dump_fopen in sf-pcap.o
      _pcap_dump_open_append in sf-pcap.o
      _pcap_lex in scanner.o
  "___strcat_chk", referenced from:
      _pcap_activate_bpf in pcap-bpf.o
      _check_bpf_bindable in pcap-bpf.o
  "___strlcat_chk", referenced from:
      _pcap_can_set_rfmon_bpf in pcap-bpf.o
      _check_setif_failure in pcap-bpf.o
  "___strlcpy_chk", referenced from:
      _pcap_activate_bpf in pcap-bpf.o
      _pcap_can_set_rfmon_bpf in pcap-bpf.o
      _check_setif_failure in pcap-bpf.o
      _pcap_lookupdev in pcap.o
      _pcap_lookupnet in pcap.o
      _pcap_getnonblock in pcap.o
      _pcap_setnonblock in pcap.o
      ...
  "___udivdi3", referenced from:
      _add_interface in sf-pcapng.o
      _pcap_ng_next_packet in sf-pcapng.o
  "___vsnprintf_chk", referenced from:
      _bpf_set_error in gencode.o
      _bpf_error in gencode.o
      _opt_error in optimize.o
      _conv_error in optimize.o
      _pcap_fmt_errmsg_for_errno in fmtutils.o
  "_abort", referenced from:
      _gen_proto_abbrev_internal in gencode.o
      _gen_portop in gencode.o
      _gen_portop6 in gencode.o
      _gen_portrangeop in gencode.o
      _gen_portrangeop6 in gencode.o
      _gen_scode in gencode.o
      _gen_host in gencode.o
      ...
  "_atexit", referenced from:
      _pcap_do_addexit in pcap.o
  "_atoi", referenced from:
      _add_dev in pcap.o
     (maybe you meant: ___pcap_atoin)
  "_calloc", referenced from:
      _pcap_list_tstamp_types in pcap.o
      _pcap_list_datalinks in pcap.o
      _bpf_optimize in optimize.o
      _convert_code_r in optimize.o
  "_clearerr", referenced from:
      _pcap_lex in scanner.o
  "_close$UNIX2003", referenced from:
      _pcap_activate_bpf in pcap-bpf.o
      _pcap_can_set_rfmon_bpf in pcap-bpf.o
      _check_bpf_bindable in pcap-bpf.o
      _get_if_flags in pcap-bpf.o
      _check_setif_failure in pcap-bpf.o
      _bpf_open_and_bind in pcap-bpf.o
      _pcap_lookupnet in pcap.o
      ...
  "_ether_hostton", referenced from:
      _pcap_ether_hostton in nametoaddr.o
     (maybe you meant: _pcap_ether_hostton)
  "_exit", referenced from:
      _yy_fatal_error in scanner.o
  "_fclose", referenced from:
      _sf_cleanup in savefile.o
      _pcap_open_offline_with_tstamp_precision in savefile.o
      _pcap_dump_open in sf-pcap.o
      _pcap_dump_fopen in sf-pcap.o
      _pcap_dump_open_append in sf-pcap.o
      _pcap_dump_close in sf-pcap.o
  "_fcntl$UNIX2003", referenced from:
      _pcap_getnonblock_fd in pcap.o
      _pcap_setnonblock_fd in pcap.o
  "_feof", referenced from:
      _pcap_dump_open_append in sf-pcap.o
  "_ferror", referenced from:
      _pcap_fopen_offline_with_tstamp_precision in savefile.o
      _pcap_check_header in sf-pcap.o
      _pcap_next_packet in sf-pcap.o
      _pcap_dump_open_append in sf-pcap.o
      _pcap_ng_check_header in sf-pcapng.o
      _read_block in sf-pcapng.o
      _pcap_lex in scanner.o
      ...
  "_fflush", referenced from:
      _pcap_dump_flush in sf-pcap.o
  "_fileno", referenced from:
      _pcap_fopen_offline_with_tstamp_precision in savefile.o
     (maybe you meant: _pcap_fileno)
  "_fopen$UNIX2003", referenced from:
      _pcap_open_offline_with_tstamp_precision in savefile.o
      _pcap_dump_open in sf-pcap.o
      _pcap_dump_open_append in sf-pcap.o
  "_fprintf", referenced from:
      _pcap_perror in pcap.o
      _yy_fatal_error in scanner.o
  "_fread", referenced from:
      _pcap_fopen_offline_with_tstamp_precision in savefile.o
      _pcap_check_header in sf-pcap.o
      _pcap_next_packet in sf-pcap.o
      _pcap_dump_open_append in sf-pcap.o
      _pcap_ng_check_header in sf-pcapng.o
      _read_block in sf-pcapng.o
      _pcap_lex in scanner.o
      ...
  "_free", referenced from:
      _pcap_activate_bpf in pcap-bpf.o
      _pcap_can_set_rfmon_bpf in pcap-bpf.o
      _check_bpf_bindable in pcap-bpf.o
      _get_dlt_list in pcap-bpf.o
      _pcap_cleanup_bpf in pcap-bpf.o
      _pcap_free_tstamp_types in pcap.o
      _pcap_freealldevs in pcap.o
      ...
     (maybe you meant: _pcap_free, _pcap_free_tstamp_types , _pcap_free_datalinks , _pcap_freecode , _pcap_freealldevs )
  "_freeaddrinfo", referenced from:
      _pcap_compile in gencode.o
      _gen_scode in gencode.o
      _gen_mcode6 in gencode.o
      _pcap_nametoport in nametoaddr.o
      _pcap_lex in scanner.o
  "_freeifaddrs", referenced from:
      _pcap_findalldevs_interfaces in fad-getad.o
  "_fseek", referenced from:
      _pcap_dump_open_append in sf-pcap.o
  "_ftell", referenced from:
      _pcap_dump_ftell in sf-pcap.o
     (maybe you meant: _pcap_dump_ftell, _pcap_dump_ftell64 )
  "_ftello", referenced from:
      _pcap_dump_ftell64 in sf-pcap.o
  "_fwrite$UNIX2003", referenced from:
      _pcap_dump in sf-pcap.o
      _pcap_dump_open in sf-pcap.o
      _pcap_dump_fopen in sf-pcap.o
      _pcap_dump_open_append in sf-pcap.o
      _pcap_lex in scanner.o
  "_getaddrinfo", referenced from:
      _pcap_nametoaddrinfo in nametoaddr.o
      _pcap_nametoport in nametoaddr.o
      _pcap_lex in scanner.o
  "_getc", referenced from:
      _pcap_next_etherent in etherent.o
      _pcap_lex in scanner.o
  "_gethostbyname", referenced from:
      _pcap_nametoaddr in nametoaddr.o
  "_getifaddrs", referenced from:
      _pcap_findalldevs_interfaces in fad-getad.o
  "_getnetbyname", referenced from:
      _pcap_nametonetaddr in nametoaddr.o
  "_getprotobyname", referenced from:
      _pcap_nametoproto in nametoaddr.o
  "_ioctl", referenced from:
      _pcap_activate_bpf in pcap-bpf.o
      _pcap_can_set_rfmon_bpf in pcap-bpf.o
      _get_if_flags in pcap-bpf.o
      _get_dlt_list in pcap-bpf.o
      _check_setif_failure in pcap-bpf.o
      _pcap_inject_bpf in pcap-bpf.o
      _pcap_setfilter_bpf in pcap-bpf.o
      ...
  "_longjmp", referenced from:
      _pcap_compile in gencode.o
      _finish_parse in gencode.o
      _gen_llc_internal in gencode.o
      _gen_llc_i in gencode.o
      _gen_load_a in gencode.o
      _gen_llc_s in gencode.o
      _gen_llc_u in gencode.o
      ...
  "_malloc", referenced from:
      _pcap_activate_bpf in pcap-bpf.o
      _check_bpf_bindable in pcap-bpf.o
      _get_dlt_list in pcap-bpf.o
      _pcap_list_tstamp_types in pcap.o
      _add_addr_to_dev in pcap.o
      _add_dev in pcap.o
      _pcap_create_common in pcap.o
      ...
  "_memcpy", referenced from:
      _pcap_list_tstamp_types in pcap.o
      _add_addr_to_dev in pcap.o
      _pcap_list_datalinks in pcap.o
      _opt_loop in optimize.o
      _install_bpf_program in optimize.o
      _pcap__scan_string in scanner.o
      _pcap__scan_bytes in scanner.o
      ...
  "_memset", referenced from:
      _opt_loop in optimize.o
  "_open$UNIX2003", referenced from:
      _bpf_open in pcap-bpf.o
  "_printf", referenced from:
      _bpf_dump in bpf_dump.o
  "_puts", referenced from:
      _bpf_dump in bpf_dump.o
  "_read$UNIX2003", referenced from:
      _pcap_read_bpf in pcap-bpf.o
  "_realloc", referenced from:
      _pcap_next_packet in sf-pcap.o
      _read_block in sf-pcapng.o
      _add_interface in sf-pcapng.o
      _pcap_lex in scanner.o
      _pcap_ensure_buffer_stack in scanner.o
      _pcap_realloc in scanner.o
     (maybe you meant: _pcap_realloc)
  "_setjmp", referenced from:
      _pcap_compile in gencode.o
      _finish_parse in gencode.o
      _gen_llc in gencode.o
      _gen_llc_i in gencode.o
      _gen_llc_s in gencode.o
      _gen_llc_u in gencode.o
      _gen_llc_s_subtype in gencode.o
      ...
  "_socket", referenced from:
      _pcap_activate_bpf in pcap-bpf.o
      _pcap_can_set_rfmon_bpf in pcap-bpf.o
      _get_if_flags in pcap-bpf.o
      _check_setif_failure in pcap-bpf.o
      _pcap_lookupnet in pcap.o
  "_sscanf", referenced from:
      _pcap_nametoportrange in nametoaddr.o
      ___pcap_atodn in nametoaddr.o
  "_strchr", referenced from:
      _pcap_findalldevs_interfaces in fad-getad.o
      _pcap_nametoportrange in nametoaddr.o
  "_strcmp", referenced from:
      _pcap_activate_bpf in pcap-bpf.o
      _find_or_add_if in pcap.o
      _find_or_add_dev in pcap.o
      _add_addr_to_if in pcap.o
      _find_dev in pcap.o
      _add_dev in pcap.o
      _pcap_lookupnet in pcap.o
      ...
  "_strdup", referenced from:
      _pcap_activate_bpf in pcap-bpf.o
      _add_dev in pcap.o
      _pcap_create in pcap.o
      _pcap_nametoportrange in nametoaddr.o
  "_strerror$UNIX2003", referenced from:
      _pcap_strerror in pcap.o
  "_strerror_r", referenced from:
      _pcap_fmt_errmsg_for_errno in fmtutils.o
  "_strlen", referenced from:
      _pcap_activate_bpf in pcap-bpf.o
      _check_bpf_bindable in pcap-bpf.o
      _add_dev in pcap.o
      _sdup in gencode.o
      _pcap_fmt_errmsg_for_errno in fmtutils.o
      _pcap__scan_string in scanner.o
  "_strncmp", referenced from:
      _pcap_activate_bpf in pcap-bpf.o
      _pcap_can_set_rfmon_bpf in pcap-bpf.o
      _check_bpf_bindable in pcap-bpf.o
      _check_setif_failure in pcap-bpf.o
  "_strncpy", referenced from:
      _pcap_activate_bpf in pcap-bpf.o
      _pcap_can_set_rfmon_bpf in pcap-bpf.o
      _get_if_flags in pcap-bpf.o
      _bpf_open_and_bind in pcap-bpf.o
  "_uname", referenced from:
      _pcap_activate_bpf in pcap-bpf.o
      _pcap_can_set_rfmon_bpf in pcap-bpf.o
  "_write$UNIX2003", referenced from:
      _pcap_inject_bpf in pcap-bpf.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libpcap.dylib] Error 1

**Comment by infrastation** [comment]
If this problem reproduces with the latest master branch of libpcap, please provide the steps to reproduce. Otherwise this request will be closed in 7 days.

**Comment by infrastation** [comment]
It is time.
