### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by panmengjia** [the-tcpdump-group/libpcap#987]
libpcap version ： 
1.10.0
operating system ：
 ubunut 20.04

configure:
./../libpcap/configure --prefix=$PWD-Install --host=arm-himix200-linux CC=arm-himix200-linux-gcc --with-pcap=linux --disable-ipv6  --enable-shared=yes --enable-static=yes

uname -a：
Linux hisilicon-desktop 5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

When i cross-compile libpcap with arm-himix200-linux-gcc ,i  encountered a problem as followed;

./../libpcap/bpf_image.c: In function 'bpf_image':
./../libpcap/bpf_image.c:309:15: error: 'BPF_MOD' undeclared (first use in this function)
  case BPF_ALU|BPF_MOD|BPF_X:
               ^~~~~~~
./../libpcap/bpf_image.c:309:15: note: each undeclared identifier is reported only once for each function it appears in
./../libpcap/bpf_image.c:324:15: error: 'BPF_XOR' undeclared (first use in this function)
  case BPF_ALU|BPF_XOR|BPF_X:
               ^~~~~~~
make: *** [Makefile:89: bpf_image.o] Error 1
make: *** Waiting for unfinished jobs....

I have "sudo apt-get install bison flex".how to fix this problem? Thanks!

**Comment by mcr** [comment]
While having bison and flex is important to be able to compile, your report is not about that.
(I don't know why you are disabling IPv6)
My guess is in your cross compilation environment, that the /usr/include/pcap/bpf.h you are using for the cross-compile does not have MPF_MOD.  There could be some kind of conflict between when libpcap is configured vs when you use it.

**Comment by guyharris** [comment]
> the /usr/include/pcap/bpf.h you are using for the cross-compile does not have BPF_MOD.

It *should* be using the pcap/bpf.h in the libpcap source tree, which should always define `BPF_MOD` and `BPF_XOR`.  I'll see if I can figure out why that's not happening.

However, if the target system's /usr/include/pcap/bpf.h doesn't define them, that may also mean that the target system's BPF interpreter doesn't *implement* them, in which case, for a live capture, we'll probably get an error trying to hand a filter expression using `%` or `^` to the kernel, and will fall back on doing filtering in userland.

**Comment by panmengjia** [comment]
I am a novice and I am not quite clear about what you said. Could you please give me some reference？Thanks!
@guyharris

**Comment by panmengjia** [comment]
I have solved the problem. Thank you for your reply.
I had this problem all the time（in version 1.10 or 1.8）, but in version 1.7, it compiled successfully and worked normally.
May I ask why?
Thank you very much!

**Comment by nehaljwani** [comment]
A git bisect reveals that starting with this commit, the problem occurs:
```
commit 0bb0b261a05bd0f396429bf99984343c9bade3b1 (refs/bisect/bad)
Author: Guy Harris <gharris@sonic.net>
Date:   Sat May 16 22:33:35 2020 -0700

    Avoid #define collisions with <linux/filter.h> or stuff it includes.

    Some programs, e.g. pktgen-dpdk, include both <linux/filter.h> and
    <pcap/bpf.h> in the same source file; both of them have BPF-instruction

    Just as we protect against <net/bpf.h> and <pcap/bpf.h> colliding, we
    protect against <linux/filter.h> and <pcap/bpf.h> colliding, although we
    need to protect fewer things as <linux/filter.h> doesn't define
    everything we need.

    This should address GitHub pull request #933.
```

If the kernel headers (specifically linux/filter.h) in cross compiler sysroot are too old, it will trigger this problem.

**Comment by guyharris** [comment]
2abff2bc2dbd2be3888330e9ce0df298dd441d8a should fix this.
