### ISSUE TITLE
pcap_stat overflowing uint.max

### ISSUE THREAD

**Issue by danairis** [the-tcpdump-group/libpcap#988]
On high traffic machines and after capturing for a day, the u_int of pcap_stat overflows. 
How would you feel about extending its properties from u_int to u_long?

**Comment by guyharris** [comment]
> How would you feel about extending its properties from u_int to u_long?

It would break binary compatibility (which matters on at least some platforms), so it's not an acceptable fix.

A *new* API would fix that problem; it could also fix other problems, such as 1) some statistics not being available on all platforms and 2) not all useful statistics are available.  An API that returns something similar to [a pcapng Interface Statistics Block](https://pcapng.github.io/pcapng/draft-tuexen-opsawg-pcapng.html#name-interface-statistics-block) would do both.

**Comment by guyharris** [comment]
(And it also wouldn't help on ILP32 platforms.)

**Comment by infrastation** [comment]
Is there any good reason to keep this issue open?

**Comment by guyharris** [comment]
> Is there any good reason to keep this issue open?

Only if we retitle it to "provide better API for getting packet statistics".  It's not going to happen with the current API, for binary compatibility reasons, and, as per my comment, a better API could solve other problems as well.

**Comment by infrastation** [comment]
Fine, let's put this item on the list then and close the issue.
