### ISSUE TITLE
filter 'type mgt subtype probe-req' does not work anymore

### ISSUE THREAD

**Issue by solsticedhiver** [the-tcpdump-group/libpcap#989]
Either with tcpdump **4.99** or libpcap **1.10**, a (bpf) filter of `type mgt subtype probe-req` gives the error:

    unknown 802.11 type

Previous versions of the tool did not give such error.

As a work-around, one have to use `subtype probe-req` only as filter

**Comment by guyharris** [comment]
Fixed in 6ff5d20e1b8b13917e538d735392a71bcd381b96.

**Comment by solsticedhiver** [comment]
When can we hope for a release ?

This is broken for me, and I can't do anything I want with lipcap.

**Comment by linxcow** [comment]
> 1. The bug is easy to reproduce using the filtertest test program in the testprogs directory (`testprogs/filtertest IEEE802_11 type mgt subtype prob-req`).
> 
>     2. Tcpdump prints that message because there's a bug in libpcap - _this_ bug.
> 
>     3. Fix incoming.

In which release of libpcap is this fix integrated?

**Comment by fxlb** [comment]
> In which release of libpcap is this fix incorporated?

libpcap 1.10.1 or later.
