### ISSUE TITLE
Issue with filtering packets using BPF / pcap_open_dead()

### ISSUE THREAD

**Issue by sumitece87** [the-tcpdump-group/libpcap#991]
I am using a DPDK application. I have a pointer to a packet and trying to match it against a BPF filter using:
// initialized before looking at the packet
pcap_open_dead(DLT_EN10MB, 65535);
pcap_compile(...)

// when I have a packet, I call
pcap_offline_filter(...)

The packets are always VLAN encapsulated. 

Whenever the filter is "vlan", I match all the packets. Other than that, it is not able to filter any other type (e.g., ip, arp).

**Comment by guyharris** [comment]
(Same question as on ask.wireshark.org, same answer as on ask.wireshark.org....)

> The packets are always VLAN encapsulated.

That means that all filters must be of the form "vlan and XXX"; for example, "vlan and ip" to find IP packets, "vlan and arp" to find ARP packets, etc..
