### ISSUE TITLE
CMake warning on Ubuntu 20.04 and Debian 11

### ISSUE THREAD

**Issue by fxlb** [the-tcpdump-group/libpcap#993]
CMake Deprecation Warning at CMakeLists.txt:16 (cmake_policy):
  The OLD behavior for policy CMP0042 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

**Comment by fxlb** [comment]
> CMake 3.19.4 on OpenBSD 6.9 produces similar output:
> 
> ```
> CMake Deprecation Warning at CMakeLists.txt:7 (cmake_minimum_required):
>   Compatibility with CMake < 2.8.12 will be removed from a future version of
>   CMake.
> 
>   Update the VERSION argument <min> value or use a ...<max> suffix to tell
>   CMake that the project does not need compatibility with older versions.
> ```

This warning was fixed by: a5d68ebafa182528dfbcdff6467b41be252e8f82.

For the CMP0042 warning, closing as duplicate of #1094 which has a Guy comment and a link to a fix proposal via a PR.

**Comment by guyharris** [comment]
So combination of #1138, fixed by a5d68ebafa182528dfbcdff6467b41be252e8f82, and #1094, fixed by PR #1111.
