### ISSUE TITLE
Incoming and outgoing packets are time stamped using different clocks

### ISSUE THREAD

**Issue by rass92** [the-tcpdump-group/libpcap#999]
Hello,

I am facing a problem with tcpdump because is using different clocks to make the timestamp for incoming and outgoing packets

I am synchronizing two devices with ptp4l and phc2sys, I see that the offset is around 10 nanoseconds. Both devices are using hardware timestamp

I am using the following command to capture the packets in both devices

```
tcpdump -i eno0 -w tracefile_BOARD_SERIAL.pcap -j adapter_unsynced -tt --time-stamp-precision=nano
```

When I see the traces I see that the difference between outgoing packets and incoming packets is of 37 seconds.

It seems like tcpdump is using two different clocks to make the timestamp, is there a way for it to use one clock for incoming and outgoing packets

I am using a yocto distribution

```
ID="poky"
NAME="Poky (Yocto Project Reference Distro)"
VERSION="3.0.4 (zeus)"
VERSION_ID="3.0.4"
PRETTY_NAME="Poky (Yocto Project Reference Distro) 3.0.4 (zeus)"
```

Thank you in advance

**Comment by rass92** [comment]
Thank you guyharris for your answer and the detailed explanation.

> Have it use the default host clock, i.e. the clock maintained by the Linux kernel. That clock is the same for incoming and outgoing packets, although its disadvantage is that it doesn't reflect when an outgoing packet makes it onto the network (it reflects some earlier time when the networking stack in the kernel time stamps the packet) nor does it reflect when an incoming packet is received from the network (it reflects some later time when the packet makes it to the part of the networking stack that time stamps the packet).

As you stated here there is a way to use the same clock for outgoing and incoming packets. I understand that tcpdump is not able to give the exact time when the packets in put into the network. But as I stated before this is not happening to me, I can imagine that maybe I have something configure wrong or use the wrong flags. Can you please help to see where is my error?

This is the command I am using

```
tcpdump -i eno0 -w tracefile_BOARD_SERIAL.pcap -j adapter_unsynced -tt --time-stamp-precision=nano
```

What should I change?

Thank you in advance

**Comment by guyharris** [comment]
> Can you please help to see where is my error?

It's the `-j adapter_unsynced`.  Remove that and tcpdump will no longer ask libpcap to use a capture mechanism that uses different clocks for incoming and outgoing packets.

**Comment by rass92** [comment]
Yes it work perfectly, thank you very much.
